$axure.loadCurrentPage({
  "url":"等待接受邀請.html",
  "generationDate":new Date(1404292444875.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"40b956ae530c4257aeeed317ec2ef5bd",
    "type":"Axure:Page",
    "name":"等待接受邀請",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"124db377a2f9412db5f7788b839953b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b1da6d404b9431c84aae884651138b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"0b4b68d54eb74b4f8af54468f81a5a5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1902,
              "height":640},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9fc5817ebf9415885246973b31d5d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1902,
                  "height":640},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u0.png"}},
{
          "id":"6a296363627b46f0b5dca354e3f8e0fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1902,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609df9e01b3843109f7232ebdb01aa6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1902,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u2.png"}},
{
          "id":"af7715f14ecd4e8fba3b9a7161173557",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":160},
            "size":{
              "width":1024,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc5a12571ed480b8e9b8a88594328ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":160},
                "size":{
                  "width":1024,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u4.png"}},
{
          "id":"58a2b9b308c2423fb65b0b3298e2695f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab37f5c3b8314193a4a6275995d49f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"62c1671058f74aa59f48ba5ab9e5b835",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898633632d6e4a14a2c6ae018f05055c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u8.png"}},
{
          "id":"d02dffadb65542fb8abf32015cf24083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da3375dd472f408995d9488d874ea8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07de7d8fcdd240e4bc4daae6c95d8fa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f59f2ea1cdd540f6b393ef8167565b3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":190},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u16.png"}},
{
          "id":"51fb99ca27fe4091a06d3430b6f07623",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":615,
              "y":190},
            "size":{
              "width":41,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e51f865eca4957a5ae9525f47c5d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":615,
                  "y":190},
                "size":{
                  "width":41,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u18.png"}},
{
          "id":"f5ebad21c2f7492c97417aac01edd02f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":203},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005e819128754572b2ee3aa0d55ab29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":203},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u20.png"}},
{
          "id":"0621d6385cb64c05bc3b2da1f347dc85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37844e1ac4b34701bc6eefa5c69771d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7be0f255f2a34bfe91c09c0781a6099e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":380},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3863abd8287045ad9832e95226b61598",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":380},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3482ea1d4f5a4ff5893e1d5362a088f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":440},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04d2af62ae05453497707c9780c5a28e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":440},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90adb0b128ba41ce87fb9d9d7486d5a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":260},
            "size":{
              "width":730,
              "height":400},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80242a1ecb894a8d8ae71c9cd56a1d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":260},
                "size":{
                  "width":730,
                  "height":400},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u26.png"}},
{
          "id":"c6e8ca35fbd84d8cba344f73e406122e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":282},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34936fafa7a64560ad4655c691cd584b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":282},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u30.png"}},
{
          "id":"f973aef670514f33bf11b2e65e183ceb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":281},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103ce36cd0684a53b04266fac6a91ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":281},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"0bae2e106b804a31be01f56074d3688f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1b0549ce9574901977c2903817718c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"a966ba049a0449dc9e907ccd910101e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5264d75eaa4b41b6076a6a451f213d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"2c5106379606492b805239c1bddbb2fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":10},
            "size":{
              "width":138,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa9079e07e4549fa83ef9a737d6763f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":10},
                "size":{
                  "width":138,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfc63b99af9b47e4af311cd2c1b20b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":616,
              "y":10},
            "size":{
              "width":83,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af8f618030f8483db1aa2bf06c1dd8ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":616,
                  "y":10},
                "size":{
                  "width":83,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77cd333717064839bbf3d1dafa165879",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":737,
              "y":10},
            "size":{
              "width":55,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988aaf705f514aac9a1d563a72b0c406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":737,
                  "y":10},
                "size":{
                  "width":55,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16037520aef4e6ab6bef45960947c93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":830,
              "y":10},
            "size":{
              "width":58,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f35667f83a90459faa18c794cab7d734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":830,
                  "y":10},
                "size":{
                  "width":58,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de0112dd4ba0456ca5979bf50dce3f2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1903,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7721df3289248809664900b3eb7feb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1903,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u51.png"}},
{
          "id":"d49225a052cc489a87da7940f62f20a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"543a401e3c3a4d37aa6aa57379f09d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e8ab17a0f7749a9a3c7f35836dd427f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79abbb1f41854dd78db1d10a6a68a701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"186960b845a14dcf97726c103b90e737",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0027b20db21c4e79acc82073c5f6856a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"190d4478e2c04807936dcdf3953340c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f98d74c85764b99af71a3590cfa95ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c773d74348e342ce8305a068a87d7cb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":313},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19001ca89a5841809ae7213f934dbff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":313},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"d49d85fff20f4c898f861e302d7f63cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":480,
              "y":260},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6d27e497cb147ba81a08e2ea4e1134d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":480,
                  "y":260},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/等待接受邀請/u56.png"}},
{
          "id":"dea96cd2221640e3bcd9dc1673fee968",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":750,
              "y":274},
            "size":{
              "width":200,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30809032755842a8a6120c5808a53e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":750,
                  "y":274},
                "size":{
                  "width":200,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c68dcee94c9e4ae2ac6c897abe60918e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":974,
              "y":274},
            "size":{
              "width":213,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"154d365ff01d41d785ebaab95de23f7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":974,
                  "y":274},
                "size":{
                  "width":213,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/等待接受邀請/u60.png"}},
{
          "id":"a08085b8a1874e85b781621a5582c7af",
          "label":"Button.Simple",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1243.5,
              "y":277},
            "size":{
              "width":90,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fa909209cc4459801069f51d472b0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9}]}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF363636,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1243.5,
                  "y":277},
                "size":{
                  "width":90,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/等待接受邀請/button_simple_u62.png",
            "mouseOver~":"images/等待接受邀請/button_simple_u62_mouseOver.png",
            "mouseDown~":"images/等待接受邀請/button_simple_u62_mouseDown.png"}},
{
          "id":"739d16894d494e1e9e38dedbb1209d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1187,
              "y":313},
            "size":{
              "width":223,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea70f66232ad4bd3838a56f293d7629d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1187,
                  "y":313},
                "size":{
                  "width":223,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"035818a8a06d40b482072f75e441c1ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b7d45fc515348d4a402c98194840784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f735bc027ff94c309de09befd378a6aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee185f2bfd74a07a27fdbf4e99e6a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79cb75541c194179bf357e0f0eee6ae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95621224a87647a69a134fffbaf3804f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b14ab9e1d80c4e0b87ffa50b4d61a0ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b2f382a44e42ea9de2c8e1e8301571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"592983ef10e34f71bc934af291e3af93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"133b572c72884283a0bb17e139078269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "124db377a2f9412db5f7788b839953b5":{
      "scriptId":"u0"},
    "3b1da6d404b9431c84aae884651138b6":{
      "scriptId":"u1"},
    "0b4b68d54eb74b4f8af54468f81a5a5a":{
      "scriptId":"u2"},
    "c9fc5817ebf9415885246973b31d5d78":{
      "scriptId":"u3"},
    "6a296363627b46f0b5dca354e3f8e0fb":{
      "scriptId":"u4"},
    "609df9e01b3843109f7232ebdb01aa6a":{
      "scriptId":"u5"},
    "af7715f14ecd4e8fba3b9a7161173557":{
      "scriptId":"u6"},
    "efc5a12571ed480b8e9b8a88594328ea":{
      "scriptId":"u7"},
    "58a2b9b308c2423fb65b0b3298e2695f":{
      "scriptId":"u8"},
    "ab37f5c3b8314193a4a6275995d49f02":{
      "scriptId":"u9"},
    "62c1671058f74aa59f48ba5ab9e5b835":{
      "scriptId":"u10"},
    "898633632d6e4a14a2c6ae018f05055c":{
      "scriptId":"u11"},
    "d02dffadb65542fb8abf32015cf24083":{
      "scriptId":"u12"},
    "da3375dd472f408995d9488d874ea8f2":{
      "scriptId":"u13"},
    "07de7d8fcdd240e4bc4daae6c95d8fa4":{
      "scriptId":"u14"},
    "f59f2ea1cdd540f6b393ef8167565b3b":{
      "scriptId":"u15"},
    "51fb99ca27fe4091a06d3430b6f07623":{
      "scriptId":"u16"},
    "65e51f865eca4957a5ae9525f47c5d43":{
      "scriptId":"u17"},
    "f5ebad21c2f7492c97417aac01edd02f":{
      "scriptId":"u18"},
    "005e819128754572b2ee3aa0d55ab29b":{
      "scriptId":"u19"},
    "0621d6385cb64c05bc3b2da1f347dc85":{
      "scriptId":"u20"},
    "37844e1ac4b34701bc6eefa5c69771d2":{
      "scriptId":"u21"},
    "7be0f255f2a34bfe91c09c0781a6099e":{
      "scriptId":"u22"},
    "3863abd8287045ad9832e95226b61598":{
      "scriptId":"u23"},
    "3482ea1d4f5a4ff5893e1d5362a088f8":{
      "scriptId":"u24"},
    "04d2af62ae05453497707c9780c5a28e":{
      "scriptId":"u25"},
    "90adb0b128ba41ce87fb9d9d7486d5a5":{
      "scriptId":"u26"},
    "80242a1ecb894a8d8ae71c9cd56a1d4f":{
      "scriptId":"u27"},
    "c6e8ca35fbd84d8cba344f73e406122e":{
      "scriptId":"u28"},
    "34936fafa7a64560ad4655c691cd584b":{
      "scriptId":"u29"},
    "f973aef670514f33bf11b2e65e183ceb":{
      "scriptId":"u30"},
    "103ce36cd0684a53b04266fac6a91ec7":{
      "scriptId":"u31"},
    "0bae2e106b804a31be01f56074d3688f":{
      "scriptId":"u32"},
    "c1b0549ce9574901977c2903817718c8":{
      "scriptId":"u33"},
    "a966ba049a0449dc9e907ccd910101e5":{
      "scriptId":"u34"},
    "eb5264d75eaa4b41b6076a6a451f213d":{
      "scriptId":"u35"},
    "2c5106379606492b805239c1bddbb2fa":{
      "scriptId":"u36"},
    "fa9079e07e4549fa83ef9a737d6763f2":{
      "scriptId":"u37"},
    "cfc63b99af9b47e4af311cd2c1b20b8f":{
      "scriptId":"u38"},
    "af8f618030f8483db1aa2bf06c1dd8ca":{
      "scriptId":"u39"},
    "77cd333717064839bbf3d1dafa165879":{
      "scriptId":"u40"},
    "988aaf705f514aac9a1d563a72b0c406":{
      "scriptId":"u41"},
    "e16037520aef4e6ab6bef45960947c93":{
      "scriptId":"u42"},
    "f35667f83a90459faa18c794cab7d734":{
      "scriptId":"u43"},
    "de0112dd4ba0456ca5979bf50dce3f2d":{
      "scriptId":"u44"},
    "b7721df3289248809664900b3eb7feb4":{
      "scriptId":"u45"},
    "d49225a052cc489a87da7940f62f20a1":{
      "scriptId":"u46"},
    "543a401e3c3a4d37aa6aa57379f09d1a":{
      "scriptId":"u47"},
    "0e8ab17a0f7749a9a3c7f35836dd427f":{
      "scriptId":"u48"},
    "79abbb1f41854dd78db1d10a6a68a701":{
      "scriptId":"u49"},
    "186960b845a14dcf97726c103b90e737":{
      "scriptId":"u50"},
    "0027b20db21c4e79acc82073c5f6856a":{
      "scriptId":"u51"},
    "190d4478e2c04807936dcdf3953340c0":{
      "scriptId":"u52"},
    "3f98d74c85764b99af71a3590cfa95ee":{
      "scriptId":"u53"},
    "c773d74348e342ce8305a068a87d7cb4":{
      "scriptId":"u54"},
    "19001ca89a5841809ae7213f934dbff4":{
      "scriptId":"u55"},
    "d49d85fff20f4c898f861e302d7f63cd":{
      "scriptId":"u56"},
    "f6d27e497cb147ba81a08e2ea4e1134d":{
      "scriptId":"u57"},
    "dea96cd2221640e3bcd9dc1673fee968":{
      "scriptId":"u58"},
    "30809032755842a8a6120c5808a53e9c":{
      "scriptId":"u59"},
    "c68dcee94c9e4ae2ac6c897abe60918e":{
      "scriptId":"u60"},
    "154d365ff01d41d785ebaab95de23f7b":{
      "scriptId":"u61"},
    "a08085b8a1874e85b781621a5582c7af":{
      "scriptId":"u62"},
    "57fa909209cc4459801069f51d472b0c":{
      "scriptId":"u63"},
    "739d16894d494e1e9e38dedbb1209d4b":{
      "scriptId":"u64"},
    "ea70f66232ad4bd3838a56f293d7629d":{
      "scriptId":"u65"},
    "035818a8a06d40b482072f75e441c1ed":{
      "scriptId":"u66"},
    "4b7d45fc515348d4a402c98194840784":{
      "scriptId":"u67"},
    "f735bc027ff94c309de09befd378a6aa":{
      "scriptId":"u68"},
    "eee185f2bfd74a07a27fdbf4e99e6a1b":{
      "scriptId":"u69"},
    "79cb75541c194179bf357e0f0eee6ae0":{
      "scriptId":"u70"},
    "95621224a87647a69a134fffbaf3804f":{
      "scriptId":"u71"},
    "b14ab9e1d80c4e0b87ffa50b4d61a0ef":{
      "scriptId":"u72"},
    "d1b2f382a44e42ea9de2c8e1e8301571":{
      "scriptId":"u73"},
    "592983ef10e34f71bc934af291e3af93":{
      "scriptId":"u74"},
    "133b572c72884283a0bb17e139078269":{
      "scriptId":"u75"}}});