$axure.loadCurrentPage({
  "url":"企業雇主註冊流程.html",
  "generationDate":new Date(1404292430684.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"8eb03d78e073454a9e82ebd206ba232d",
    "type":"Axure:Page",
    "name":"企業雇主註冊流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"02aa76c7858146dfa38638545b38e3a6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d6606473398143acb34b1ea1fa8e1030",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1307}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f299fcfa84844cba9e9486fb02a9d06a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1307}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/企業雇主註冊流程/u1.png"}},
{
                  "id":"f62bed5d5e5e43b3ac11290033cabd2c",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1300,
                      "y":1030},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e8851763f754277b34bfcb14e6640d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1300,
                          "y":1030},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State3",
                              "panelsToStates":[{
                                  "panelPath":["d1eb8dcc6eb04ebab9d2d09afb80ca65"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"3b25d32dd9f64a91aed8eb5553a3ad7e",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cba7902d29e8485792ef9c4266c54b33",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1028}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d8ede5f50fc4be396f398e6a5b0e9cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1028}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/企業雇主註冊流程/u5.png"}},
{
                  "id":"2b0979d88a7c487da165b627f07582ec",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":480,
                      "y":750},
                    "size":{
                      "width":130,
                      "height":65},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ac689f0aa524263923f59cd4abe5edb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":480,
                          "y":750},
                        "size":{
                          "width":130,
                          "height":65},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State1",
                              "panelsToStates":[{
                                  "panelPath":["d1eb8dcc6eb04ebab9d2d09afb80ca65"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"808bf0d9a6b84d21ac06e310e53dfb7a",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1290,
                      "y":750},
                    "size":{
                      "width":130,
                      "height":65},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06f1829a733d4d979746f1017767d607",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1290,
                          "y":750},
                        "size":{
                          "width":130,
                          "height":65},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State4",
                              "panelsToStates":[{
                                  "panelPath":["d1eb8dcc6eb04ebab9d2d09afb80ca65"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"903c19b5b91a44a7af0ff2765c04af78",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"407edc23968f4962a96ed7b5055c519b",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1604}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31652ebf61c6419897b8dd9cead3e329",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1604}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/企業雇主註冊流程/u11.png"}},
{
                  "id":"f9bb4c3316ee49819916d814d90317ca",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":480,
                      "y":1330},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ce898da881346509c11dc81bc7d2c3e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":480,
                          "y":1330},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State3",
                              "panelsToStates":[{
                                  "panelPath":["d1eb8dcc6eb04ebab9d2d09afb80ca65"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ced46d0a9846405ab1c90bd0176d1a91",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1300,
                      "y":1320},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"709ff390d1384de78e6a68ad9b99cf1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1300,
                          "y":1320},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State5",
                              "panelsToStates":[{
                                  "panelPath":["d1eb8dcc6eb04ebab9d2d09afb80ca65"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c56d9b1a127744998f02af5010f7b674",
              "label":"State5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6ae6fcd805674667a94f107364ad2d85",
                  "label":"",
                  "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1334}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a979f4c272a4c96a5f588b804e870e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1eb8dcc6eb04ebab9d2d09afb80ca65",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1334}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/企業雇主註冊流程/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "d1eb8dcc6eb04ebab9d2d09afb80ca65":{
      "scriptId":"u0"},
    "d6606473398143acb34b1ea1fa8e1030":{
      "scriptId":"u1"},
    "f299fcfa84844cba9e9486fb02a9d06a":{
      "scriptId":"u2"},
    "f62bed5d5e5e43b3ac11290033cabd2c":{
      "scriptId":"u3"},
    "9e8851763f754277b34bfcb14e6640d9":{
      "scriptId":"u4"},
    "cba7902d29e8485792ef9c4266c54b33":{
      "scriptId":"u5"},
    "5d8ede5f50fc4be396f398e6a5b0e9cd":{
      "scriptId":"u6"},
    "2b0979d88a7c487da165b627f07582ec":{
      "scriptId":"u7"},
    "3ac689f0aa524263923f59cd4abe5edb":{
      "scriptId":"u8"},
    "808bf0d9a6b84d21ac06e310e53dfb7a":{
      "scriptId":"u9"},
    "06f1829a733d4d979746f1017767d607":{
      "scriptId":"u10"},
    "407edc23968f4962a96ed7b5055c519b":{
      "scriptId":"u11"},
    "31652ebf61c6419897b8dd9cead3e329":{
      "scriptId":"u12"},
    "f9bb4c3316ee49819916d814d90317ca":{
      "scriptId":"u13"},
    "6ce898da881346509c11dc81bc7d2c3e":{
      "scriptId":"u14"},
    "ced46d0a9846405ab1c90bd0176d1a91":{
      "scriptId":"u15"},
    "709ff390d1384de78e6a68ad9b99cf1b":{
      "scriptId":"u16"},
    "6ae6fcd805674667a94f107364ad2d85":{
      "scriptId":"u17"},
    "0a979f4c272a4c96a5f588b804e870e1":{
      "scriptId":"u18"}}});