$axure.loadCurrentPage({
  "url":"評價完成.html",
  "generationDate":new Date(1404292441619.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"b45a3955fa204ac58f92f4e793fa3f5c",
    "type":"Axure:Page",
    "name":"評價完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6e43f6081ff545d09ccc811e760a8433",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e2af79d1b34111bec4d1c348fc0077",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"69f74f7bef1c4d6382544710f4d4ec80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1101},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c262a225c7ff4bebb7e3f1b6a8096308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1101},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"6fb8821ccd1447d785aff907601a63c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5941af930bcc47e39b5a522ac1a942d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"4e8f2a33599c4278bc6db8abfa45c365",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":919},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"806d96b2943e4f90858e483939cb2060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":919},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"34c540c1058d42c29494083d93981322",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1065},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38dd3ca100c4fd880ea7c2ffa71b737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1065},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"2e7628e7a52c42bf8511dcc37f938878",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ff2062cb2544ef841fcf16eab60b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb3c2b7049dc4a9ba8a7b3da07806198",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":485,
              "y":1001},
            "size":{
              "width":145,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a00f9448574e30a63aaf680adeb82e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":485,
                  "y":1001},
                "size":{
                  "width":145,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"763d3c94482e4af6b649647a55736db7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":640,
              "y":1010},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"634d7e52d0b64c998d3eb8770bdf5e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":640,
                  "y":1010},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be36f00ace0649a5ac297f94b031fff3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":478.5,
              "y":147},
            "size":{
              "width":963,
              "height":103},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b7a007abb0439483d3e6112314a1c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":478.5,
                  "y":147},
                "size":{
                  "width":963,
                  "height":103},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/終止合約/u25.png"}},
{
          "id":"d5904201947d412a94734a0c57e6ba42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":541,
              "y":170},
            "size":{
              "width":440,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b58e221893f43dc96d7477030b51001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":541,
                  "y":170},
                "size":{
                  "width":440,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/評價完成/u18.png"}},
{
          "id":"c99b24895c5646b8aacd965e997ee9f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":541,
              "y":200},
            "size":{
              "width":79,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b57fa01f9624bd18a394a508f36039a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":541,
                  "y":200},
                "size":{
                  "width":79,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6e43f6081ff545d09ccc811e760a8433":{
      "scriptId":"u0"},
    "18e2af79d1b34111bec4d1c348fc0077":{
      "scriptId":"u1"},
    "69f74f7bef1c4d6382544710f4d4ec80":{
      "scriptId":"u2"},
    "c262a225c7ff4bebb7e3f1b6a8096308":{
      "scriptId":"u3"},
    "6fb8821ccd1447d785aff907601a63c0":{
      "scriptId":"u4"},
    "5941af930bcc47e39b5a522ac1a942d2":{
      "scriptId":"u5"},
    "4e8f2a33599c4278bc6db8abfa45c365":{
      "scriptId":"u6"},
    "806d96b2943e4f90858e483939cb2060":{
      "scriptId":"u7"},
    "34c540c1058d42c29494083d93981322":{
      "scriptId":"u8"},
    "e38dd3ca100c4fd880ea7c2ffa71b737":{
      "scriptId":"u9"},
    "2e7628e7a52c42bf8511dcc37f938878":{
      "scriptId":"u10"},
    "00ff2062cb2544ef841fcf16eab60b0d":{
      "scriptId":"u11"},
    "eb3c2b7049dc4a9ba8a7b3da07806198":{
      "scriptId":"u12"},
    "d6a00f9448574e30a63aaf680adeb82e":{
      "scriptId":"u13"},
    "763d3c94482e4af6b649647a55736db7":{
      "scriptId":"u14"},
    "634d7e52d0b64c998d3eb8770bdf5e4d":{
      "scriptId":"u15"},
    "be36f00ace0649a5ac297f94b031fff3":{
      "scriptId":"u16"},
    "d0b7a007abb0439483d3e6112314a1c7":{
      "scriptId":"u17"},
    "d5904201947d412a94734a0c57e6ba42":{
      "scriptId":"u18"},
    "8b58e221893f43dc96d7477030b51001":{
      "scriptId":"u19"},
    "c99b24895c5646b8aacd965e997ee9f3":{
      "scriptId":"u20"},
    "8b57fa01f9624bd18a394a508f36039a":{
      "scriptId":"u21"}}});