$axure.loadCurrentPage({
  "url":"檢視合約_固定薪資_.html",
  "generationDate":new Date(1404292450340.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"32d3fdae3e364d609aa89a5284d6cdcb",
    "type":"Axure:Page",
    "name":"檢視合約(固定薪資)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2628c3af2fdd4600a56f9e1853d4ae93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5feef2638fd5493dbc5147221b2ada76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"ead84bbbe0494247b45314a5096753e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b07da766f6649c3915d27213fe4255e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":843},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"0b5967d327f74ab48fc16bc0523d3bf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5b4e95bb69410095d435c666056893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"5de0e844db724f4cae2e4f4667d64967",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":669},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41dd4231fbde450aa6d60f057ae1cfca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":669},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"1be9374161bf4f9c8e0ac4fa2bdc1323",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":820},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"060f892a76dd4d288fbc22f08f207f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":820},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"605ff25a4df3468db5b4b77d05660e32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"503d65a3f37f451daf90a12753a672f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22a4e7ba5f1c409ca3ed3bb2566d260d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":476,
              "y":157},
            "size":{
              "width":200,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18b6e24ea65a4642a568ac45d3c7bedb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":476,
                  "y":157},
                "size":{
                  "width":200,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u22.png"}},
{
          "id":"78aad50296d0420399c54124b5b85cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":404},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29ebbcc1be642a7bb1dbed06e75cc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":404},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"817b65c3b2c94c6d819c78e707b24491",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":404},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6e7c6ec371e47a9a6c0aac38fe42920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":404},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"816bdb03c8bf4fe48f565bdc024c95d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1137,
              "y":257},
            "size":{
              "width":310,
              "height":203},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a814f82286b46eca7dfbde430b726a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1137,
                  "y":257},
                "size":{
                  "width":310,
                  "height":203},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視正在執行中的合約/u38.png"}},
{
          "id":"7bdf6de3dbe54818ae417cef618157a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":298},
            "size":{
              "width":200,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80208709cd6349cf81ceb9ace2c28e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":298},
                "size":{
                  "width":200,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f53631e43fe42ce919bbf0d191d9d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1242,
              "y":268},
            "size":{
              "width":98,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a27d9365eb42e0b14f73db8a458cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1242,
                  "y":268},
                "size":{
                  "width":98,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e543c430de0a4b9a81031a79fe38d683",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":400},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/申請案件-檢視案件合約/u62_line.png"}},
{
          "id":"5d1d5662376c4fe0995cd725a581702b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1151,
              "y":327},
            "size":{
              "width":52,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672ae18a1763402bbfe677569e8ed0e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1151,
                  "y":327},
                "size":{
                  "width":52,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u67.png"}},
{
          "id":"68f9bc61b10c4953be3b277435e25200",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":1213,
              "y":338},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520806f5ff73426185b1d219c7e75479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":1213,
                  "y":338},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83d65e4ed58d421a8b8ce623a8a4801b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":420},
            "size":{
              "width":279,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a14d302be0341b38433cc32fb2d5a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":420},
                "size":{
                  "width":279,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d4a11ed3c7e4dc1a46df42f80356689",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":379},
            "size":{
              "width":644,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/申請案件-檢視案件合約/u75_line.png"}},
{
          "id":"91b8408d4cca44958ec6cf32e80954c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":476,
              "y":196},
            "size":{
              "width":384,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a33351643c4e22aa50446b5c9f4683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":476,
                  "y":196},
                "size":{
                  "width":384,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b2c232807f44e51925de323c6f1c244",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":425},
            "size":{
              "width":200,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135ba3d6157c45bc9824a85177857252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":425},
                "size":{
                  "width":200,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視案件申請的詳細資料 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視案件申請的詳細資料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e500113f03bb4a09b1aa4fc3ee76971f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":250},
            "size":{
              "width":127,
              "height":107},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e35b4eeb97514ad2b34e0ac438729442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":250},
                "size":{
                  "width":127,
                  "height":107},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視正在執行中的合約/u56.png"}},
{
          "id":"547488998ef14aa2bee029b42e3b5c30",
          "label":"Button.Simple",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1137,
              "y":470},
            "size":{
              "width":148,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f524932dfa240b0ac350165cd59113a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9}]}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF363636,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1137,
                  "y":470},
                "size":{
                  "width":148,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視正在執行中的合約/button_simple_u62.png",
            "mouseOver~":"images/檢視正在執行中的合約/button_simple_u62_mouseOver.png",
            "mouseDown~":"images/檢視正在執行中的合約/button_simple_u62_mouseDown.png"}},
{
          "id":"538bcae53a5b4d6193a911f886d33c5b",
          "label":"Button.Red",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE75859}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD24B4C}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFD95C5C},
            "location":{
              "x":1299,
              "y":470},
            "size":{
              "width":148,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fff86a22b4d444eacb7425ca0dff7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE75859}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD24B4C}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD95C5C},
                "location":{
                  "x":1299,
                  "y":470},
                "size":{
                  "width":148,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視正在執行中的合約/button_red_u64.png",
            "mouseOver~":"images/檢視正在執行中的合約/button_red_u64_mouseOver.png",
            "mouseDown~":"images/檢視正在執行中的合約/button_red_u64_mouseDown.png"}},
{
          "id":"789abe974210485b833a4410a07327da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":990,
              "y":340},
            "size":{
              "width":137,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"363f616bb371402080c7d938bf58122c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":340},
                "size":{
                  "width":137,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/已經結束的案件合約/u68.png"}},
{
          "id":"43ffe42ca00f41d4a43414dfc76371e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1137,
              "y":470},
            "size":{
              "width":148,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bba60b3110994135ab4ad90a9c46ce76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1137,
                  "y":470},
                "size":{
                  "width":148,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 申請退款 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"申請退款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f64182252ef94a4486519d72cd85e604",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1299,
              "y":470},
            "size":{
              "width":148,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f432855c0d76499783fa996521826eaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1299,
                  "y":470},
                "size":{
                  "width":148,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 終止合約 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"終止合約.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62791e28086a4c0f868fc39a319563cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":540},
            "size":{
              "width":971,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/檢視合約_固定薪資_/u48_line.png"}},
{
          "id":"d014865998b6411d86a9841f3ffcd529",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":560},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa490c27877748049d6e6c133e183246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":560},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"1dba8899fd234239967401687e94f645",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":608},
            "size":{
              "width":57,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d409165edec5409084c4f917fb9f5229",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":608},
                "size":{
                  "width":57,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u186.png"}},
{
          "id":"eae5d5e6dc534b71a08d8dd614dc5fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":608},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a92bd789991431d903e2819ce0faee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":608},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"9b31b79aebf24174b7589ee6889d545f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":608},
            "size":{
              "width":410,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a44c1a6f7a45e8a17d9790d7d05816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":736,
                  "y":608},
                "size":{
                  "width":410,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u190.png"}},
{
          "id":"08a43a56ef26493593f37dfacff95c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1325,
              "y":608},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa88d88e2ada429aa3b348f4d318f0d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1325,
                  "y":608},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"f575623f84644eacbc1d333f80a7fea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":452},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb0fa44a3184098b3e9a581d0f70915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":452},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"b6d4c51000b342809f0d3e88eb7818cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":452},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94e389d6119b4d46a509803e938aef0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":452},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"def2e11020044fa0867b75eb4f100043",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1178,
              "y":608},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d2b266dd3644168ec6b3fdcfd031a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1178,
                  "y":608},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"56065124a9da435384c58fd97a9b802d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":650},
            "size":{
              "width":57,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"018f8b6ecdcf4927a67dcc1f37310131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":650},
                "size":{
                  "width":57,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u186.png"}},
{
          "id":"0241233562644e1ba9710fce0fa63285",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":650},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994da042638a4d82af9458d8ab69e0b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":650},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"4765e45a07c04d219b6a10719c7f73c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":650},
            "size":{
              "width":410,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dc6ae74e13f4a34b6bee43cf92d6503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":736,
                  "y":650},
                "size":{
                  "width":410,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u190.png"}},
{
          "id":"8fa8c25cc62c48fdb0e4a081d1a5c1c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1325,
              "y":650},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be8bc7cfcf4848159a5af8e303d59963",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1325,
                  "y":650},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"81dd8bc1c2cb4e9a9033325e3ab956b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1178,
              "y":650},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5515378ebad04320b255af6a5718c077",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1178,
                  "y":650},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"ac668f3980104f81a02d4c42b818878b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":700},
            "size":{
              "width":57,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46aa82e7b4e9442e912bce053dd8e316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":700},
                "size":{
                  "width":57,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u186.png"}},
{
          "id":"e9fa8d29440a4e55b1cf372c7433bedf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":700},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9099927c6dee4da4840f0e77c2c71ba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":700},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"16d2980e7d754fb39a51bbf7d7d78c6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":736,
              "y":700},
            "size":{
              "width":410,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8334a95e6614904954da954313a2fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":736,
                  "y":700},
                "size":{
                  "width":410,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u190.png"}},
{
          "id":"db6ff82c181a4f4bb1c5ee1b80bcdfa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1325,
              "y":700},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff8cb66628e49aab8ffbcc683e3b433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1325,
                  "y":700},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"3eebfa9e695444919fc21b838481a8eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1178,
              "y":700},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"622598167fb34c9486a9ae6a504df0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1178,
                  "y":700},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"93061b18fc6748df976d02d498acb2b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":760},
            "size":{
              "width":57,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456b9b16e16a4ec583b54ba498e02a5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":760},
                "size":{
                  "width":57,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u186.png"}},
{
          "id":"f1cd6f0373614c0fa3be27c1402d2de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":760},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf1a67722844c198a7aa3570aeafbfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":760},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"7f61fc22aa894e068506d5a5bf55bc63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":736,
              "y":760},
            "size":{
              "width":410,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7908174256d14c7ea9dd05114b3da4f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":736,
                  "y":760},
                "size":{
                  "width":410,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u190.png"}},
{
          "id":"01dd6ad88db94e3ca84dcfbc124911a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1325,
              "y":760},
            "size":{
              "width":115,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4208e719cb47c7912acd1be497ba33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1325,
                  "y":760},
                "size":{
                  "width":115,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視合約/u188.png"}},
{
          "id":"5092ad8ae46849f299cd8888e9b5156c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1178,
              "y":760},
            "size":{
              "width":115,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6124d203168c4a26b6eb3f20a41fd1d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1178,
                  "y":760},
                "size":{
                  "width":115,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2628c3af2fdd4600a56f9e1853d4ae93":{
      "scriptId":"u0"},
    "5feef2638fd5493dbc5147221b2ada76":{
      "scriptId":"u1"},
    "ead84bbbe0494247b45314a5096753e4":{
      "scriptId":"u2"},
    "2b07da766f6649c3915d27213fe4255e":{
      "scriptId":"u3"},
    "0b5967d327f74ab48fc16bc0523d3bf8":{
      "scriptId":"u4"},
    "5c5b4e95bb69410095d435c666056893":{
      "scriptId":"u5"},
    "5de0e844db724f4cae2e4f4667d64967":{
      "scriptId":"u6"},
    "41dd4231fbde450aa6d60f057ae1cfca":{
      "scriptId":"u7"},
    "1be9374161bf4f9c8e0ac4fa2bdc1323":{
      "scriptId":"u8"},
    "060f892a76dd4d288fbc22f08f207f21":{
      "scriptId":"u9"},
    "605ff25a4df3468db5b4b77d05660e32":{
      "scriptId":"u10"},
    "503d65a3f37f451daf90a12753a672f1":{
      "scriptId":"u11"},
    "22a4e7ba5f1c409ca3ed3bb2566d260d":{
      "scriptId":"u12"},
    "18b6e24ea65a4642a568ac45d3c7bedb":{
      "scriptId":"u13"},
    "78aad50296d0420399c54124b5b85cab":{
      "scriptId":"u14"},
    "f29ebbcc1be642a7bb1dbed06e75cc2a":{
      "scriptId":"u15"},
    "817b65c3b2c94c6d819c78e707b24491":{
      "scriptId":"u16"},
    "d6e7c6ec371e47a9a6c0aac38fe42920":{
      "scriptId":"u17"},
    "816bdb03c8bf4fe48f565bdc024c95d5":{
      "scriptId":"u18"},
    "4a814f82286b46eca7dfbde430b726a3":{
      "scriptId":"u19"},
    "7bdf6de3dbe54818ae417cef618157a6":{
      "scriptId":"u20"},
    "80208709cd6349cf81ceb9ace2c28e32":{
      "scriptId":"u21"},
    "9f53631e43fe42ce919bbf0d191d9d37":{
      "scriptId":"u22"},
    "95a27d9365eb42e0b14f73db8a458cb0":{
      "scriptId":"u23"},
    "e543c430de0a4b9a81031a79fe38d683":{
      "scriptId":"u24"},
    "5d1d5662376c4fe0995cd725a581702b":{
      "scriptId":"u25"},
    "672ae18a1763402bbfe677569e8ed0e9":{
      "scriptId":"u26"},
    "68f9bc61b10c4953be3b277435e25200":{
      "scriptId":"u27"},
    "520806f5ff73426185b1d219c7e75479":{
      "scriptId":"u28"},
    "83d65e4ed58d421a8b8ce623a8a4801b":{
      "scriptId":"u29"},
    "2a14d302be0341b38433cc32fb2d5a0d":{
      "scriptId":"u30"},
    "7d4a11ed3c7e4dc1a46df42f80356689":{
      "scriptId":"u31"},
    "91b8408d4cca44958ec6cf32e80954c7":{
      "scriptId":"u32"},
    "38a33351643c4e22aa50446b5c9f4683":{
      "scriptId":"u33"},
    "0b2c232807f44e51925de323c6f1c244":{
      "scriptId":"u34"},
    "135ba3d6157c45bc9824a85177857252":{
      "scriptId":"u35"},
    "e500113f03bb4a09b1aa4fc3ee76971f":{
      "scriptId":"u36"},
    "e35b4eeb97514ad2b34e0ac438729442":{
      "scriptId":"u37"},
    "547488998ef14aa2bee029b42e3b5c30":{
      "scriptId":"u38"},
    "3f524932dfa240b0ac350165cd59113a":{
      "scriptId":"u39"},
    "538bcae53a5b4d6193a911f886d33c5b":{
      "scriptId":"u40"},
    "5fff86a22b4d444eacb7425ca0dff7e1":{
      "scriptId":"u41"},
    "789abe974210485b833a4410a07327da":{
      "scriptId":"u42"},
    "363f616bb371402080c7d938bf58122c":{
      "scriptId":"u43"},
    "43ffe42ca00f41d4a43414dfc76371e8":{
      "scriptId":"u44"},
    "bba60b3110994135ab4ad90a9c46ce76":{
      "scriptId":"u45"},
    "f64182252ef94a4486519d72cd85e604":{
      "scriptId":"u46"},
    "f432855c0d76499783fa996521826eaf":{
      "scriptId":"u47"},
    "62791e28086a4c0f868fc39a319563cf":{
      "scriptId":"u48"},
    "d014865998b6411d86a9841f3ffcd529":{
      "scriptId":"u49"},
    "fa490c27877748049d6e6c133e183246":{
      "scriptId":"u50"},
    "1dba8899fd234239967401687e94f645":{
      "scriptId":"u51"},
    "d409165edec5409084c4f917fb9f5229":{
      "scriptId":"u52"},
    "eae5d5e6dc534b71a08d8dd614dc5fd1":{
      "scriptId":"u53"},
    "5a92bd789991431d903e2819ce0faee7":{
      "scriptId":"u54"},
    "9b31b79aebf24174b7589ee6889d545f":{
      "scriptId":"u55"},
    "28a44c1a6f7a45e8a17d9790d7d05816":{
      "scriptId":"u56"},
    "08a43a56ef26493593f37dfacff95c7e":{
      "scriptId":"u57"},
    "aa88d88e2ada429aa3b348f4d318f0d3":{
      "scriptId":"u58"},
    "f575623f84644eacbc1d333f80a7fea3":{
      "scriptId":"u59"},
    "bfb0fa44a3184098b3e9a581d0f70915":{
      "scriptId":"u60"},
    "b6d4c51000b342809f0d3e88eb7818cd":{
      "scriptId":"u61"},
    "94e389d6119b4d46a509803e938aef0e":{
      "scriptId":"u62"},
    "def2e11020044fa0867b75eb4f100043":{
      "scriptId":"u63"},
    "d3d2b266dd3644168ec6b3fdcfd031a0":{
      "scriptId":"u64"},
    "56065124a9da435384c58fd97a9b802d":{
      "scriptId":"u65"},
    "018f8b6ecdcf4927a67dcc1f37310131":{
      "scriptId":"u66"},
    "0241233562644e1ba9710fce0fa63285":{
      "scriptId":"u67"},
    "994da042638a4d82af9458d8ab69e0b0":{
      "scriptId":"u68"},
    "4765e45a07c04d219b6a10719c7f73c3":{
      "scriptId":"u69"},
    "3dc6ae74e13f4a34b6bee43cf92d6503":{
      "scriptId":"u70"},
    "8fa8c25cc62c48fdb0e4a081d1a5c1c3":{
      "scriptId":"u71"},
    "be8bc7cfcf4848159a5af8e303d59963":{
      "scriptId":"u72"},
    "81dd8bc1c2cb4e9a9033325e3ab956b0":{
      "scriptId":"u73"},
    "5515378ebad04320b255af6a5718c077":{
      "scriptId":"u74"},
    "ac668f3980104f81a02d4c42b818878b":{
      "scriptId":"u75"},
    "46aa82e7b4e9442e912bce053dd8e316":{
      "scriptId":"u76"},
    "e9fa8d29440a4e55b1cf372c7433bedf":{
      "scriptId":"u77"},
    "9099927c6dee4da4840f0e77c2c71ba4":{
      "scriptId":"u78"},
    "16d2980e7d754fb39a51bbf7d7d78c6e":{
      "scriptId":"u79"},
    "f8334a95e6614904954da954313a2fcf":{
      "scriptId":"u80"},
    "db6ff82c181a4f4bb1c5ee1b80bcdfa9":{
      "scriptId":"u81"},
    "3ff8cb66628e49aab8ffbcc683e3b433":{
      "scriptId":"u82"},
    "3eebfa9e695444919fc21b838481a8eb":{
      "scriptId":"u83"},
    "622598167fb34c9486a9ae6a504df0cb":{
      "scriptId":"u84"},
    "93061b18fc6748df976d02d498acb2b4":{
      "scriptId":"u85"},
    "456b9b16e16a4ec583b54ba498e02a5a":{
      "scriptId":"u86"},
    "f1cd6f0373614c0fa3be27c1402d2de0":{
      "scriptId":"u87"},
    "ddf1a67722844c198a7aa3570aeafbfc":{
      "scriptId":"u88"},
    "7f61fc22aa894e068506d5a5bf55bc63":{
      "scriptId":"u89"},
    "7908174256d14c7ea9dd05114b3da4f4":{
      "scriptId":"u90"},
    "01dd6ad88db94e3ca84dcfbc124911a5":{
      "scriptId":"u91"},
    "0a4208e719cb47c7912acd1be497ba33":{
      "scriptId":"u92"},
    "5092ad8ae46849f299cd8888e9b5156c":{
      "scriptId":"u93"},
    "6124d203168c4a26b6eb3f20a41fd1d4":{
      "scriptId":"u94"}}});