$axure.loadCurrentPage({
  "url":"管理我的團隊.html",
  "generationDate":new Date(1404292444408.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"d495595da33b46db8319010fe3c42102",
    "type":"Axure:Page",
    "name":"管理我的團隊",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7a6a86628bd54a489d2abacac7fbee01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1902,
              "height":640},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea958dc2cbd4c5c90e8eaa43d5a810d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1902,
                  "height":640},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u0.png"}},
{
          "id":"ee95139325014c5dbf4bbb78365562a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1902,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0349906a8d94b38a7b566f65e1faf7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1902,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u2.png"}},
{
          "id":"1c5d971d1f654878b6c4dec1c36ff7e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":160},
            "size":{
              "width":1024,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84fc2bc897d74dafa287be49395b7f3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":160},
                "size":{
                  "width":1024,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u4.png"}},
{
          "id":"96ce0bb854214b0598271fc6b8b6a212",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98bf5daa69d4bc58cb0a25246c72cde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"047df51319a64aceb4b49217f6e54e1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d5e4fcafed1417e8c5cb3fe4fcbe30b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u8.png"}},
{
          "id":"911fde4ff5564540b12e224cf052c335",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd2328bafcd642bba72b3d959c5e7499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f50ea1286978420680770635b65c425a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b58ed9a87ec4a81b2e81a1b8299e13d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16459c3ebe894db99bf8582523e0bd05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF,
              "opacity":0},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5a01af21ba492da12d3500824b8b2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF,
                  "opacity":0},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f8ea964be74bd1958508de2e6af71b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4baeea360dfe431abb041c54f75523f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":190},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u16.png"}},
{
          "id":"c8e3f266c62249d9929f389a2a5271ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":615,
              "y":190},
            "size":{
              "width":41,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"738795398b1a4f97a5230111dce120d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":615,
                  "y":190},
                "size":{
                  "width":41,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u18.png"}},
{
          "id":"41e8793c2b884833ad94d7a77b4510c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":203},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db69b1af741b457aa301a3bb228bbc52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":203},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u20.png"}},
{
          "id":"31707be56f074c7fbe3fd9c116229b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":480,
              "y":260},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7b5bc6616de4211876974792890f7f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":260},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u22.png"}},
{
          "id":"11b29506e0c9446294a1608351fb4b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55cdc6c1a38d4d82a54afc76d8eab9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86949479451b42509cf23fb3c9ba5e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":380},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a94e3a4ec91149bc864b1773e7e33746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":380},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u26.png"}},
{
          "id":"b63f2a2f682e414f931d837ee5463891",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":260},
            "size":{
              "width":730,
              "height":380},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d687cb122b8484c809ecf56bc405a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":260},
                "size":{
                  "width":730,
                  "height":380},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u28.png"}},
{
          "id":"452f18fff6db4a85bfbc78ca743ace05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":283},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"404ea149bc51452a9ff29b51d7fc1eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":283},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u30.png"}},
{
          "id":"2bc3ef6f4c8b41cb9f71e3724985dbd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":286},
            "size":{
              "width":199,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70a61924a51c453eb948ca6a8fd297bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":286},
                "size":{
                  "width":199,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視遠距工作者工作詳情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視遠距工作者工作詳情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理我的團隊/u32.png"}},
{
          "id":"b97d5d05db92409583eb814d3247363b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1310,
              "y":298},
            "size":{
              "width":79,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9385b49d79af4437a6ce563211bc9f03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1310,
                  "y":298},
                "size":{
                  "width":79,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u34.png"}},
{
          "id":"7a64a10972da459f8863c8cfc303dc3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":310},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380f45d9da9f4badad7b05a6792dd3e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":310},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"9e8ae2978e2241378ec20e467808c11d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":381},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc4e5f1a0a549eeaa5a4abb624070c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":381},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u38.jpg"}},
{
          "id":"fa1b6567fa394e0abce47951ecb6544b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":369},
            "size":{
              "width":199,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134040f0717c4c32a77d0910ea5bbdee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":369},
                "size":{
                  "width":199,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視遠距工作者工作詳情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視遠距工作者工作詳情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理我的團隊/u32.png"}},
{
          "id":"e8353334fad8465c943846ed42424f29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1310,
              "y":381},
            "size":{
              "width":79,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ea46039b5434e0fa46c26c35fbfdfd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1310,
                  "y":381},
                "size":{
                  "width":79,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u34.png"}},
{
          "id":"b5ec60a8928b4e179f7bff410354135e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1356,
              "y":393},
            "size":{
              "width":13,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e523d867824501b34eb23c0337b84f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1356,
                  "y":393},
                "size":{
                  "width":13,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u44.png"}},
{
          "id":"02e697c82664451283cb912e2cadbf11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":465},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee17231bb7ad4232899da6cbec94858a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":465},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u46.jpg"}},
{
          "id":"d31b7e01149f4a998516101bfe60d0e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":453},
            "size":{
              "width":199,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67549a974e564245bdbcca94c964f5e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":453},
                "size":{
                  "width":199,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視遠距工作者工作詳情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視遠距工作者工作詳情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理我的團隊/u32.png"}},
{
          "id":"8cceb2e86ac243e883f8eb1e5ecb7fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1310,
              "y":465},
            "size":{
              "width":79,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"324caa91b580435cba7e0a461aae512b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1310,
                  "y":465},
                "size":{
                  "width":79,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u34.png"}},
{
          "id":"04b70d48598448aab3fcfccacfdb29cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":477},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa8b78bea7141cbbb7422b70e8790b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":477},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"c7cde2f152ba4972b2b109d38a270f2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":548},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b5312819194797a9a249889c9e72bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":548},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u54.jpg"}},
{
          "id":"98ffd1a3e7394bb99287b28d0588892a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":536},
            "size":{
              "width":199,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce9f0c50f4b457589431c16c4c3f0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":536},
                "size":{
                  "width":199,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視遠距工作者工作詳情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視遠距工作者工作詳情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理我的團隊/u32.png"}},
{
          "id":"47d63274b07345298060bf1b7186efa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1310,
              "y":548},
            "size":{
              "width":79,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4da071bd27459ebec0c229f1eba1f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1310,
                  "y":548},
                "size":{
                  "width":79,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u34.png"}},
{
          "id":"324f7a5aa0a448659750f48e4133eec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":560},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef73ff908e74abfbfc7cbd8eb9c3f2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":560},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"0ceb4b80c24143869f0e4206b37894c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4208d14ea548198fbb871171d443dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"2a9c64f280c345c0ab993cec61080bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":10},
            "size":{
              "width":138,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4876ebe1bc76439f84c8e2f570e4e789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":10},
                "size":{
                  "width":138,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"449c749925644e51b4b487006be5170b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1903,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"446e9a30a3e6499eb31fda2ee28f05e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1903,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u51.png"}},
{
          "id":"d9b3538672054bc38690618eeb54c34e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ad9e1e798048d9acc9f09d31bdadc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f84ff70efe7c48b6951af283c46aa7e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e19fee0bed497a85e4a0d343c96874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"196eaa74dde34609bcba9a79baab464d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b24e7775524726ae07205cd64b4bd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b2abae036e3444a9a331d9373137db4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5469dea13e46a48c90372d618038aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9ab5688b51c4ad69342123bbad13207",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":960,
              "y":288},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b8d9287fa2483589b7224ce12ae539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":960,
                  "y":288},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"7e6632e46aab4ffab9866493460f56c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":960,
              "y":371},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c813411648664085a9eef8bb081f977e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":960,
                  "y":371},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"d28582982a394915ae11aec9318eb778",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":960,
              "y":455},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69b6937e9f644beaf2341af4fdf91e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":960,
                  "y":455},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"dde3a350e8cc400ead8d11768aed0b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":960,
              "y":538},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd6d98826ce448568074dc8fb93242fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":960,
                  "y":538},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"6b13cbe61c0649399e199fdf874f67ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":288},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62abf556c59b42cdbc56392de3342eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":288},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"601977873d9b45c8bb22fa74d9368bad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":371},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c27f2af95e54711bda628c493ee0fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":371},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"74b6e6439bf94af496f3e3204acee236",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":1170,
              "y":455},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21fc926831244c2d85d9a33f09284f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":1170,
                  "y":455},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"3f2eacfc90c84f26b39b3e6222a64fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":1170,
              "y":538},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7a6b96e3304a49bd1a0ca250b58c12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":1170,
                  "y":538},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"0230fdead44e42a8a8c58728ccf27e8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":323},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b17b4174792a411fb122535916e496d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":323},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"10a65880f7704c8aab1e6e0272344d92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":583},
            "size":{
              "width":122,
              "height":233},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2977a773c141478a8b6aa61410fa2911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":583},
                "size":{
                  "width":122,
                  "height":233},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u94.png"}},
{
          "id":"b9b4f363abaa4e178f97b309645f951c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":416},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287b85b9ce1944d29549ffd5a3315024",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":416},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"7388c52fd99f4e48aae5e5c817e0da5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":499},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3072057e48b4d7f8db94545c584b91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":499},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"cdd56726e1f0416294a2a3cd6bcc7cb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":583},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cd388f113e642fea7042057fc513d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":583},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"d9cf6ff7dfa64b00a6d81d7b05932845",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":960,
              "y":462},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9085c2f6b4f347efb23d3fe8eca75b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":960,
                  "y":462},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"d0dff9c0a2d74f60b52164212d6c1735",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":462},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e7078d49aa4e6f94e38d78eeb46d6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":462},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"9a2a2eb176aa44d9b2936048da35d3b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":960,
              "y":546},
            "size":{
              "width":200,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8491382a379649babe94bff1b3c78355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":960,
                  "y":546},
                "size":{
                  "width":200,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u76.png"}},
{
          "id":"4989e2e5075041e691563cfb09c904b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":546},
            "size":{
              "width":130,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c8380775ff84d0d8e624340b335e850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":546},
                "size":{
                  "width":130,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u84.png"}},
{
          "id":"482fdf184c29478f82c5c32e8b52a027",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":754,
              "y":276},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a40ea1341a1493db75c55dad3ed0c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":754,
                  "y":276},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9733fd145726453e9e94362c243131d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":751,
              "y":374},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eac401687aa4d26b1d615b27968e35c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":751,
                  "y":374},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d04d516ae70b47fb88e6b81e02e9c63b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":751,
              "y":455},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77c8c26da3540529497bbf665292a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":751,
                  "y":455},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01ada05c03e148d8a510ce979cdd4a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":754,
              "y":538},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf0949a09c44a699fc416e5e9c237dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":754,
                  "y":538},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de8a1b57ae4e41e2ae0296c5d6006a04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10674d1b205645449b64444dee14e155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7a6a86628bd54a489d2abacac7fbee01":{
      "scriptId":"u0"},
    "fea958dc2cbd4c5c90e8eaa43d5a810d":{
      "scriptId":"u1"},
    "ee95139325014c5dbf4bbb78365562a0":{
      "scriptId":"u2"},
    "d0349906a8d94b38a7b566f65e1faf7e":{
      "scriptId":"u3"},
    "1c5d971d1f654878b6c4dec1c36ff7e1":{
      "scriptId":"u4"},
    "84fc2bc897d74dafa287be49395b7f3b":{
      "scriptId":"u5"},
    "96ce0bb854214b0598271fc6b8b6a212":{
      "scriptId":"u6"},
    "c98bf5daa69d4bc58cb0a25246c72cde":{
      "scriptId":"u7"},
    "047df51319a64aceb4b49217f6e54e1d":{
      "scriptId":"u8"},
    "4d5e4fcafed1417e8c5cb3fe4fcbe30b":{
      "scriptId":"u9"},
    "911fde4ff5564540b12e224cf052c335":{
      "scriptId":"u10"},
    "cd2328bafcd642bba72b3d959c5e7499":{
      "scriptId":"u11"},
    "f50ea1286978420680770635b65c425a":{
      "scriptId":"u12"},
    "4b58ed9a87ec4a81b2e81a1b8299e13d":{
      "scriptId":"u13"},
    "16459c3ebe894db99bf8582523e0bd05":{
      "scriptId":"u14"},
    "9f5a01af21ba492da12d3500824b8b2e":{
      "scriptId":"u15"},
    "38f8ea964be74bd1958508de2e6af71b":{
      "scriptId":"u16"},
    "4baeea360dfe431abb041c54f75523f5":{
      "scriptId":"u17"},
    "c8e3f266c62249d9929f389a2a5271ce":{
      "scriptId":"u18"},
    "738795398b1a4f97a5230111dce120d7":{
      "scriptId":"u19"},
    "41e8793c2b884833ad94d7a77b4510c1":{
      "scriptId":"u20"},
    "db69b1af741b457aa301a3bb228bbc52":{
      "scriptId":"u21"},
    "31707be56f074c7fbe3fd9c116229b5f":{
      "scriptId":"u22"},
    "b7b5bc6616de4211876974792890f7f0":{
      "scriptId":"u23"},
    "11b29506e0c9446294a1608351fb4b42":{
      "scriptId":"u24"},
    "55cdc6c1a38d4d82a54afc76d8eab9c2":{
      "scriptId":"u25"},
    "86949479451b42509cf23fb3c9ba5e80":{
      "scriptId":"u26"},
    "a94e3a4ec91149bc864b1773e7e33746":{
      "scriptId":"u27"},
    "b63f2a2f682e414f931d837ee5463891":{
      "scriptId":"u28"},
    "1d687cb122b8484c809ecf56bc405a52":{
      "scriptId":"u29"},
    "452f18fff6db4a85bfbc78ca743ace05":{
      "scriptId":"u30"},
    "404ea149bc51452a9ff29b51d7fc1eb2":{
      "scriptId":"u31"},
    "2bc3ef6f4c8b41cb9f71e3724985dbd4":{
      "scriptId":"u32"},
    "70a61924a51c453eb948ca6a8fd297bf":{
      "scriptId":"u33"},
    "b97d5d05db92409583eb814d3247363b":{
      "scriptId":"u34"},
    "9385b49d79af4437a6ce563211bc9f03":{
      "scriptId":"u35"},
    "7a64a10972da459f8863c8cfc303dc3c":{
      "scriptId":"u36"},
    "380f45d9da9f4badad7b05a6792dd3e0":{
      "scriptId":"u37"},
    "9e8ae2978e2241378ec20e467808c11d":{
      "scriptId":"u38"},
    "bdc4e5f1a0a549eeaa5a4abb624070c7":{
      "scriptId":"u39"},
    "fa1b6567fa394e0abce47951ecb6544b":{
      "scriptId":"u40"},
    "134040f0717c4c32a77d0910ea5bbdee":{
      "scriptId":"u41"},
    "e8353334fad8465c943846ed42424f29":{
      "scriptId":"u42"},
    "4ea46039b5434e0fa46c26c35fbfdfd5":{
      "scriptId":"u43"},
    "b5ec60a8928b4e179f7bff410354135e":{
      "scriptId":"u44"},
    "d9e523d867824501b34eb23c0337b84f":{
      "scriptId":"u45"},
    "02e697c82664451283cb912e2cadbf11":{
      "scriptId":"u46"},
    "ee17231bb7ad4232899da6cbec94858a":{
      "scriptId":"u47"},
    "d31b7e01149f4a998516101bfe60d0e9":{
      "scriptId":"u48"},
    "67549a974e564245bdbcca94c964f5e7":{
      "scriptId":"u49"},
    "8cceb2e86ac243e883f8eb1e5ecb7fdd":{
      "scriptId":"u50"},
    "324caa91b580435cba7e0a461aae512b":{
      "scriptId":"u51"},
    "04b70d48598448aab3fcfccacfdb29cf":{
      "scriptId":"u52"},
    "9fa8b78bea7141cbbb7422b70e8790b7":{
      "scriptId":"u53"},
    "c7cde2f152ba4972b2b109d38a270f2e":{
      "scriptId":"u54"},
    "12b5312819194797a9a249889c9e72bd":{
      "scriptId":"u55"},
    "98ffd1a3e7394bb99287b28d0588892a":{
      "scriptId":"u56"},
    "4ce9f0c50f4b457589431c16c4c3f0b5":{
      "scriptId":"u57"},
    "47d63274b07345298060bf1b7186efa5":{
      "scriptId":"u58"},
    "fc4da071bd27459ebec0c229f1eba1f6":{
      "scriptId":"u59"},
    "324f7a5aa0a448659750f48e4133eec7":{
      "scriptId":"u60"},
    "bef73ff908e74abfbfc7cbd8eb9c3f2b":{
      "scriptId":"u61"},
    "0ceb4b80c24143869f0e4206b37894c4":{
      "scriptId":"u62"},
    "6c4208d14ea548198fbb871171d443dd":{
      "scriptId":"u63"},
    "2a9c64f280c345c0ab993cec61080bb5":{
      "scriptId":"u64"},
    "4876ebe1bc76439f84c8e2f570e4e789":{
      "scriptId":"u65"},
    "449c749925644e51b4b487006be5170b":{
      "scriptId":"u66"},
    "446e9a30a3e6499eb31fda2ee28f05e3":{
      "scriptId":"u67"},
    "d9b3538672054bc38690618eeb54c34e":{
      "scriptId":"u68"},
    "56ad9e1e798048d9acc9f09d31bdadc6":{
      "scriptId":"u69"},
    "f84ff70efe7c48b6951af283c46aa7e7":{
      "scriptId":"u70"},
    "c2e19fee0bed497a85e4a0d343c96874":{
      "scriptId":"u71"},
    "196eaa74dde34609bcba9a79baab464d":{
      "scriptId":"u72"},
    "32b24e7775524726ae07205cd64b4bd3":{
      "scriptId":"u73"},
    "5b2abae036e3444a9a331d9373137db4":{
      "scriptId":"u74"},
    "bf5469dea13e46a48c90372d618038aa":{
      "scriptId":"u75"},
    "d9ab5688b51c4ad69342123bbad13207":{
      "scriptId":"u76"},
    "a2b8d9287fa2483589b7224ce12ae539":{
      "scriptId":"u77"},
    "7e6632e46aab4ffab9866493460f56c4":{
      "scriptId":"u78"},
    "c813411648664085a9eef8bb081f977e":{
      "scriptId":"u79"},
    "d28582982a394915ae11aec9318eb778":{
      "scriptId":"u80"},
    "c69b6937e9f644beaf2341af4fdf91e3":{
      "scriptId":"u81"},
    "dde3a350e8cc400ead8d11768aed0b73":{
      "scriptId":"u82"},
    "cd6d98826ce448568074dc8fb93242fd":{
      "scriptId":"u83"},
    "6b13cbe61c0649399e199fdf874f67ff":{
      "scriptId":"u84"},
    "62abf556c59b42cdbc56392de3342eb3":{
      "scriptId":"u85"},
    "601977873d9b45c8bb22fa74d9368bad":{
      "scriptId":"u86"},
    "7c27f2af95e54711bda628c493ee0fc8":{
      "scriptId":"u87"},
    "74b6e6439bf94af496f3e3204acee236":{
      "scriptId":"u88"},
    "21fc926831244c2d85d9a33f09284f78":{
      "scriptId":"u89"},
    "3f2eacfc90c84f26b39b3e6222a64fad":{
      "scriptId":"u90"},
    "ab7a6b96e3304a49bd1a0ca250b58c12":{
      "scriptId":"u91"},
    "0230fdead44e42a8a8c58728ccf27e8a":{
      "scriptId":"u92"},
    "b17b4174792a411fb122535916e496d1":{
      "scriptId":"u93"},
    "10a65880f7704c8aab1e6e0272344d92":{
      "scriptId":"u94"},
    "2977a773c141478a8b6aa61410fa2911":{
      "scriptId":"u95"},
    "b9b4f363abaa4e178f97b309645f951c":{
      "scriptId":"u96"},
    "287b85b9ce1944d29549ffd5a3315024":{
      "scriptId":"u97"},
    "7388c52fd99f4e48aae5e5c817e0da5a":{
      "scriptId":"u98"},
    "e3072057e48b4d7f8db94545c584b91a":{
      "scriptId":"u99"},
    "cdd56726e1f0416294a2a3cd6bcc7cb1":{
      "scriptId":"u100"},
    "7cd388f113e642fea7042057fc513d27":{
      "scriptId":"u101"},
    "d9cf6ff7dfa64b00a6d81d7b05932845":{
      "scriptId":"u102"},
    "9085c2f6b4f347efb23d3fe8eca75b91":{
      "scriptId":"u103"},
    "d0dff9c0a2d74f60b52164212d6c1735":{
      "scriptId":"u104"},
    "18e7078d49aa4e6f94e38d78eeb46d6c":{
      "scriptId":"u105"},
    "9a2a2eb176aa44d9b2936048da35d3b8":{
      "scriptId":"u106"},
    "8491382a379649babe94bff1b3c78355":{
      "scriptId":"u107"},
    "4989e2e5075041e691563cfb09c904b9":{
      "scriptId":"u108"},
    "7c8380775ff84d0d8e624340b335e850":{
      "scriptId":"u109"},
    "482fdf184c29478f82c5c32e8b52a027":{
      "scriptId":"u110"},
    "8a40ea1341a1493db75c55dad3ed0c1c":{
      "scriptId":"u111"},
    "9733fd145726453e9e94362c243131d5":{
      "scriptId":"u112"},
    "1eac401687aa4d26b1d615b27968e35c":{
      "scriptId":"u113"},
    "d04d516ae70b47fb88e6b81e02e9c63b":{
      "scriptId":"u114"},
    "d77c8c26da3540529497bbf665292a6e":{
      "scriptId":"u115"},
    "01ada05c03e148d8a510ce979cdd4a63":{
      "scriptId":"u116"},
    "adf0949a09c44a699fc416e5e9c237dd":{
      "scriptId":"u117"},
    "de8a1b57ae4e41e2ae0296c5d6006a04":{
      "scriptId":"u118"},
    "10674d1b205645449b64444dee14e155":{
      "scriptId":"u119"}}});