$axure.loadCurrentPage({
  "url":"申請退款.html",
  "generationDate":new Date(1404292438935.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"3eb89284ddee4249a27d5e58d935d529",
    "type":"Axure:Page",
    "name":"申請退款",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7581628596304375a93f838c64b3944b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08931a01ac2b4bf5b3e28bd090991593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"1a7995e7b8584f17aef36ce1b3638e9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bafc4f922fd4036aac0051b13d10560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":843},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"50fedbf56f3041a59bf62b4cc6c57228",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edcd11b37e574727a0f794cbea15bea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"a2845eae5bbe4b92914aa1c3c699c02c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":669},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b4ea61fddf947d5b3a3feccc4867f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":669},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"521d763a1fce4ab0953cf0bf1204cbd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":820},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2bc73cc81b44507ae39125669e83499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":820},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"1a18e47bc96542c4a0e990b5053facf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1631191a2af478f92190a5fff3addce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視正在執行中的合約 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視正在執行中的合約.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"187b2937ee574f208b94be501c5193ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":143},
            "size":{
              "width":956,
              "height":587},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da99f3c0b04433ba30d327b918615cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":143},
                "size":{
                  "width":956,
                  "height":587},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請退款/u12.png"}},
{
          "id":"94aacbc1bdf145479da7fe773f17aa8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":680,
              "y":688},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071b009c03624a5aa390aa1e9e7d1b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":680,
                  "y":688},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視正在執行中的合約 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視正在執行中的合約.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7581628596304375a93f838c64b3944b":{
      "scriptId":"u0"},
    "08931a01ac2b4bf5b3e28bd090991593":{
      "scriptId":"u1"},
    "1a7995e7b8584f17aef36ce1b3638e9c":{
      "scriptId":"u2"},
    "4bafc4f922fd4036aac0051b13d10560":{
      "scriptId":"u3"},
    "50fedbf56f3041a59bf62b4cc6c57228":{
      "scriptId":"u4"},
    "edcd11b37e574727a0f794cbea15bea3":{
      "scriptId":"u5"},
    "a2845eae5bbe4b92914aa1c3c699c02c":{
      "scriptId":"u6"},
    "1b4ea61fddf947d5b3a3feccc4867f7d":{
      "scriptId":"u7"},
    "521d763a1fce4ab0953cf0bf1204cbd2":{
      "scriptId":"u8"},
    "c2bc73cc81b44507ae39125669e83499":{
      "scriptId":"u9"},
    "1a18e47bc96542c4a0e990b5053facf6":{
      "scriptId":"u10"},
    "c1631191a2af478f92190a5fff3addce":{
      "scriptId":"u11"},
    "187b2937ee574f208b94be501c5193ea":{
      "scriptId":"u12"},
    "4da99f3c0b04433ba30d327b918615cf":{
      "scriptId":"u13"},
    "94aacbc1bdf145479da7fe773f17aa8e":{
      "scriptId":"u14"},
    "071b009c03624a5aa390aa1e9e7d1b23":{
      "scriptId":"u15"}}});