$axure.loadCurrentPage({
  "url":"個人雇主註冊流程.html",
  "generationDate":new Date(1404292430598.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"946317f0f9c248f4a222ea564967ce0b",
    "type":"Axure:Page",
    "name":"個人雇主註冊流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
          "label":"個人雇主登入流程",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5825d769153448aca8866d059e64cf29",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"978d9953a0364d8c94d7a8fbcab8fc0b",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1258}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a29e211b0da4a56b03ffc79252ba0b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1258}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/個人雇主註冊流程/u1.png"}},
{
                  "id":"1fa6801804f34c26b9ec8ed3adf58c10",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1300,
                      "y":980},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0076d2b499643d3933519ff615d52ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1300,
                          "y":980},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 個人雇主登入流程 to State2",
                              "panelsToStates":[{
                                  "panelPath":["95046fbc7e8f41ceba3c5d2b6ae82b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"33fa2c7d19aa4965b50fedfebb3db3cf",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6d550b1474bf4029acc079fad79e54a9",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fc485dcfbfd446787359302032c4bc1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":979}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/個人雇主註冊流程/u5.png"}},
{
                  "id":"ddbd09df86de40029f2809c32d92b021",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":470,
                      "y":700},
                    "size":{
                      "width":140,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3865b654ec2c4af78cf9e9baff5b6e2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":470,
                          "y":700},
                        "size":{
                          "width":140,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 個人雇主登入流程 to State1",
                              "panelsToStates":[{
                                  "panelPath":["95046fbc7e8f41ceba3c5d2b6ae82b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e43dd0575c9046a693a4b049b340e35e",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1290,
                      "y":700},
                    "size":{
                      "width":140,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"836a1b2525ef4bd6b64dbd4d083d27aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1290,
                          "y":700},
                        "size":{
                          "width":140,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 個人雇主登入流程 to State3",
                              "panelsToStates":[{
                                  "panelPath":["95046fbc7e8f41ceba3c5d2b6ae82b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0d9fee987581417cbb300fd6faf9c077",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"96e85088f0f5496b8239ea8c84c68715",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1520}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d80c940935ee40069e8f0a3e8078e4f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1520}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/個人雇主註冊流程/u11.png"}},
{
                  "id":"b82f7b7c4bb6480ca72a7051e0c897c9",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":470,
                      "y":1240},
                    "size":{
                      "width":150,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73a1abc8afc74a1faadf31cdc6d9a556",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":470,
                          "y":1240},
                        "size":{
                          "width":150,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 個人雇主登入流程 to State2",
                              "panelsToStates":[{
                                  "panelPath":["95046fbc7e8f41ceba3c5d2b6ae82b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"07363119cd6c4c3d802a6881912a7962",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1290,
                      "y":1240},
                    "size":{
                      "width":150,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5ebfcacf46f4fa0b9014392964bd64f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1290,
                          "y":1240},
                        "size":{
                          "width":150,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 個人雇主登入流程 to State4",
                              "panelsToStates":[{
                                  "panelPath":["95046fbc7e8f41ceba3c5d2b6ae82b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"777d773709654df0b83b671b0b7e52a8",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4c7f525442346c98f7bd7f39ea332aa",
                  "label":"",
                  "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1250}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01e969d790ff47c6a9f9601a790b3689",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"95046fbc7e8f41ceba3c5d2b6ae82b9f",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1250}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/個人雇主註冊流程/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "95046fbc7e8f41ceba3c5d2b6ae82b9f":{
      "scriptId":"u0"},
    "978d9953a0364d8c94d7a8fbcab8fc0b":{
      "scriptId":"u1"},
    "4a29e211b0da4a56b03ffc79252ba0b5":{
      "scriptId":"u2"},
    "1fa6801804f34c26b9ec8ed3adf58c10":{
      "scriptId":"u3"},
    "e0076d2b499643d3933519ff615d52ce":{
      "scriptId":"u4"},
    "6d550b1474bf4029acc079fad79e54a9":{
      "scriptId":"u5"},
    "6fc485dcfbfd446787359302032c4bc1":{
      "scriptId":"u6"},
    "ddbd09df86de40029f2809c32d92b021":{
      "scriptId":"u7"},
    "3865b654ec2c4af78cf9e9baff5b6e2b":{
      "scriptId":"u8"},
    "e43dd0575c9046a693a4b049b340e35e":{
      "scriptId":"u9"},
    "836a1b2525ef4bd6b64dbd4d083d27aa":{
      "scriptId":"u10"},
    "96e85088f0f5496b8239ea8c84c68715":{
      "scriptId":"u11"},
    "d80c940935ee40069e8f0a3e8078e4f9":{
      "scriptId":"u12"},
    "b82f7b7c4bb6480ca72a7051e0c897c9":{
      "scriptId":"u13"},
    "73a1abc8afc74a1faadf31cdc6d9a556":{
      "scriptId":"u14"},
    "07363119cd6c4c3d802a6881912a7962":{
      "scriptId":"u15"},
    "e5ebfcacf46f4fa0b9014392964bd64f":{
      "scriptId":"u16"},
    "d4c7f525442346c98f7bd7f39ea332aa":{
      "scriptId":"u17"},
    "01e969d790ff47c6a9f9601a790b3689":{
      "scriptId":"u18"}}});