$axure.loadCurrentPage({
  "url":"終止合約.html",
  "generationDate":new Date(1404292438969.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"a64bf83308d24a00977acfe37653391e",
    "type":"Axure:Page",
    "name":"終止合約",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb5e9c83bbc4402fb93d0359c9ff0256",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a48d3168a64b7c872001b99dbfdd30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"1ddfa3b3886c4a18a38d800cd7434b22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1241},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eca22174dd14bfe82e993db23513c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1241},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"ed0d509d28ce4e58bbdce5a89427554a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c81642de55c4e3cafe79e38c63b2000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"ed7ed8c412a4432a9d190d4cf57b8ba7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":1046},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8063dd6001e4454d8a611828ca4c48a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":1046},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"8e8ba39d2078479e8bdc4ed611fadbe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1197},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d78a6312bab40ddad12fea83af31dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1197},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"0cf90fd7c1e14a859b746736be3ba515",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a12b284ea2434ce882aa6d1d7674c407",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視正在執行中的合約 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視正在執行中的合約.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"353e42e06541461e9d98feb7437157f1",
          "label":"end contain",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":151},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7c4c73e04f8b4a0086126c1d5cfba31d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"258713e924de4ef4a454c9c8015cad3e",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":965,
                      "height":418},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"336bf432394e4e42bea43ca84e6c1546",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":965,
                          "height":418},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/終止合約/u13.png"}},
{
                  "id":"53a349aa39494284b6617e175c64b08e",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":902},
                    "size":{
                      "width":965,
                      "height":98},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"563a05c5a5bb4331828a3e43144d3011",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":902},
                        "size":{
                          "width":965,
                          "height":98},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/終止合約/u15.png"}},
{
                  "id":"8c6ee727d92b461b885a59ea58d70f4c",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":964},
                    "size":{
                      "width":120,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ddb3dbe661a4aa88616fa9720476b25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":964},
                        "size":{
                          "width":120,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set end contain to State2",
                              "panelsToStates":[{
                                  "panelPath":["353e42e06541461e9d98feb7437157f1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4479055c983f489aaa5f2e640f446233",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":120,
                      "y":964},
                    "size":{
                      "width":50,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"062d21e7d222481f9eaedde8f362df26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":120,
                          "y":964},
                        "size":{
                          "width":50,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 檢視正在執行中的合約 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"檢視正在執行中的合約.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3802a9f1fd4e46048b8950870591dee6",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":418},
                    "size":{
                      "width":966,
                      "height":467},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"724a1d9ecdc142a58d189baaa52dd05b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":418},
                        "size":{
                          "width":966,
                          "height":467},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/終止合約/u21.png"}},
{
                  "id":"8434d633533a43fbb771b54107d4ae81",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "location":{
                      "x":200,
                      "y":434},
                    "size":{
                      "width":200,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9d7233c29c04cecbcf4aeb177b26019",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7},
                        "location":{
                          "x":200,
                          "y":434},
                        "size":{
                          "width":200,
                          "height":25},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/終止合約/u23.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0e0246c6ae2846a19a6613261967c035",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"adbca88779c741858e0479d66a07a125",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":963,
                      "height":103},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cf6b2e8031e4c1da76aa5c861536954",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":963,
                          "height":103},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/終止合約/u25.png"}},
{
                  "id":"b0f2624e3b4c449d926f4a33211065b7",
                  "label":"",
                  "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":60,
                      "y":52},
                    "size":{
                      "width":80,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06b74fbadb204882ae16fba71d365669",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"353e42e06541461e9d98feb7437157f1",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":60,
                          "y":52},
                        "size":{
                          "width":80,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 我的案件 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"我的案件.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "fb5e9c83bbc4402fb93d0359c9ff0256":{
      "scriptId":"u0"},
    "b5a48d3168a64b7c872001b99dbfdd30":{
      "scriptId":"u1"},
    "1ddfa3b3886c4a18a38d800cd7434b22":{
      "scriptId":"u2"},
    "9eca22174dd14bfe82e993db23513c91":{
      "scriptId":"u3"},
    "ed0d509d28ce4e58bbdce5a89427554a":{
      "scriptId":"u4"},
    "7c81642de55c4e3cafe79e38c63b2000":{
      "scriptId":"u5"},
    "ed7ed8c412a4432a9d190d4cf57b8ba7":{
      "scriptId":"u6"},
    "8063dd6001e4454d8a611828ca4c48a3":{
      "scriptId":"u7"},
    "8e8ba39d2078479e8bdc4ed611fadbe8":{
      "scriptId":"u8"},
    "0d78a6312bab40ddad12fea83af31dc0":{
      "scriptId":"u9"},
    "0cf90fd7c1e14a859b746736be3ba515":{
      "scriptId":"u10"},
    "a12b284ea2434ce882aa6d1d7674c407":{
      "scriptId":"u11"},
    "353e42e06541461e9d98feb7437157f1":{
      "scriptId":"u12"},
    "258713e924de4ef4a454c9c8015cad3e":{
      "scriptId":"u13"},
    "336bf432394e4e42bea43ca84e6c1546":{
      "scriptId":"u14"},
    "53a349aa39494284b6617e175c64b08e":{
      "scriptId":"u15"},
    "563a05c5a5bb4331828a3e43144d3011":{
      "scriptId":"u16"},
    "8c6ee727d92b461b885a59ea58d70f4c":{
      "scriptId":"u17"},
    "7ddb3dbe661a4aa88616fa9720476b25":{
      "scriptId":"u18"},
    "4479055c983f489aaa5f2e640f446233":{
      "scriptId":"u19"},
    "062d21e7d222481f9eaedde8f362df26":{
      "scriptId":"u20"},
    "3802a9f1fd4e46048b8950870591dee6":{
      "scriptId":"u21"},
    "724a1d9ecdc142a58d189baaa52dd05b":{
      "scriptId":"u22"},
    "8434d633533a43fbb771b54107d4ae81":{
      "scriptId":"u23"},
    "d9d7233c29c04cecbcf4aeb177b26019":{
      "scriptId":"u24"},
    "adbca88779c741858e0479d66a07a125":{
      "scriptId":"u25"},
    "7cf6b2e8031e4c1da76aa5c861536954":{
      "scriptId":"u26"},
    "b0f2624e3b4c449d926f4a33211065b7":{
      "scriptId":"u27"},
    "06b74fbadb204882ae16fba71d365669":{
      "scriptId":"u28"}}});