$axure.loadCurrentPage({
  "url":"案件詳細資料.html",
  "generationDate":new Date(1404292434827.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"66e8ffe86a184e8bbbf8c9d533118222",
    "type":"Axure:Page",
    "name":"案件詳細資料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23c6eb3579574220a5003fa5f69aa3be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3bb96f21c8f4b2e901e6cb8d9f0c5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u0.png"}},
{
          "id":"18746fc2b1e74c26a6c6c8a3d4e483b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":470,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9862a6ce60884a31a4d198349221034b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":470,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 案件詳細資料 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"案件詳細資料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73e125dc970f42fe8145c1d74874d963",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":680,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efdd2780be0c46ecafafcc637a777319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":680,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 投標者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"投標者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"669729cdbea64d79a3efcdbe38a1f24c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":900,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef05157ef3e745f78a513911fd6ad83b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":900,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主評價 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主評價.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"899908f88bbe439f85262912b6d4d5fe",
          "label":"save",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":231},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["899908f88bbe439f85262912b6d4d5fe"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3c71c559368142ed9da687ecf1dd2c68",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"230da6d87f5d4ce3b8fd2f4cced2292c",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"899908f88bbe439f85262912b6d4d5fe",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2af27c59f04647039937340276c7ed89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"899908f88bbe439f85262912b6d4d5fe",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0304956021b14f1ba382d25f2473cffe",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f3be0221e767432a972b200004225cf5",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"899908f88bbe439f85262912b6d4d5fe",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"462a9f0b1a2d45bd923b489828f81761",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"899908f88bbe439f85262912b6d4d5fe",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"eb54bacfe504425e94e8ef9250544fff",
          "label":"apply",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":229},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["eb54bacfe504425e94e8ef9250544fff"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"62110022a4b144f4bc122db13a548471",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"447b80e1887b40779ab27bc1745e752e",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"eb54bacfe504425e94e8ef9250544fff",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5af2f37917624e86bf459b946b7eec1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eb54bacfe504425e94e8ef9250544fff",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2eab5277bc0445ed975dc0a845f89dda",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"becfa4a9616f4b3f847ea6878577dcab",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"eb54bacfe504425e94e8ef9250544fff",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"359edb9c0af84c41a0bb7446a7ebe18d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eb54bacfe504425e94e8ef9250544fff",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"52324204a9744b23850708b7af9d6b72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1135,
              "y":160},
            "size":{
              "width":285,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef56232eea9445e98db182dfa7dce2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1135,
                  "y":160},
                "size":{
                  "width":285,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u18.png"}},
{
          "id":"7e021919a0f94880bc71824dc7f42574",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1380,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7340ae42df234fa19d1880bb5db08f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1380,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u20.png"}},
{
          "id":"2e2ae998794d4623ad718ecb72db1c60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1380,
              "y":0},
            "size":{
              "width":51,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a20e246cd2d47dbb71855873aed9417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1380,
                  "y":0},
                "size":{
                  "width":51,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u22.png"}},
{
          "id":"610acdc0dbd24342a292b84eef6d9a6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1431,
              "y":0},
            "size":{
              "width":489,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae466444762641138a45f0a53c900f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1431,
                  "y":0},
                "size":{
                  "width":489,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u24.png"}},
{
          "id":"98f7c60b8ddd4797aafa155790d3de91",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":26}},
          "adaptiveStyles":{
},
          "masterId":"96e31ac88e3944cf843d8f845f224998"},
{
          "id":"7179938ef5844860b4b533a6ec3fd61b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1680,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d1a1dfa27ac24ff2a583a261fc97d904"},
{
          "id":"acab0fe8eb3d4c60bd283a73cb1ceec5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1524,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d94c7ba1eaa34714a5d6253dffbe242f"},
{
          "id":"7fbc34c8705040a09a0eda67724c8b0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":760},
            "size":{
              "width":290,
              "height":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a1a3542cce642fcac7721a22165f498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":760},
                "size":{
                  "width":290,
                  "height":190},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u71.png"}}]}},
  "masters":{
    "96e31ac88e3944cf843d8f845f224998":{
      "packageId":"96e31ac88e3944cf843d8f845f224998",
      "type":"Axure:Master",
      "name":"dropdown",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"506f205c4d3f45b4a8d8879d40c585c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":117,
                "y":0},
              "size":{
                "width":170,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9b048d4c0424257a86f9053565fae84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":117,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44d2cae74264fe28efc5a9f011db65c",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":63},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"0ac610d031604d3e8252ebd82275eec3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b2490259cfb24a27937c8cc947bca228",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":102},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"17d97940863d453493d1773f25937fa8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":102},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 個人設定 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"個人設定.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"73dd3af138be44458bd25a2634764d55",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afb506fe892a47528ea57c3d3074e449",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"1a6249c0920944ceb89ae7e1be69ce09",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":141},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e45023e673d24bcda3e25c34b974ecef",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":141},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open TeleWork首頁 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"telework__.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7e4f70b8597e4e87b9a74652345d9ede",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":24},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7c6bb4ed82e4d73b9ed1dc1cf37732b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":24},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 遠距工作者登入後(找案件) in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"遠距工作者登入後_找案件_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db4e0239fc24aa5838f7a781f489e0f",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"18px",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099CC,
                        "opacity":1},
                      "location":{
                        "x":70,
                        "y":75},
                      "size":{
                        "width":170,
                        "height":36},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"26d3c97b49b9491e915ab197141698fb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"18px",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099CC,
                            "opacity":1},
                          "location":{
                            "x":70,
                            "y":75},
                          "size":{
                            "width":170,
                            "height":36},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u135.png"}},
{
                    "id":"5a69b865ebd6452ebabd85af7eedb35b",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":74},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c28622cbcfd4bc198d16cf0651c1dac",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":74},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 雇主登入後 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"雇主登入後.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"61887cf395474173a1dd468a457de938",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":-40,
                "y":50},
              "size":{
                "width":900,
                "height":460},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0571e4ff7de34900acd1a730a6b1eb2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":-40,
                    "y":50},
                  "size":{
                    "width":900,
                    "height":460},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73af37ef2bc548cfb218313275d91d54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":90},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9dc390a6c3e4fe89c75bd55943e8173",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":90},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 遠距工作者登入後(找案件) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"遠距工作者登入後_找案件_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c34866e4049b438ea46fb17ab8c63e6b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":140},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d929f16ffcd4e71bd2f5ca13b0d445f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":140},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 雇主登入後 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"雇主登入後.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d1a1dfa27ac24ff2a583a261fc97d904":{
      "packageId":"d1a1dfa27ac24ff2a583a261fc97d904",
      "type":"Axure:Master",
      "name":"change currency",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9769e695b0664441b3ccd5fbff65efea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":44,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0513e769e9d247dcad8d4b622b25b6ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":0},
                  "size":{
                    "width":44,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["7fc383c5928e49879a99dc4d9df850ae"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/遠距工作者詳細資料/u146.png"}},
{
            "id":"7fc383c5928e49879a99dc4d9df850ae",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":66},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"e234e68ced72465cb1fa9db278729a4e",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"dde9df61cfeb4ad0b61066271a6d78ad",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc21472bed343a3aef07d5ca3ec1639",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"b71ae81389e54486818e6630092762e8",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":30},
                      "size":{
                        "width":287,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c95221fca89e45be83003b35dbef975d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":287,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u151.png"}},
{
                    "id":"e8b8f022d802460e81c3242754b4631b",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":24},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"57944770132240ff89cbea05872a77de",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":24},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cb28593ac22e4ff982b158f27a2b81af",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":58},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"68c1f570ff814e418efd898b1f5a29aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":58},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9eae22708664bd780e699248735f154",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":92},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7d5f6bf4eb94b728c3cd1c2ca7b230d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":92},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c0e451649a8443e6b1d18c009d17b970",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":126},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"604e76edfd1f4bc19d41c745717c608b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":126},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3f060a28aabf42f0bc66baa1730d2dd1",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":160},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"95856e8d4e144148beb2044bf7442380",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":160},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "d94c7ba1eaa34714a5d6253dffbe242f":{
      "packageId":"d94c7ba1eaa34714a5d6253dffbe242f",
      "type":"Axure:Master",
      "name":"newinfo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"288ab1dc513d4d93aa14fe7c5f12cb0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":276,
                "y":0},
              "size":{
                "width":60,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11c910fab7bd4dd2afd5b9891a0bd868",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":276,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle info",
                        "objectsToFades":[{
                            "objectPath":["086570bf076446d99e2f75e95782f03d"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"086570bf076446d99e2f75e95782f03d",
            "label":"info",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":73},
              "size":{
                "width":345,
                "height":142},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3f0f17c212483eac523909f62362b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":false,
                "style":{
                  "location":{
                    "x":0,
                    "y":73},
                  "size":{
                    "width":345,
                    "height":142},
                  "visible":false},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/遠距工作者詳細資料/info_u166.png"}}]}}},
  "objectPaths":{
    "23c6eb3579574220a5003fa5f69aa3be":{
      "scriptId":"u0"},
    "f3bb96f21c8f4b2e901e6cb8d9f0c5bf":{
      "scriptId":"u1"},
    "18746fc2b1e74c26a6c6c8a3d4e483b9":{
      "scriptId":"u2"},
    "9862a6ce60884a31a4d198349221034b":{
      "scriptId":"u3"},
    "73e125dc970f42fe8145c1d74874d963":{
      "scriptId":"u4"},
    "efdd2780be0c46ecafafcc637a777319":{
      "scriptId":"u5"},
    "669729cdbea64d79a3efcdbe38a1f24c":{
      "scriptId":"u6"},
    "ef05157ef3e745f78a513911fd6ad83b":{
      "scriptId":"u7"},
    "899908f88bbe439f85262912b6d4d5fe":{
      "scriptId":"u8"},
    "230da6d87f5d4ce3b8fd2f4cced2292c":{
      "scriptId":"u9"},
    "2af27c59f04647039937340276c7ed89":{
      "scriptId":"u10"},
    "f3be0221e767432a972b200004225cf5":{
      "scriptId":"u11"},
    "462a9f0b1a2d45bd923b489828f81761":{
      "scriptId":"u12"},
    "eb54bacfe504425e94e8ef9250544fff":{
      "scriptId":"u13"},
    "447b80e1887b40779ab27bc1745e752e":{
      "scriptId":"u14"},
    "5af2f37917624e86bf459b946b7eec1f":{
      "scriptId":"u15"},
    "becfa4a9616f4b3f847ea6878577dcab":{
      "scriptId":"u16"},
    "359edb9c0af84c41a0bb7446a7ebe18d":{
      "scriptId":"u17"},
    "52324204a9744b23850708b7af9d6b72":{
      "scriptId":"u18"},
    "8ef56232eea9445e98db182dfa7dce2f":{
      "scriptId":"u19"},
    "7e021919a0f94880bc71824dc7f42574":{
      "scriptId":"u20"},
    "7340ae42df234fa19d1880bb5db08f66":{
      "scriptId":"u21"},
    "2e2ae998794d4623ad718ecb72db1c60":{
      "scriptId":"u22"},
    "3a20e246cd2d47dbb71855873aed9417":{
      "scriptId":"u23"},
    "610acdc0dbd24342a292b84eef6d9a6e":{
      "scriptId":"u24"},
    "ae466444762641138a45f0a53c900f62":{
      "scriptId":"u25"},
    "98f7c60b8ddd4797aafa155790d3de91":{
      "scriptId":"u26",
      "506f205c4d3f45b4a8d8879d40c585c1":{
        "scriptId":"u27"},
      "e9b048d4c0424257a86f9053565fae84":{
        "scriptId":"u28"},
      "f44d2cae74264fe28efc5a9f011db65c":{
        "scriptId":"u29"},
      "b2490259cfb24a27937c8cc947bca228":{
        "scriptId":"u30"},
      "17d97940863d453493d1773f25937fa8":{
        "scriptId":"u31"},
      "73dd3af138be44458bd25a2634764d55":{
        "scriptId":"u32"},
      "afb506fe892a47528ea57c3d3074e449":{
        "scriptId":"u33"},
      "1a6249c0920944ceb89ae7e1be69ce09":{
        "scriptId":"u34"},
      "e45023e673d24bcda3e25c34b974ecef":{
        "scriptId":"u35"},
      "7e4f70b8597e4e87b9a74652345d9ede":{
        "scriptId":"u36"},
      "e7c6bb4ed82e4d73b9ed1dc1cf37732b":{
        "scriptId":"u37"},
      "1db4e0239fc24aa5838f7a781f489e0f":{
        "scriptId":"u38"},
      "26d3c97b49b9491e915ab197141698fb":{
        "scriptId":"u39"},
      "5a69b865ebd6452ebabd85af7eedb35b":{
        "scriptId":"u40"},
      "1c28622cbcfd4bc198d16cf0651c1dac":{
        "scriptId":"u41"},
      "61887cf395474173a1dd468a457de938":{
        "scriptId":"u42"},
      "0571e4ff7de34900acd1a730a6b1eb2e":{
        "scriptId":"u43"},
      "73af37ef2bc548cfb218313275d91d54":{
        "scriptId":"u44"},
      "f9dc390a6c3e4fe89c75bd55943e8173":{
        "scriptId":"u45"},
      "c34866e4049b438ea46fb17ab8c63e6b":{
        "scriptId":"u46"},
      "3d929f16ffcd4e71bd2f5ca13b0d445f":{
        "scriptId":"u47"}},
    "7179938ef5844860b4b533a6ec3fd61b":{
      "scriptId":"u48",
      "9769e695b0664441b3ccd5fbff65efea":{
        "scriptId":"u49"},
      "0513e769e9d247dcad8d4b622b25b6ae":{
        "scriptId":"u50"},
      "7fc383c5928e49879a99dc4d9df850ae":{
        "scriptId":"u51"},
      "dde9df61cfeb4ad0b61066271a6d78ad":{
        "scriptId":"u52"},
      "8dc21472bed343a3aef07d5ca3ec1639":{
        "scriptId":"u53"},
      "b71ae81389e54486818e6630092762e8":{
        "scriptId":"u54"},
      "c95221fca89e45be83003b35dbef975d":{
        "scriptId":"u55"},
      "e8b8f022d802460e81c3242754b4631b":{
        "scriptId":"u56"},
      "57944770132240ff89cbea05872a77de":{
        "scriptId":"u57"},
      "cb28593ac22e4ff982b158f27a2b81af":{
        "scriptId":"u58"},
      "68c1f570ff814e418efd898b1f5a29aa":{
        "scriptId":"u59"},
      "f9eae22708664bd780e699248735f154":{
        "scriptId":"u60"},
      "d7d5f6bf4eb94b728c3cd1c2ca7b230d":{
        "scriptId":"u61"},
      "c0e451649a8443e6b1d18c009d17b970":{
        "scriptId":"u62"},
      "604e76edfd1f4bc19d41c745717c608b":{
        "scriptId":"u63"},
      "3f060a28aabf42f0bc66baa1730d2dd1":{
        "scriptId":"u64"},
      "95856e8d4e144148beb2044bf7442380":{
        "scriptId":"u65"}},
    "acab0fe8eb3d4c60bd283a73cb1ceec5":{
      "scriptId":"u66",
      "288ab1dc513d4d93aa14fe7c5f12cb0e":{
        "scriptId":"u67"},
      "11c910fab7bd4dd2afd5b9891a0bd868":{
        "scriptId":"u68"},
      "086570bf076446d99e2f75e95782f03d":{
        "scriptId":"u69"},
      "7f3f0f17c212483eac523909f62362b1":{
        "scriptId":"u70"}},
    "7fbc34c8705040a09a0eda67724c8b0d":{
      "scriptId":"u71"},
    "0a1a3542cce642fcac7721a22165f498":{
      "scriptId":"u72"}}});