$axure.loadCurrentPage({
  "url":"評價雇主.html",
  "generationDate":new Date(1404292441599.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"864dc9d3897d48539467f828b1a49858",
    "type":"Axure:Page",
    "name":"評價雇主",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d1d605fa3c241859d9b1465465f6cd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8d0003798f4413d93f988572bf8bfc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"ad7b045db1ae4597aaa24e08a46818f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1101},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5557fed1b26141569a49e060f8879188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1101},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"7e89e23a32a043b5a5b04c52e54f6ecb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c55bc4f06b349069c1d3fabfe8477b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"87d2cc4cf2c947a8958be5d5a6f7b231",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":919},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"188c7195235d4c9ba4c6db809bf27355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":919},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"136fbef0672f492d8585f45efcd800aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1065},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"728b18646b9441989c1319f909443054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1065},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"b823c1e007cb4a1793f7137cf4e86638",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2dbc81f6aa483394cf65fba7fda75f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7823d129f9b4e2abecbbddcf9f5e619",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":151},
            "size":{
              "width":965,
              "height":892}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239ef8693c944ae6931f06d1fa04bc4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":151},
                "size":{
                  "width":965,
                  "height":892}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/評價雇主/u12.png"}},
{
          "id":"d51811804f0146aebec5068d175b8931",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":485,
              "y":1001},
            "size":{
              "width":145,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ac3fee967242a2bc870b23c747ca89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":485,
                  "y":1001},
                "size":{
                  "width":145,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83fb895d9a6f4e12abf2c59d0f8a4c5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":640,
              "y":1010},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33f2611bad134a89b5cbdbc59b265844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":640,
                  "y":1010},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d1d605fa3c241859d9b1465465f6cd7":{
      "scriptId":"u0"},
    "d8d0003798f4413d93f988572bf8bfc1":{
      "scriptId":"u1"},
    "ad7b045db1ae4597aaa24e08a46818f5":{
      "scriptId":"u2"},
    "5557fed1b26141569a49e060f8879188":{
      "scriptId":"u3"},
    "7e89e23a32a043b5a5b04c52e54f6ecb":{
      "scriptId":"u4"},
    "4c55bc4f06b349069c1d3fabfe8477b0":{
      "scriptId":"u5"},
    "87d2cc4cf2c947a8958be5d5a6f7b231":{
      "scriptId":"u6"},
    "188c7195235d4c9ba4c6db809bf27355":{
      "scriptId":"u7"},
    "136fbef0672f492d8585f45efcd800aa":{
      "scriptId":"u8"},
    "728b18646b9441989c1319f909443054":{
      "scriptId":"u9"},
    "b823c1e007cb4a1793f7137cf4e86638":{
      "scriptId":"u10"},
    "3b2dbc81f6aa483394cf65fba7fda75f":{
      "scriptId":"u11"},
    "e7823d129f9b4e2abecbbddcf9f5e619":{
      "scriptId":"u12"},
    "239ef8693c944ae6931f06d1fa04bc4b":{
      "scriptId":"u13"},
    "d51811804f0146aebec5068d175b8931":{
      "scriptId":"u14"},
    "00ac3fee967242a2bc870b23c747ca89":{
      "scriptId":"u15"},
    "83fb895d9a6f4e12abf2c59d0f8a4c5e":{
      "scriptId":"u16"},
    "33f2611bad134a89b5cbdbc59b265844":{
      "scriptId":"u17"}}});