$axure.loadCurrentPage({
  "url":"遠距工作者註冊流程.html",
  "generationDate":new Date(1404292430373.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"33f36dd5cbc0448bbcaab6681f4294a7",
    "type":"Axure:Page",
    "name":"遠距工作者註冊流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"067173a992dd41b2aaa31ca8bd86305f",
          "label":"Freelancer註冊流程",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"af7de5434a234eecaaace79c703a173e",
              "label":"State0",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b58a29cbeea4ab39ca6aab6bd660f79",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1154}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1c643ff3f104c4e94e91e6897170d4a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1154}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊流程/u1.png"}},
{
                  "id":"b2eb59563581475b9f62cd2a39088951",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1320,
                      "y":920},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9cc17ecbcb141f6a595ccf6dcd36332",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1320,
                          "y":920},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State1",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d3c56f13702c484c9410011232145b4c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7a25ef8b20664eac882e1b377ed5c4b9",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e35bde3bafd848efaa93d0c6ad0ac8db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":979}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊流程/u5.png"}},
{
                  "id":"99dc55dd8ab14b6f915de223442eeb5a",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":476,
                      "y":660},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e91cd639489455f837fecf3c796dd9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":476,
                          "y":660},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State0",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e1d649246b374fa5a31933fc70a9a48e",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1327,
                      "y":660},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be60c63acea8435583c40e3ef823f6fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1327,
                          "y":660},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State2",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"521ecc7ce6b44e9296ca08f1f8258896",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4d093eceac2547e2a3c82f29038e71fe",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1521}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62d1182935e949b89d6178dfb57b4ea7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1521}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊流程/u11.png"}},
{
                  "id":"4502ebeee35d4becbd0a565b4dbf164c",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1310,
                      "y":1293},
                    "size":{
                      "width":120,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5c676e899d44dc9b93974bb581c1703",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1310,
                          "y":1293},
                        "size":{
                          "width":120,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State3",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0546dee1d33e43bf998427f04a1df196",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a850b1ecf0b84fcd82a23b8e2586c6d0",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1018}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"49713f3de9f54a6c92b99267d5ce0ebd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1018}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊流程/u15.png"}},
{
                  "id":"a822a8425a1848f1a2baeee0bee13f37",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":491,
                      "y":784},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02c09cd5bfeb42a3b426b3ba25a87756",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":491,
                          "y":784},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State2",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dd5a1ff70bfa4265ae7beb46333bf60d",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1310,
                      "y":784},
                    "size":{
                      "width":120,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d6ab9c20d0d4625ace66768cee0a2c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1310,
                          "y":784},
                        "size":{
                          "width":120,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State3",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"3abb8b8ac8bd4afd9447a42433e2e1a6",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"48590743bbd54ae990e6b4ea203af2bd",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":4,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1599}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d0bb14e308d4325beaf7b28080294cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":4,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1599}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊流程/u21.png"}},
{
                  "id":"38b820fb7c174c33b0a29be4c601d97f",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":4,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":490,
                      "y":1370},
                    "size":{
                      "width":120,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e995f19a0b684d85895bfdcb6eec2640",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":4,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":490,
                          "y":1370},
                        "size":{
                          "width":120,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊流程 to State3",
                              "panelsToStates":[{
                                  "panelPath":["067173a992dd41b2aaa31ca8bd86305f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d065b9fb57e34d9daac486c1a4e8dd0e",
                  "label":"",
                  "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                  "panelIndex":4,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1310,
                      "y":1370},
                    "size":{
                      "width":120,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"154bc04aca8146039b5b99e0f4a37298",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"067173a992dd41b2aaa31ca8bd86305f",
                      "panelIndex":4,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1310,
                          "y":1370},
                        "size":{
                          "width":120,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 個人設定 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"個人設定.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "067173a992dd41b2aaa31ca8bd86305f":{
      "scriptId":"u0"},
    "2b58a29cbeea4ab39ca6aab6bd660f79":{
      "scriptId":"u1"},
    "b1c643ff3f104c4e94e91e6897170d4a":{
      "scriptId":"u2"},
    "b2eb59563581475b9f62cd2a39088951":{
      "scriptId":"u3"},
    "e9cc17ecbcb141f6a595ccf6dcd36332":{
      "scriptId":"u4"},
    "7a25ef8b20664eac882e1b377ed5c4b9":{
      "scriptId":"u5"},
    "e35bde3bafd848efaa93d0c6ad0ac8db":{
      "scriptId":"u6"},
    "99dc55dd8ab14b6f915de223442eeb5a":{
      "scriptId":"u7"},
    "4e91cd639489455f837fecf3c796dd9c":{
      "scriptId":"u8"},
    "e1d649246b374fa5a31933fc70a9a48e":{
      "scriptId":"u9"},
    "be60c63acea8435583c40e3ef823f6fd":{
      "scriptId":"u10"},
    "4d093eceac2547e2a3c82f29038e71fe":{
      "scriptId":"u11"},
    "62d1182935e949b89d6178dfb57b4ea7":{
      "scriptId":"u12"},
    "4502ebeee35d4becbd0a565b4dbf164c":{
      "scriptId":"u13"},
    "d5c676e899d44dc9b93974bb581c1703":{
      "scriptId":"u14"},
    "a850b1ecf0b84fcd82a23b8e2586c6d0":{
      "scriptId":"u15"},
    "49713f3de9f54a6c92b99267d5ce0ebd":{
      "scriptId":"u16"},
    "a822a8425a1848f1a2baeee0bee13f37":{
      "scriptId":"u17"},
    "02c09cd5bfeb42a3b426b3ba25a87756":{
      "scriptId":"u18"},
    "dd5a1ff70bfa4265ae7beb46333bf60d":{
      "scriptId":"u19"},
    "3d6ab9c20d0d4625ace66768cee0a2c9":{
      "scriptId":"u20"},
    "48590743bbd54ae990e6b4ea203af2bd":{
      "scriptId":"u21"},
    "4d0bb14e308d4325beaf7b28080294cc":{
      "scriptId":"u22"},
    "38b820fb7c174c33b0a29be4c601d97f":{
      "scriptId":"u23"},
    "e995f19a0b684d85895bfdcb6eec2640":{
      "scriptId":"u24"},
    "d065b9fb57e34d9daac486c1a4e8dd0e":{
      "scriptId":"u25"},
    "154bc04aca8146039b5b99e0f4a37298":{
      "scriptId":"u26"}}});