$axure.loadCurrentPage({
  "url":"遠距工作者註冊.html",
  "generationDate":new Date(1404292430223.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"6838a549fb6e4f13a9088d024f614790",
    "type":"Axure:Page",
    "name":"遠距工作者註冊",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e3dbf47c7ea74bdd825a347f86b2e2f8",
          "label":"Freelancer註冊頁",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"31e5decb0ea648b69453b22ced93751c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"60c80f14b0b74a4cb4d38e1cdbe4b3dd",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":1135}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28f7ddef2b154c2da6c8ccf0f6bb5724",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":1135}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"91fb88e36d3f4dac918e166a949d99bf",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4bc9fa69ba004db9b1bbab2d6a679cd6",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1903,
                      "height":979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52b6b606455b410c857bff1150944a18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1903,
                          "height":979}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u3.png"}},
{
                  "id":"1447dd9eb651437297e45978d35e83b2",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":710,
                      "y":210},
                    "size":{
                      "width":500,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbc676fc61c74670b6757944445a7f53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":710,
                          "y":210},
                        "size":{
                          "width":500,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u5.png"}},
{
                  "id":"a7a944006e884867a69de2c50c55632c",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":720,
                      "y":213},
                    "size":{
                      "width":270,
                      "height":44},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57c8496664744aea85bf0337277fb1b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":720,
                          "y":213},
                        "size":{
                          "width":270,
                          "height":44},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u7.png"}},
{
                  "id":"40248e9d38c74766ad1d2e5aae031f70",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":440,
                      "y":100},
                    "size":{
                      "width":1020,
                      "height":320},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10bcaa8b8abe4dfe80efcae9a7438095",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":440,
                          "y":100},
                        "size":{
                          "width":1020,
                          "height":320},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊頁 to State3",
                              "panelsToStates":[{
                                  "panelPath":["e3dbf47c7ea74bdd825a347f86b2e2f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"42e56d98c35644e0b89f6dc9acaa5eb4",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"44d13b880c484c95a90cd7b205b35065",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":935}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6c57378477d43ce93e4990621f18582",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":935}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u11.png"}},
{
                  "id":"827ab15cefdf4276affee2fe72a69690",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":880,
                      "y":300},
                    "size":{
                      "width":170,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffea7aca09914c2390d2bf58d2139888",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":880,
                          "y":300},
                        "size":{
                          "width":170,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u13.png"}},
{
                  "id":"a5372f5369c449b2ab3cf30bb648d52f",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1409,
                      "y":0},
                    "size":{
                      "width":503,
                      "height":93},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e390a08acf17429aa8a726a9df6f0c54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1409,
                          "y":0},
                        "size":{
                          "width":503,
                          "height":93},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u15.png"}},
{
                  "id":"252eccbd9d33408bb24cac8e214241c1",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":450,
                      "y":100},
                    "size":{
                      "width":1030,
                      "height":340},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68a17f048cfc47a6b3145e528931678e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":450,
                          "y":100},
                        "size":{
                          "width":1030,
                          "height":340},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Freelancer註冊頁 to State4",
                              "panelsToStates":[{
                                  "panelPath":["e3dbf47c7ea74bdd825a347f86b2e2f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"1aaf1c10fc7944f0a6673dceadb042f1",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e0f1816412234ab8a8037825f7c4b43d",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1920,
                      "height":935}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"360f641d9f9c446687e9d4dae927d8ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1920,
                          "height":935}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u19.png"}},
{
                  "id":"f79e04a9e7864102b5905a86ffb97e9f",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":870,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc74f762269c46d9b9d90535cd931e4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":870,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/遠距工作者註冊/u21.png"}},
{
                  "id":"da9689a2a85844b882f822e7f4e626ab",
                  "label":"",
                  "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":680,
                      "y":530},
                    "size":{
                      "width":560,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1d3765903b245d3a911f6ee0624997c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3dbf47c7ea74bdd825a347f86b2e2f8",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":680,
                          "y":530},
                        "size":{
                          "width":560,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 遠距工作者註冊流程 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"遠距工作者註冊流程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c727e4c8515349c1ad5d764c237cc130",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":860},
            "size":{
              "width":610,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8e0f155a464b84ac489e977e8ac7a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":860},
                "size":{
                  "width":610,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Freelancer註冊頁 to State2",
                      "panelsToStates":[{
                          "panelPath":["e3dbf47c7ea74bdd825a347f86b2e2f8"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e3dbf47c7ea74bdd825a347f86b2e2f8":{
      "scriptId":"u0"},
    "60c80f14b0b74a4cb4d38e1cdbe4b3dd":{
      "scriptId":"u1"},
    "28f7ddef2b154c2da6c8ccf0f6bb5724":{
      "scriptId":"u2"},
    "4bc9fa69ba004db9b1bbab2d6a679cd6":{
      "scriptId":"u3"},
    "52b6b606455b410c857bff1150944a18":{
      "scriptId":"u4"},
    "1447dd9eb651437297e45978d35e83b2":{
      "scriptId":"u5"},
    "dbc676fc61c74670b6757944445a7f53":{
      "scriptId":"u6"},
    "a7a944006e884867a69de2c50c55632c":{
      "scriptId":"u7"},
    "57c8496664744aea85bf0337277fb1b6":{
      "scriptId":"u8"},
    "40248e9d38c74766ad1d2e5aae031f70":{
      "scriptId":"u9"},
    "10bcaa8b8abe4dfe80efcae9a7438095":{
      "scriptId":"u10"},
    "44d13b880c484c95a90cd7b205b35065":{
      "scriptId":"u11"},
    "e6c57378477d43ce93e4990621f18582":{
      "scriptId":"u12"},
    "827ab15cefdf4276affee2fe72a69690":{
      "scriptId":"u13"},
    "ffea7aca09914c2390d2bf58d2139888":{
      "scriptId":"u14"},
    "a5372f5369c449b2ab3cf30bb648d52f":{
      "scriptId":"u15"},
    "e390a08acf17429aa8a726a9df6f0c54":{
      "scriptId":"u16"},
    "252eccbd9d33408bb24cac8e214241c1":{
      "scriptId":"u17"},
    "68a17f048cfc47a6b3145e528931678e":{
      "scriptId":"u18"},
    "e0f1816412234ab8a8037825f7c4b43d":{
      "scriptId":"u19"},
    "360f641d9f9c446687e9d4dae927d8ab":{
      "scriptId":"u20"},
    "f79e04a9e7864102b5905a86ffb97e9f":{
      "scriptId":"u21"},
    "fc74f762269c46d9b9d90535cd931e4e":{
      "scriptId":"u22"},
    "da9689a2a85844b882f822e7f4e626ab":{
      "scriptId":"u23"},
    "c1d3765903b245d3a911f6ee0624997c":{
      "scriptId":"u24"},
    "c727e4c8515349c1ad5d764c237cc130":{
      "scriptId":"u25"},
    "8d8e0f155a464b84ac489e977e8ac7a4":{
      "scriptId":"u26"}}});