$axure.loadCurrentPage({
  "url":"邀請遠距工作者申請案件.html",
  "generationDate":new Date(1404292445066.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"e24bf13a8ad84f0f9afa5be193074c03",
    "type":"Axure:Page",
    "name":"邀請遠距工作者申請案件",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff4eafb8332f499f82227566abe6480e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeab54cbcb44419dbda57a2692339854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"201654ac02f34300aa2a1c1de5f3a991",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1902,
              "height":930},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce12cc67938a454282c78bb0c4e173c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1902,
                  "height":930},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u0.png"}},
{
          "id":"27c58ea774a245b5adf95c20900931a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1010},
            "size":{
              "width":1902,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a1a44414fd745b9a5612fe6f6e0421f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1010},
                "size":{
                  "width":1902,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u2.png"}},
{
          "id":"93162318656041069886e029416254ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":120},
            "size":{
              "width":1024,
              "height":860},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8469f9faf7554af89c16d416117eae89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":120},
                "size":{
                  "width":1024,
                  "height":860},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u6.png"}},
{
          "id":"a3cc5f75a7ff40b183f2e03bf6962f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":10},
            "size":{
              "width":138,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3f8a04ea834e46af20b5bf22493acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":10},
                "size":{
                  "width":138,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d724073560f452895f58b0a0c5113b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":616,
              "y":10},
            "size":{
              "width":83,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af07e2026eb464a8e19a1702a3ee5c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":616,
                  "y":10},
                "size":{
                  "width":83,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3dd40522db14d6cb2a744a367d63036",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":737,
              "y":10},
            "size":{
              "width":55,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df8aba85fb8240769eb28055c262d84c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":737,
                  "y":10},
                "size":{
                  "width":55,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a413b055b5b94c6c8030380eb8af09c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":830,
              "y":10},
            "size":{
              "width":58,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1560c929612d4ebab0a135fed518d7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":830,
                  "y":10},
                "size":{
                  "width":58,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"831edae8e81646f89971b270371d0a59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f80426e2f14bae957b118fd0721f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"e6720b316bec425188a09c3c52e70db5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "location":{
              "x":466,
              "y":380},
            "size":{
              "width":970,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c1196e6e204e388c6e395bbcb8c9ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "location":{
                  "x":466,
                  "y":380},
                "size":{
                  "width":970,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/u21.png"}},
{
          "id":"5149e470b94c466b96d593dbbdd3edb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":466,
              "y":418},
            "size":{
              "width":970,
              "height":122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab60b201dda44258f9895fc32630750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":466,
                  "y":418},
                "size":{
                  "width":970,
                  "height":122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u20.png"}},
{
          "id":"3955e468d1c04233bc823fd589999c23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":476,
              "y":392},
            "size":{
              "width":280,
              "height":16},
            "rotation":"0",
            "textRotation":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9907156c81244f9d955b9c9920074d85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":392},
                "size":{
                  "width":280,
                  "height":16},
                "rotation":"0",
                "textRotation":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60c98594e0f04312994e2396162cc9cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":142},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6281ab41c7a6448aa92526378cbf9ff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":142},
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3db7f091e1ed4705a09ac476bd828f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":476,
              "y":440},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af26df69eca34401b54b5b7187fa7c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":476,
                  "y":440},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb23cc569544faaa86a9078efbb69f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":476,
              "y":472},
            "size":{
              "width":404,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13ddfc94a5764eeaa8c2ef603129c43c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":476,
                  "y":472},
                "size":{
                  "width":404,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u28.png"}},
{
          "id":"a48d36549bf246b892d2d56287f0ffca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":523,
              "y":435},
            "size":{
              "width":503,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107f27a91acb42979808327e3f2a5b66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":523,
                  "y":435},
                "size":{
                  "width":503,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u30.png"}},
{
          "id":"34a2f4cddbe64c4eabb8da1942a9002c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "location":{
              "x":466,
              "y":570},
            "size":{
              "width":970,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb0b3a9915842678510dd351882f873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "location":{
                  "x":466,
                  "y":570},
                "size":{
                  "width":970,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/u21.png"}},
{
          "id":"733fa69f0a9d478495c807c65ff19936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":466,
              "y":608},
            "size":{
              "width":970,
              "height":232},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"decc62de7acf4fb4aa7b9b757b7323d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":466,
                  "y":608},
                "size":{
                  "width":970,
                  "height":232},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/u23.png"}},
{
          "id":"3fe7d230a9c746aab9780c3f41295eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":476,
              "y":582},
            "size":{
              "width":280,
              "height":16},
            "rotation":"0",
            "textRotation":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c6a2918c4a64ad39e012ec6173ef55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":582},
                "size":{
                  "width":280,
                  "height":16},
                "rotation":"0",
                "textRotation":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64ab1bcc83cf47e48e9dc8cfecfce818",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "location":{
              "x":466,
              "y":194},
            "size":{
              "width":970,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e132c1c5bf184708843b6ff30f086ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "location":{
                  "x":466,
                  "y":194},
                "size":{
                  "width":970,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/u21.png"}},
{
          "id":"08720a29a5d440b1be18b3b19e1a7781",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":466,
              "y":232},
            "size":{
              "width":970,
              "height":122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74c514bb7964931a72fad17a689f18c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":466,
                  "y":232},
                "size":{
                  "width":970,
                  "height":122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u20.png"}},
{
          "id":"ef0ba60334124f8886b4936062c7f961",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":476,
              "y":206},
            "size":{
              "width":280,
              "height":16},
            "rotation":"0",
            "textRotation":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c68b1bad59499683adf711c3c319fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":206},
                "size":{
                  "width":280,
                  "height":16},
                "rotation":"0",
                "textRotation":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a2a4c596d39464cb54b0da45b56c02d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":268},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65dd97469d384275ad49b191f0ae1ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":268},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u44.png"}},
{
          "id":"a03567dea1f142689102831554b0d5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":544,
              "y":282},
            "size":{
              "width":118,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea28501f4dc7483aba51a857e3c25b24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":544,
                  "y":282},
                "size":{
                  "width":118,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bcbe68954c34cfb9fe60ec42b6e5139",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":672,
              "y":286},
            "size":{
              "width":49,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e81990c4fb7948eaab6f648541935351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":672,
                  "y":286},
                "size":{
                  "width":49,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u48.png"}},
{
          "id":"ec133e54b8574ec6aa85c2bc6c5aea01",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":476,
              "y":628},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef2b811d9d045408f43b28440adcca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":476,
                  "y":628},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"734c543bff7f45bf956183728231dcf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":523,
              "y":628},
            "size":{
              "width":877,
              "height":182},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff3d88370eb94f61b6971a695f769b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":523,
                  "y":628},
                "size":{
                  "width":877,
                  "height":182},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u52.png"}},
{
          "id":"f78fcd856c9e4be8bbb3fe7a2435fd7b",
          "label":"Button.Green",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF58CB73}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CB164}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF5BBD72},
            "location":{
              "x":466,
              "y":870},
            "size":{
              "width":110,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feebbd8b31364d37968c62ca2184d90a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF58CB73}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4CB164}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5BBD72},
                "location":{
                  "x":466,
                  "y":870},
                "size":{
                  "width":110,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/button_green_u135.png",
            "mouseOver~":"images/申請案件/button_green_u135_mouseOver.png",
            "mouseDown~":"images/申請案件/button_green_u135_mouseDown.png"}},
{
          "id":"9d63e1656eba43f5b61c52c92b9a12fa",
          "label":"Button.Red",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE75859}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD24B4C}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFD95C5C},
            "location":{
              "x":589,
              "y":870},
            "size":{
              "width":110,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9705ac72a80447dfbac3138ad03cd94e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE75859}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD24B4C}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD95C5C},
                "location":{
                  "x":589,
                  "y":870},
                "size":{
                  "width":110,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件/button_red_u133.png",
            "mouseOver~":"images/申請案件/button_red_u133_mouseOver.png",
            "mouseDown~":"images/申請案件/button_red_u133_mouseDown.png"}},
{
          "id":"5902198a07d34e26a8d497a1181e620f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":466,
              "y":916},
            "size":{
              "width":384,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b01a9566a47346a3b1e627e7711f0a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":466,
                  "y":916},
                "size":{
                  "width":384,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/邀請遠距工作者申請案件/u58.png"}},
{
          "id":"106d9b24c98d47c0a5f72583b2baddc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":91},
            "size":{
              "width":200,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0f7ee1184fc4b7093bb640a28586637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":91},
                "size":{
                  "width":200,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac45e1271d294103b7e14ec3ceaa799a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f174bf66a5de4fad99d342d1de39a730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"3ccce1e4f88b47f88d62ba495938f151",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ebe0b660ef4ea1a7d52a57cf154a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"ec1500b0a6804598a57f62dbddddc201",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1903,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cadb5b4410c44418b80cf940f8544768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1903,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u51.png"}},
{
          "id":"e158a36f3dc34149aa5d002a32769156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4282bd3578954e218054c7e56c4782c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e836015dfa2b4f068e4f5ae297d3b0a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"844c6a9233f0487ab5714c931c0e75c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfe902a6f3ec4c2fbd0913c5cf4e3f14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a31e5a3ab86446c1994864cef57ae0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6dcdbbf495b4e408a9b23303dfadac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efca94d4b669406baaa77643fa0d82f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff4eafb8332f499f82227566abe6480e":{
      "scriptId":"u0"},
    "eeab54cbcb44419dbda57a2692339854":{
      "scriptId":"u1"},
    "201654ac02f34300aa2a1c1de5f3a991":{
      "scriptId":"u2"},
    "ce12cc67938a454282c78bb0c4e173c5":{
      "scriptId":"u3"},
    "27c58ea774a245b5adf95c20900931a4":{
      "scriptId":"u4"},
    "3a1a44414fd745b9a5612fe6f6e0421f":{
      "scriptId":"u5"},
    "93162318656041069886e029416254ec":{
      "scriptId":"u6"},
    "8469f9faf7554af89c16d416117eae89":{
      "scriptId":"u7"},
    "a3cc5f75a7ff40b183f2e03bf6962f1f":{
      "scriptId":"u8"},
    "2e3f8a04ea834e46af20b5bf22493acf":{
      "scriptId":"u9"},
    "9d724073560f452895f58b0a0c5113b0":{
      "scriptId":"u10"},
    "0af07e2026eb464a8e19a1702a3ee5c5":{
      "scriptId":"u11"},
    "a3dd40522db14d6cb2a744a367d63036":{
      "scriptId":"u12"},
    "df8aba85fb8240769eb28055c262d84c":{
      "scriptId":"u13"},
    "a413b055b5b94c6c8030380eb8af09c2":{
      "scriptId":"u14"},
    "1560c929612d4ebab0a135fed518d7d5":{
      "scriptId":"u15"},
    "831edae8e81646f89971b270371d0a59":{
      "scriptId":"u16"},
    "47f80426e2f14bae957b118fd0721f3d":{
      "scriptId":"u17"},
    "e6720b316bec425188a09c3c52e70db5":{
      "scriptId":"u18"},
    "10c1196e6e204e388c6e395bbcb8c9ea":{
      "scriptId":"u19"},
    "5149e470b94c466b96d593dbbdd3edb1":{
      "scriptId":"u20"},
    "aab60b201dda44258f9895fc32630750":{
      "scriptId":"u21"},
    "3955e468d1c04233bc823fd589999c23":{
      "scriptId":"u22"},
    "9907156c81244f9d955b9c9920074d85":{
      "scriptId":"u23"},
    "60c98594e0f04312994e2396162cc9cf":{
      "scriptId":"u24"},
    "6281ab41c7a6448aa92526378cbf9ff1":{
      "scriptId":"u25"},
    "3db7f091e1ed4705a09ac476bd828f7f":{
      "scriptId":"u26"},
    "af26df69eca34401b54b5b7187fa7c49":{
      "scriptId":"u27"},
    "0fb23cc569544faaa86a9078efbb69f5":{
      "scriptId":"u28"},
    "13ddfc94a5764eeaa8c2ef603129c43c":{
      "scriptId":"u29"},
    "a48d36549bf246b892d2d56287f0ffca":{
      "scriptId":"u30"},
    "107f27a91acb42979808327e3f2a5b66":{
      "scriptId":"u31"},
    "34a2f4cddbe64c4eabb8da1942a9002c":{
      "scriptId":"u32"},
    "beb0b3a9915842678510dd351882f873":{
      "scriptId":"u33"},
    "733fa69f0a9d478495c807c65ff19936":{
      "scriptId":"u34"},
    "decc62de7acf4fb4aa7b9b757b7323d6":{
      "scriptId":"u35"},
    "3fe7d230a9c746aab9780c3f41295eb7":{
      "scriptId":"u36"},
    "6c6a2918c4a64ad39e012ec6173ef55d":{
      "scriptId":"u37"},
    "64ab1bcc83cf47e48e9dc8cfecfce818":{
      "scriptId":"u38"},
    "e132c1c5bf184708843b6ff30f086ad3":{
      "scriptId":"u39"},
    "08720a29a5d440b1be18b3b19e1a7781":{
      "scriptId":"u40"},
    "e74c514bb7964931a72fad17a689f18c":{
      "scriptId":"u41"},
    "ef0ba60334124f8886b4936062c7f961":{
      "scriptId":"u42"},
    "90c68b1bad59499683adf711c3c319fb":{
      "scriptId":"u43"},
    "4a2a4c596d39464cb54b0da45b56c02d":{
      "scriptId":"u44"},
    "65dd97469d384275ad49b191f0ae1ec2":{
      "scriptId":"u45"},
    "a03567dea1f142689102831554b0d5c3":{
      "scriptId":"u46"},
    "ea28501f4dc7483aba51a857e3c25b24":{
      "scriptId":"u47"},
    "7bcbe68954c34cfb9fe60ec42b6e5139":{
      "scriptId":"u48"},
    "e81990c4fb7948eaab6f648541935351":{
      "scriptId":"u49"},
    "ec133e54b8574ec6aa85c2bc6c5aea01":{
      "scriptId":"u50"},
    "9ef2b811d9d045408f43b28440adcca5":{
      "scriptId":"u51"},
    "734c543bff7f45bf956183728231dcf7":{
      "scriptId":"u52"},
    "ff3d88370eb94f61b6971a695f769b45":{
      "scriptId":"u53"},
    "f78fcd856c9e4be8bbb3fe7a2435fd7b":{
      "scriptId":"u54"},
    "feebbd8b31364d37968c62ca2184d90a":{
      "scriptId":"u55"},
    "9d63e1656eba43f5b61c52c92b9a12fa":{
      "scriptId":"u56"},
    "9705ac72a80447dfbac3138ad03cd94e":{
      "scriptId":"u57"},
    "5902198a07d34e26a8d497a1181e620f":{
      "scriptId":"u58"},
    "b01a9566a47346a3b1e627e7711f0a04":{
      "scriptId":"u59"},
    "106d9b24c98d47c0a5f72583b2baddc2":{
      "scriptId":"u60"},
    "c0f7ee1184fc4b7093bb640a28586637":{
      "scriptId":"u61"},
    "ac45e1271d294103b7e14ec3ceaa799a":{
      "scriptId":"u62"},
    "f174bf66a5de4fad99d342d1de39a730":{
      "scriptId":"u63"},
    "3ccce1e4f88b47f88d62ba495938f151":{
      "scriptId":"u64"},
    "57ebe0b660ef4ea1a7d52a57cf154a98":{
      "scriptId":"u65"},
    "ec1500b0a6804598a57f62dbddddc201":{
      "scriptId":"u66"},
    "cadb5b4410c44418b80cf940f8544768":{
      "scriptId":"u67"},
    "e158a36f3dc34149aa5d002a32769156":{
      "scriptId":"u68"},
    "4282bd3578954e218054c7e56c4782c3":{
      "scriptId":"u69"},
    "e836015dfa2b4f068e4f5ae297d3b0a5":{
      "scriptId":"u70"},
    "844c6a9233f0487ab5714c931c0e75c7":{
      "scriptId":"u71"},
    "dfe902a6f3ec4c2fbd0913c5cf4e3f14":{
      "scriptId":"u72"},
    "a31e5a3ab86446c1994864cef57ae0a7":{
      "scriptId":"u73"},
    "d6dcdbbf495b4e408a9b23303dfadac6":{
      "scriptId":"u74"},
    "efca94d4b669406baaa77643fa0d82f9":{
      "scriptId":"u75"}}});