$axure.loadCurrentPage({
  "url":"檢視推薦遠距工作.html",
  "generationDate":new Date(1404292442245.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"18155cc98fc040fd8438eabe6fb37bdb",
    "type":"Axure:Page",
    "name":"檢視推薦遠距工作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"696ff2d139814d82b5908747ee7c67aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bca7eeb8ece4acfb41f562f3c2752d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/雇主登入後/u0.png"}},
{
          "id":"53f8b5e5e7c3423883a64284798d25d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE3E3E3},
            "location":{
              "x":400,
              "y":114},
            "size":{
              "width":1120,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95df4a8d790446319cba8f1bf8470f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE3E3E3},
                "location":{
                  "x":400,
                  "y":114},
                "size":{
                  "width":1120,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視推薦遠距工作/u2.png"}},
{
          "id":"9f786fb0b55747dba757ea40b881240e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":183},
            "size":{
              "width":1100,
              "height":717},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f0ef60ae3549088a6ce6f29e7de985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":183},
                "size":{
                  "width":1100,
                  "height":717},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視推薦遠距工作/u4.png"}},
{
          "id":"ade8fd391c4145cc9cb4d5c1c84232ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":245},
            "size":{
              "width":686,
              "height":309}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"054581941999484688786fd0abce17d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":245},
                "size":{
                  "width":686,
                  "height":309}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視推薦遠距工作/u6.png"}},
{
          "id":"67bc2eaa2ea7474ab8641f14f21cbc35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":582},
            "size":{
              "width":686,
              "height":309}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"335b8113071443df9f0ac09a19991167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":582},
                "size":{
                  "width":686,
                  "height":309}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視推薦遠距工作/u6.png"}},
{
          "id":"d0e7ec5f9a95436581752c18248b1f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCFF,
              "opacity":1},
            "location":{
              "x":767.5,
              "y":100},
            "size":{
              "width":385,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d14202d95fa4b33a34fb34f995ed476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF,
                  "opacity":1},
                "location":{
                  "x":767.5,
                  "y":100},
                "size":{
                  "width":385,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0352581217cf46ed9b1bb50fb7887353",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":440,
              "y":201},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7210a6a7613546b591f7743c00475fd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":201},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68ace1213bbf4ce4b492a8972825692f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome Regular', 'FontAwesome'",
            "fontSize":"36px",
            "baseStyle":"acf17f55de514228870a79e6ef16480f",
            "location":{
              "x":410,
              "y":194},
            "size":{
              "width":28,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"654d9f0827954f28b6be8adc55d13b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome Regular', 'FontAwesome'",
                "fontSize":"36px",
                "baseStyle":"acf17f55de514228870a79e6ef16480f",
                "location":{
                  "x":410,
                  "y":194},
                "size":{
                  "width":28,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"248fb2cafce542db9bd534ff863703c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":410,
              "y":194},
            "size":{
              "width":200,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77a38ca7dff45e482408218b811e607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":410,
                  "y":194},
                "size":{
                  "width":200,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a07e13de7b2c4b6480d7f97ba8aad737",
          "label":"Dropdown button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0AD4E},
            "location":{
              "x":860,
              "y":331},
            "size":{
              "width":58,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD9D9D9},
            "linePattern":"none",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"035beed97fd346cfb17686bc48e5ea9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0AD4E},
                "location":{
                  "x":860,
                  "y":331},
                "size":{
                  "width":58,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD9D9D9},
                "linePattern":"none",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"已雇用",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;已雇用&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"已雇用",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"取消",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;雇用&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"雇用",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/檢視推薦遠距工作/dropdown_button_u18.png",
            "selected~":"images/檢視推薦遠距工作/dropdown_button_u18_selected.png",
            "mouseOver~":"images/檢視推薦遠距工作/dropdown_button_u18_mouseOver.png"}},
{
          "id":"1890cff70ec44f46aac53103be3eaf32",
          "label":"Dropdown button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0AD4E},
            "location":{
              "x":860,
              "y":667},
            "size":{
              "width":58,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD9D9D9},
            "linePattern":"none",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4d4cc812b84021ae76324e0b18f1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0AD4E},
                "location":{
                  "x":860,
                  "y":667},
                "size":{
                  "width":58,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD9D9D9},
                "linePattern":"none",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"已雇用",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;已雇用&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"已雇用",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"取消",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;雇用&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"雇用",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/檢視推薦遠距工作/dropdown_button_u18.png",
            "selected~":"images/檢視推薦遠距工作/dropdown_button_u18_selected.png",
            "mouseOver~":"images/檢視推薦遠距工作/dropdown_button_u18_mouseOver.png"}},
{
          "id":"918bde829ae049299f1c2432b94837b9",
          "label":"Dropdown button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFFD2322D},
            "location":{
              "x":798,
              "y":331},
            "size":{
              "width":58,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD9D9D9},
            "linePattern":"none",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b3634a417149b5a8de83d6751f3630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD2322D},
                "location":{
                  "x":798,
                  "y":331},
                "size":{
                  "width":58,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD9D9D9},
                "linePattern":"none",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"wait",
                      "description":"Wait 100 ms",
                      "waitTime":100},
{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]},
{
                  "description":"儲存",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;已儲存&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"已儲存",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"取消",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;儲存&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"儲存",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/檢視推薦遠距工作/dropdown_button_u22.png",
            "selected~":"images/檢視推薦遠距工作/dropdown_button_u22_selected.png",
            "mouseOver~":"images/檢視推薦遠距工作/dropdown_button_u22_mouseOver.png"}},
{
          "id":"673658fe04e046109ccc17aa24c938b0",
          "label":"Dropdown button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFFD2322D},
            "location":{
              "x":798,
              "y":667},
            "size":{
              "width":58,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD9D9D9},
            "linePattern":"none",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c427fcf32a4045f184ac6b9c94531ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD2322D},
                "location":{
                  "x":798,
                  "y":667},
                "size":{
                  "width":58,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD9D9D9},
                "linePattern":"none",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"wait",
                      "description":"Wait 100 ms",
                      "waitTime":100},
{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]},
{
                  "description":"儲存",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;已儲存&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"已儲存",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"取消",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;儲存&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"儲存",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/檢視推薦遠距工作/dropdown_button_u22.png",
            "selected~":"images/檢視推薦遠距工作/dropdown_button_u22_selected.png",
            "mouseOver~":"images/檢視推薦遠距工作/dropdown_button_u22_mouseOver.png"}},
{
          "id":"b238b59f4cb44a9e8c05a3c46cdb4fde",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":23}},
          "adaptiveStyles":{
},
          "masterId":"96e31ac88e3944cf843d8f845f224998"},
{
          "id":"87a20b7f5fa4403a87ce8ac110afd3ab",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1680,
              "y":17}},
          "adaptiveStyles":{
},
          "masterId":"d1a1dfa27ac24ff2a583a261fc97d904"},
{
          "id":"2642768fcda8441a8935b12c59c1592b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1524,
              "y":17}},
          "adaptiveStyles":{
},
          "masterId":"d94c7ba1eaa34714a5d6253dffbe242f"},
{
          "id":"689b31528e094de39ef98cb2f30da3de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991050360c8646ebb245994aed8be9c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97f36c4899c24719af3a948a775ca7d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c3b4ec986c14db28b8aeaec889ca1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0a7c79a82eb4b8d910ed08ee51babbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3c1ef902284b5d9d12648d108c2e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"299f6b6ad49340538b8d5bbe05231f8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da813215a594fe58ec5ddd37caf7747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "96e31ac88e3944cf843d8f845f224998":{
      "packageId":"96e31ac88e3944cf843d8f845f224998",
      "type":"Axure:Master",
      "name":"dropdown",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"506f205c4d3f45b4a8d8879d40c585c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":117,
                "y":0},
              "size":{
                "width":170,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9b048d4c0424257a86f9053565fae84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":117,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44d2cae74264fe28efc5a9f011db65c",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":63},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"0ac610d031604d3e8252ebd82275eec3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b2490259cfb24a27937c8cc947bca228",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":102},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"17d97940863d453493d1773f25937fa8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":102},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 個人設定 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"個人設定.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"73dd3af138be44458bd25a2634764d55",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afb506fe892a47528ea57c3d3074e449",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"1a6249c0920944ceb89ae7e1be69ce09",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":141},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e45023e673d24bcda3e25c34b974ecef",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":141},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open TeleWork首頁 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"telework__.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7e4f70b8597e4e87b9a74652345d9ede",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":24},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7c6bb4ed82e4d73b9ed1dc1cf37732b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":24},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 遠距工作者登入後(找案件) in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"遠距工作者登入後_找案件_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db4e0239fc24aa5838f7a781f489e0f",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"18px",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099CC,
                        "opacity":1},
                      "location":{
                        "x":70,
                        "y":75},
                      "size":{
                        "width":170,
                        "height":36},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"26d3c97b49b9491e915ab197141698fb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"18px",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099CC,
                            "opacity":1},
                          "location":{
                            "x":70,
                            "y":75},
                          "size":{
                            "width":170,
                            "height":36},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u135.png"}},
{
                    "id":"5a69b865ebd6452ebabd85af7eedb35b",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":74},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c28622cbcfd4bc198d16cf0651c1dac",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":74},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 雇主登入後 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"雇主登入後.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"61887cf395474173a1dd468a457de938",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":-40,
                "y":50},
              "size":{
                "width":900,
                "height":460},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0571e4ff7de34900acd1a730a6b1eb2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":-40,
                    "y":50},
                  "size":{
                    "width":900,
                    "height":460},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73af37ef2bc548cfb218313275d91d54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":90},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9dc390a6c3e4fe89c75bd55943e8173",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":90},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 遠距工作者登入後(找案件) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"遠距工作者登入後_找案件_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c34866e4049b438ea46fb17ab8c63e6b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":140},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d929f16ffcd4e71bd2f5ca13b0d445f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":140},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 雇主登入後 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"雇主登入後.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d1a1dfa27ac24ff2a583a261fc97d904":{
      "packageId":"d1a1dfa27ac24ff2a583a261fc97d904",
      "type":"Axure:Master",
      "name":"change currency",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9769e695b0664441b3ccd5fbff65efea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":44,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0513e769e9d247dcad8d4b622b25b6ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":0},
                  "size":{
                    "width":44,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["7fc383c5928e49879a99dc4d9df850ae"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/遠距工作者詳細資料/u146.png"}},
{
            "id":"7fc383c5928e49879a99dc4d9df850ae",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":66},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"e234e68ced72465cb1fa9db278729a4e",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"dde9df61cfeb4ad0b61066271a6d78ad",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc21472bed343a3aef07d5ca3ec1639",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"b71ae81389e54486818e6630092762e8",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":30},
                      "size":{
                        "width":287,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c95221fca89e45be83003b35dbef975d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":287,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u151.png"}},
{
                    "id":"e8b8f022d802460e81c3242754b4631b",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":24},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"57944770132240ff89cbea05872a77de",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":24},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cb28593ac22e4ff982b158f27a2b81af",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":58},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"68c1f570ff814e418efd898b1f5a29aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":58},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9eae22708664bd780e699248735f154",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":92},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7d5f6bf4eb94b728c3cd1c2ca7b230d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":92},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c0e451649a8443e6b1d18c009d17b970",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":126},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"604e76edfd1f4bc19d41c745717c608b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":126},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3f060a28aabf42f0bc66baa1730d2dd1",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":160},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"95856e8d4e144148beb2044bf7442380",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":160},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "d94c7ba1eaa34714a5d6253dffbe242f":{
      "packageId":"d94c7ba1eaa34714a5d6253dffbe242f",
      "type":"Axure:Master",
      "name":"newinfo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"288ab1dc513d4d93aa14fe7c5f12cb0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":276,
                "y":0},
              "size":{
                "width":60,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11c910fab7bd4dd2afd5b9891a0bd868",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":276,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle info",
                        "objectsToFades":[{
                            "objectPath":["086570bf076446d99e2f75e95782f03d"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"086570bf076446d99e2f75e95782f03d",
            "label":"info",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":73},
              "size":{
                "width":345,
                "height":142},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3f0f17c212483eac523909f62362b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":false,
                "style":{
                  "location":{
                    "x":0,
                    "y":73},
                  "size":{
                    "width":345,
                    "height":142},
                  "visible":false},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/遠距工作者詳細資料/info_u166.png"}}]}}},
  "objectPaths":{
    "696ff2d139814d82b5908747ee7c67aa":{
      "scriptId":"u0"},
    "6bca7eeb8ece4acfb41f562f3c2752d5":{
      "scriptId":"u1"},
    "53f8b5e5e7c3423883a64284798d25d5":{
      "scriptId":"u2"},
    "95df4a8d790446319cba8f1bf8470f33":{
      "scriptId":"u3"},
    "9f786fb0b55747dba757ea40b881240e":{
      "scriptId":"u4"},
    "d8f0ef60ae3549088a6ce6f29e7de985":{
      "scriptId":"u5"},
    "ade8fd391c4145cc9cb4d5c1c84232ef":{
      "scriptId":"u6"},
    "054581941999484688786fd0abce17d7":{
      "scriptId":"u7"},
    "67bc2eaa2ea7474ab8641f14f21cbc35":{
      "scriptId":"u8"},
    "335b8113071443df9f0ac09a19991167":{
      "scriptId":"u9"},
    "d0e7ec5f9a95436581752c18248b1f34":{
      "scriptId":"u10"},
    "4d14202d95fa4b33a34fb34f995ed476":{
      "scriptId":"u11"},
    "0352581217cf46ed9b1bb50fb7887353":{
      "scriptId":"u12"},
    "7210a6a7613546b591f7743c00475fd6":{
      "scriptId":"u13"},
    "68ace1213bbf4ce4b492a8972825692f":{
      "scriptId":"u14"},
    "654d9f0827954f28b6be8adc55d13b7a":{
      "scriptId":"u15"},
    "248fb2cafce542db9bd534ff863703c3":{
      "scriptId":"u16"},
    "a77a38ca7dff45e482408218b811e607":{
      "scriptId":"u17"},
    "a07e13de7b2c4b6480d7f97ba8aad737":{
      "scriptId":"u18"},
    "035beed97fd346cfb17686bc48e5ea9f":{
      "scriptId":"u19"},
    "1890cff70ec44f46aac53103be3eaf32":{
      "scriptId":"u20"},
    "2a4d4cc812b84021ae76324e0b18f1df":{
      "scriptId":"u21"},
    "918bde829ae049299f1c2432b94837b9":{
      "scriptId":"u22"},
    "c0b3634a417149b5a8de83d6751f3630":{
      "scriptId":"u23"},
    "673658fe04e046109ccc17aa24c938b0":{
      "scriptId":"u24"},
    "c427fcf32a4045f184ac6b9c94531ae4":{
      "scriptId":"u25"},
    "b238b59f4cb44a9e8c05a3c46cdb4fde":{
      "scriptId":"u26",
      "506f205c4d3f45b4a8d8879d40c585c1":{
        "scriptId":"u27"},
      "e9b048d4c0424257a86f9053565fae84":{
        "scriptId":"u28"},
      "f44d2cae74264fe28efc5a9f011db65c":{
        "scriptId":"u29"},
      "b2490259cfb24a27937c8cc947bca228":{
        "scriptId":"u30"},
      "17d97940863d453493d1773f25937fa8":{
        "scriptId":"u31"},
      "73dd3af138be44458bd25a2634764d55":{
        "scriptId":"u32"},
      "afb506fe892a47528ea57c3d3074e449":{
        "scriptId":"u33"},
      "1a6249c0920944ceb89ae7e1be69ce09":{
        "scriptId":"u34"},
      "e45023e673d24bcda3e25c34b974ecef":{
        "scriptId":"u35"},
      "7e4f70b8597e4e87b9a74652345d9ede":{
        "scriptId":"u36"},
      "e7c6bb4ed82e4d73b9ed1dc1cf37732b":{
        "scriptId":"u37"},
      "1db4e0239fc24aa5838f7a781f489e0f":{
        "scriptId":"u38"},
      "26d3c97b49b9491e915ab197141698fb":{
        "scriptId":"u39"},
      "5a69b865ebd6452ebabd85af7eedb35b":{
        "scriptId":"u40"},
      "1c28622cbcfd4bc198d16cf0651c1dac":{
        "scriptId":"u41"},
      "61887cf395474173a1dd468a457de938":{
        "scriptId":"u42"},
      "0571e4ff7de34900acd1a730a6b1eb2e":{
        "scriptId":"u43"},
      "73af37ef2bc548cfb218313275d91d54":{
        "scriptId":"u44"},
      "f9dc390a6c3e4fe89c75bd55943e8173":{
        "scriptId":"u45"},
      "c34866e4049b438ea46fb17ab8c63e6b":{
        "scriptId":"u46"},
      "3d929f16ffcd4e71bd2f5ca13b0d445f":{
        "scriptId":"u47"}},
    "87a20b7f5fa4403a87ce8ac110afd3ab":{
      "scriptId":"u48",
      "9769e695b0664441b3ccd5fbff65efea":{
        "scriptId":"u49"},
      "0513e769e9d247dcad8d4b622b25b6ae":{
        "scriptId":"u50"},
      "7fc383c5928e49879a99dc4d9df850ae":{
        "scriptId":"u51"},
      "dde9df61cfeb4ad0b61066271a6d78ad":{
        "scriptId":"u52"},
      "8dc21472bed343a3aef07d5ca3ec1639":{
        "scriptId":"u53"},
      "b71ae81389e54486818e6630092762e8":{
        "scriptId":"u54"},
      "c95221fca89e45be83003b35dbef975d":{
        "scriptId":"u55"},
      "e8b8f022d802460e81c3242754b4631b":{
        "scriptId":"u56"},
      "57944770132240ff89cbea05872a77de":{
        "scriptId":"u57"},
      "cb28593ac22e4ff982b158f27a2b81af":{
        "scriptId":"u58"},
      "68c1f570ff814e418efd898b1f5a29aa":{
        "scriptId":"u59"},
      "f9eae22708664bd780e699248735f154":{
        "scriptId":"u60"},
      "d7d5f6bf4eb94b728c3cd1c2ca7b230d":{
        "scriptId":"u61"},
      "c0e451649a8443e6b1d18c009d17b970":{
        "scriptId":"u62"},
      "604e76edfd1f4bc19d41c745717c608b":{
        "scriptId":"u63"},
      "3f060a28aabf42f0bc66baa1730d2dd1":{
        "scriptId":"u64"},
      "95856e8d4e144148beb2044bf7442380":{
        "scriptId":"u65"}},
    "2642768fcda8441a8935b12c59c1592b":{
      "scriptId":"u66",
      "288ab1dc513d4d93aa14fe7c5f12cb0e":{
        "scriptId":"u67"},
      "11c910fab7bd4dd2afd5b9891a0bd868":{
        "scriptId":"u68"},
      "086570bf076446d99e2f75e95782f03d":{
        "scriptId":"u69"},
      "7f3f0f17c212483eac523909f62362b1":{
        "scriptId":"u70"}},
    "689b31528e094de39ef98cb2f30da3de":{
      "scriptId":"u71"},
    "991050360c8646ebb245994aed8be9c5":{
      "scriptId":"u72"},
    "97f36c4899c24719af3a948a775ca7d1":{
      "scriptId":"u73"},
    "1c3b4ec986c14db28b8aeaec889ca1de":{
      "scriptId":"u74"},
    "a0a7c79a82eb4b8d910ed08ee51babbc":{
      "scriptId":"u75"},
    "7a3c1ef902284b5d9d12648d108c2e05":{
      "scriptId":"u76"},
    "299f6b6ad49340538b8d5bbe05231f8a":{
      "scriptId":"u77"},
    "3da813215a594fe58ec5ddd37caf7747":{
      "scriptId":"u78"}}});