$axure.loadCurrentPage({
  "url":"曾經開登的工作.html",
  "generationDate":new Date(1404292442076.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"d5d6f54bae324673a28ae64e1d6b497c",
    "type":"Axure:Page",
    "name":"曾經開登的工作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0967652638564fa09ebabfee3692aa4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":969}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e5ccb42ff5a4bd59e7ee19cff10dd26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":969}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/曾經開登的工作/u0.png"}},
{
          "id":"2b5ff37de5b54ad6bab307a1458e931c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":410,
              "y":170},
            "size":{
              "width":150,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7e5f3a6df04aa3844ca1232b633d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":410,
                  "y":170},
                "size":{
                  "width":150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bc4eb63b52e46de930c9ce84b2b18cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":160,
              "y":212},
            "size":{
              "width":240,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a222b95d52504fe897d1ad500026d960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":160,
                  "y":212},
                "size":{
                  "width":240,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/曾經開登的工作/u4.png"}},
{
          "id":"39124e92e215447cb8abd9eeb519107e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome Regular', 'FontAwesome'",
            "fontSize":"36px",
            "baseStyle":"acf17f55de514228870a79e6ef16480f",
            "location":{
              "x":348,
              "y":249},
            "size":{
              "width":28,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c826d0784e04214bc2682cd9f0091e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome Regular', 'FontAwesome'",
                "fontSize":"36px",
                "baseStyle":"acf17f55de514228870a79e6ef16480f",
                "location":{
                  "x":348,
                  "y":249},
                "size":{
                  "width":28,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e486357aec2d4644a640f558063ab044",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":235},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"facd924dc4be4e7d8b80da7d6dd3b610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":235},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"096cf59ba17d4416af794f8a2e4cffb2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":23}},
          "adaptiveStyles":{
},
          "masterId":"96e31ac88e3944cf843d8f845f224998"},
{
          "id":"f1a4eee2c92b42a6a31d9b9f0285ac48",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1680,
              "y":17}},
          "adaptiveStyles":{
},
          "masterId":"d1a1dfa27ac24ff2a583a261fc97d904"},
{
          "id":"db5be2d82c434af9bd7b2b53342f8ed5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1524,
              "y":17}},
          "adaptiveStyles":{
},
          "masterId":"d94c7ba1eaa34714a5d6253dffbe242f"},
{
          "id":"49e51dc6fcce440f881fc14da35b809d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b221782d8d40429b3a64a836de92a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b5d9179029042b8b6d0c43e3ee081d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682b0557deef41f6b71e4b4635e91e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a3bd09d1ac416a8d73d85fa9d938b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99a67730b8794b0590527b2b343f2574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d09041b2c4c2452d912bdec0b240a9f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a6d40823be64c2d8d846f05c5166a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "96e31ac88e3944cf843d8f845f224998":{
      "packageId":"96e31ac88e3944cf843d8f845f224998",
      "type":"Axure:Master",
      "name":"dropdown",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"506f205c4d3f45b4a8d8879d40c585c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":117,
                "y":0},
              "size":{
                "width":170,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9b048d4c0424257a86f9053565fae84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":117,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44d2cae74264fe28efc5a9f011db65c",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":63},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"0ac610d031604d3e8252ebd82275eec3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b2490259cfb24a27937c8cc947bca228",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":102},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"17d97940863d453493d1773f25937fa8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":102},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 個人設定 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"個人設定.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"73dd3af138be44458bd25a2634764d55",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afb506fe892a47528ea57c3d3074e449",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"1a6249c0920944ceb89ae7e1be69ce09",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":141},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e45023e673d24bcda3e25c34b974ecef",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":141},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open TeleWork首頁 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"telework__.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7e4f70b8597e4e87b9a74652345d9ede",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":24},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7c6bb4ed82e4d73b9ed1dc1cf37732b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":24},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 遠距工作者登入後(找案件) in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"遠距工作者登入後_找案件_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db4e0239fc24aa5838f7a781f489e0f",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"18px",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099CC,
                        "opacity":1},
                      "location":{
                        "x":70,
                        "y":75},
                      "size":{
                        "width":170,
                        "height":36},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"26d3c97b49b9491e915ab197141698fb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"18px",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099CC,
                            "opacity":1},
                          "location":{
                            "x":70,
                            "y":75},
                          "size":{
                            "width":170,
                            "height":36},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u135.png"}},
{
                    "id":"5a69b865ebd6452ebabd85af7eedb35b",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":74},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c28622cbcfd4bc198d16cf0651c1dac",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":74},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 雇主登入後 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"雇主登入後.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"61887cf395474173a1dd468a457de938",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":-40,
                "y":50},
              "size":{
                "width":900,
                "height":460},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0571e4ff7de34900acd1a730a6b1eb2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":-40,
                    "y":50},
                  "size":{
                    "width":900,
                    "height":460},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73af37ef2bc548cfb218313275d91d54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":90},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9dc390a6c3e4fe89c75bd55943e8173",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":90},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 遠距工作者登入後(找案件) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"遠距工作者登入後_找案件_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c34866e4049b438ea46fb17ab8c63e6b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":140},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d929f16ffcd4e71bd2f5ca13b0d445f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":140},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 雇主登入後 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"雇主登入後.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d1a1dfa27ac24ff2a583a261fc97d904":{
      "packageId":"d1a1dfa27ac24ff2a583a261fc97d904",
      "type":"Axure:Master",
      "name":"change currency",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9769e695b0664441b3ccd5fbff65efea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":44,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0513e769e9d247dcad8d4b622b25b6ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":0},
                  "size":{
                    "width":44,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["7fc383c5928e49879a99dc4d9df850ae"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/遠距工作者詳細資料/u146.png"}},
{
            "id":"7fc383c5928e49879a99dc4d9df850ae",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":66},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"e234e68ced72465cb1fa9db278729a4e",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"dde9df61cfeb4ad0b61066271a6d78ad",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc21472bed343a3aef07d5ca3ec1639",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"b71ae81389e54486818e6630092762e8",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":30},
                      "size":{
                        "width":287,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c95221fca89e45be83003b35dbef975d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":287,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u151.png"}},
{
                    "id":"e8b8f022d802460e81c3242754b4631b",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":24},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"57944770132240ff89cbea05872a77de",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":24},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cb28593ac22e4ff982b158f27a2b81af",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":58},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"68c1f570ff814e418efd898b1f5a29aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":58},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9eae22708664bd780e699248735f154",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":92},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7d5f6bf4eb94b728c3cd1c2ca7b230d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":92},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c0e451649a8443e6b1d18c009d17b970",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":126},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"604e76edfd1f4bc19d41c745717c608b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":126},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3f060a28aabf42f0bc66baa1730d2dd1",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":160},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"95856e8d4e144148beb2044bf7442380",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":160},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "d94c7ba1eaa34714a5d6253dffbe242f":{
      "packageId":"d94c7ba1eaa34714a5d6253dffbe242f",
      "type":"Axure:Master",
      "name":"newinfo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"288ab1dc513d4d93aa14fe7c5f12cb0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":276,
                "y":0},
              "size":{
                "width":60,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11c910fab7bd4dd2afd5b9891a0bd868",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":276,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle info",
                        "objectsToFades":[{
                            "objectPath":["086570bf076446d99e2f75e95782f03d"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"086570bf076446d99e2f75e95782f03d",
            "label":"info",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":73},
              "size":{
                "width":345,
                "height":142},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3f0f17c212483eac523909f62362b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":false,
                "style":{
                  "location":{
                    "x":0,
                    "y":73},
                  "size":{
                    "width":345,
                    "height":142},
                  "visible":false},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/遠距工作者詳細資料/info_u166.png"}}]}}},
  "objectPaths":{
    "0967652638564fa09ebabfee3692aa4a":{
      "scriptId":"u0"},
    "1e5ccb42ff5a4bd59e7ee19cff10dd26":{
      "scriptId":"u1"},
    "2b5ff37de5b54ad6bab307a1458e931c":{
      "scriptId":"u2"},
    "ab7e5f3a6df04aa3844ca1232b633d11":{
      "scriptId":"u3"},
    "0bc4eb63b52e46de930c9ce84b2b18cd":{
      "scriptId":"u4"},
    "a222b95d52504fe897d1ad500026d960":{
      "scriptId":"u5"},
    "39124e92e215447cb8abd9eeb519107e":{
      "scriptId":"u6"},
    "2c826d0784e04214bc2682cd9f0091e8":{
      "scriptId":"u7"},
    "e486357aec2d4644a640f558063ab044":{
      "scriptId":"u8"},
    "facd924dc4be4e7d8b80da7d6dd3b610":{
      "scriptId":"u9"},
    "096cf59ba17d4416af794f8a2e4cffb2":{
      "scriptId":"u10",
      "506f205c4d3f45b4a8d8879d40c585c1":{
        "scriptId":"u11"},
      "e9b048d4c0424257a86f9053565fae84":{
        "scriptId":"u12"},
      "f44d2cae74264fe28efc5a9f011db65c":{
        "scriptId":"u13"},
      "b2490259cfb24a27937c8cc947bca228":{
        "scriptId":"u14"},
      "17d97940863d453493d1773f25937fa8":{
        "scriptId":"u15"},
      "73dd3af138be44458bd25a2634764d55":{
        "scriptId":"u16"},
      "afb506fe892a47528ea57c3d3074e449":{
        "scriptId":"u17"},
      "1a6249c0920944ceb89ae7e1be69ce09":{
        "scriptId":"u18"},
      "e45023e673d24bcda3e25c34b974ecef":{
        "scriptId":"u19"},
      "7e4f70b8597e4e87b9a74652345d9ede":{
        "scriptId":"u20"},
      "e7c6bb4ed82e4d73b9ed1dc1cf37732b":{
        "scriptId":"u21"},
      "1db4e0239fc24aa5838f7a781f489e0f":{
        "scriptId":"u22"},
      "26d3c97b49b9491e915ab197141698fb":{
        "scriptId":"u23"},
      "5a69b865ebd6452ebabd85af7eedb35b":{
        "scriptId":"u24"},
      "1c28622cbcfd4bc198d16cf0651c1dac":{
        "scriptId":"u25"},
      "61887cf395474173a1dd468a457de938":{
        "scriptId":"u26"},
      "0571e4ff7de34900acd1a730a6b1eb2e":{
        "scriptId":"u27"},
      "73af37ef2bc548cfb218313275d91d54":{
        "scriptId":"u28"},
      "f9dc390a6c3e4fe89c75bd55943e8173":{
        "scriptId":"u29"},
      "c34866e4049b438ea46fb17ab8c63e6b":{
        "scriptId":"u30"},
      "3d929f16ffcd4e71bd2f5ca13b0d445f":{
        "scriptId":"u31"}},
    "f1a4eee2c92b42a6a31d9b9f0285ac48":{
      "scriptId":"u32",
      "9769e695b0664441b3ccd5fbff65efea":{
        "scriptId":"u33"},
      "0513e769e9d247dcad8d4b622b25b6ae":{
        "scriptId":"u34"},
      "7fc383c5928e49879a99dc4d9df850ae":{
        "scriptId":"u35"},
      "dde9df61cfeb4ad0b61066271a6d78ad":{
        "scriptId":"u36"},
      "8dc21472bed343a3aef07d5ca3ec1639":{
        "scriptId":"u37"},
      "b71ae81389e54486818e6630092762e8":{
        "scriptId":"u38"},
      "c95221fca89e45be83003b35dbef975d":{
        "scriptId":"u39"},
      "e8b8f022d802460e81c3242754b4631b":{
        "scriptId":"u40"},
      "57944770132240ff89cbea05872a77de":{
        "scriptId":"u41"},
      "cb28593ac22e4ff982b158f27a2b81af":{
        "scriptId":"u42"},
      "68c1f570ff814e418efd898b1f5a29aa":{
        "scriptId":"u43"},
      "f9eae22708664bd780e699248735f154":{
        "scriptId":"u44"},
      "d7d5f6bf4eb94b728c3cd1c2ca7b230d":{
        "scriptId":"u45"},
      "c0e451649a8443e6b1d18c009d17b970":{
        "scriptId":"u46"},
      "604e76edfd1f4bc19d41c745717c608b":{
        "scriptId":"u47"},
      "3f060a28aabf42f0bc66baa1730d2dd1":{
        "scriptId":"u48"},
      "95856e8d4e144148beb2044bf7442380":{
        "scriptId":"u49"}},
    "db5be2d82c434af9bd7b2b53342f8ed5":{
      "scriptId":"u50",
      "288ab1dc513d4d93aa14fe7c5f12cb0e":{
        "scriptId":"u51"},
      "11c910fab7bd4dd2afd5b9891a0bd868":{
        "scriptId":"u52"},
      "086570bf076446d99e2f75e95782f03d":{
        "scriptId":"u53"},
      "7f3f0f17c212483eac523909f62362b1":{
        "scriptId":"u54"}},
    "49e51dc6fcce440f881fc14da35b809d":{
      "scriptId":"u55"},
    "d9b221782d8d40429b3a64a836de92a9":{
      "scriptId":"u56"},
    "8b5d9179029042b8b6d0c43e3ee081d4":{
      "scriptId":"u57"},
    "682b0557deef41f6b71e4b4635e91e6a":{
      "scriptId":"u58"},
    "57a3bd09d1ac416a8d73d85fa9d938b0":{
      "scriptId":"u59"},
    "99a67730b8794b0590527b2b343f2574":{
      "scriptId":"u60"},
    "d09041b2c4c2452d912bdec0b240a9f8":{
      "scriptId":"u61"},
    "0a6d40823be64c2d8d846f05c5166a84":{
      "scriptId":"u62"}}});