$axure.loadCurrentPage({
  "url":"已經結束的案件合約.html",
  "generationDate":new Date(1404292438644.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"155a2e59dff448d5bc106c410b017753",
    "type":"Axure:Page",
    "name":"已經結束的案件合約",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1d34a79918e0492a861a801245fb4928",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2048,
              "height":119},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f456cea2baa4de090a96a74e93fbcea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2048,
                  "height":119},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u0.png"}},
{
          "id":"9612b89753c34923b8c29e9332de50a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":2048,
              "height":259},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766dedb3dfc5411192b6b39ce627095d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":843},
                "size":{
                  "width":2048,
                  "height":259},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u2.png"}},
{
          "id":"80a4a189f14342afb6441b891258fb0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1920,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d9351539f84f928257672a792b5e03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":1920,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u4.png"}},
{
          "id":"21786accb54e4b3a8ba2aca332471452",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":151},
            "size":{
              "width":1920,
              "height":669},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df1edc26370a4e29ace9246d0bc77c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":151},
                "size":{
                  "width":1920,
                  "height":669},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u6.png"}},
{
          "id":"e0d022425a034ad192f3c4bfc6bcb6f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":820},
            "size":{
              "width":1920,
              "height":45},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d3885a8cfb840e4abd41b6e26617a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":820},
                "size":{
                  "width":1920,
                  "height":45},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視傳送的案件合約/u8.png"}},
{
          "id":"70778cd0ac40419999a31fd338919b84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":88},
            "size":{
              "width":70,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c74c77b5c6594072ac40b084ca114289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":88},
                "size":{
                  "width":70,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9496f810cd5425d946b2fa2ea95cbfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":476,
              "y":157},
            "size":{
              "width":200,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b91266bdf35644489d55cfd228e01d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":476,
                  "y":157},
                "size":{
                  "width":200,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u22.png"}},
{
          "id":"5102266271fd4a3db08eb3c33aa6eaf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":476,
              "y":220},
            "size":{
              "width":134,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7718b91e83d24342af2a65cf4bcc5302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":220},
                "size":{
                  "width":134,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/已經結束的案件合約/u14.png"}},
{
          "id":"556124282c084c78a703d86c4bff67e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":268},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb11e111c184e67b435f220b5b62597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":268},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"b8e95ec330c34008a153bbf78b852e44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":317},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c14183484054ceea7f50b5bedb837b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":317},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"de996487aaa44ac48c37bccd07ccee3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":366},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5c2c9d5b1984cf79aeedb40e54d45e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":366},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"a4cf89205e314548884114df9b0d963d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":415},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6642c83c127a47aeacfdb8b6e04c0568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":415},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"3b6758dbb2304bd895768cbb3f4be803",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":463},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e1dbd090bea4e13af0c912b4dd08fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":463},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"8053b27294ba40cf934f63683df99282",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":512},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e7709cb9a4452cba42663668169b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":512},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"1cfbe5259c8544f2bd479d9a9fbbd73b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":501,
              "y":561},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaf11f140d6643f69d466d938aac0610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":501,
                  "y":561},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"27472eade1814a9e8d99efca3b8ae93d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":268},
            "size":{
              "width":201,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e61605f0298b41bf8184a8921a3f5cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":268},
                "size":{
                  "width":201,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u40.png"}},
{
          "id":"4ee6be41e5c344818f09b06c156d4f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":318},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe204b34c5d24d87b8fe853393d10d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":318},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"e166a28d5e9c44a891483f99de3e540c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":366},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e1b6d179d344f03ac2d768e86f9c1eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":366},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"bffbe8e690184dc9ab7b875a57677cc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":416},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c21b8bc0c0664c35a5c71ec659f0b049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":416},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"509da9f17d39434ea65b5ad30f5aedee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":464},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74adaa2a392e4337b0ca8977c6f8ba1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":464},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"c05fe5b0d07d49b7965025e0cbad5598",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":889,
              "y":512},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"210e532a11fb4b7db6537e7b67b25037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":889,
                  "y":512},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u26.png"}},
{
          "id":"1fdce205bbfa4020979f0c56133df09b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1137,
              "y":257},
            "size":{
              "width":310,
              "height":391},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9ef3657e104cb891f9024363046a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1137,
                  "y":257},
                "size":{
                  "width":310,
                  "height":391},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u54.png"}},
{
          "id":"8967cc7b6d984a348cb74dc04dc65d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":298},
            "size":{
              "width":200,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd26b93bc5994662935ca1b2e5b61713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":298},
                "size":{
                  "width":200,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29e441524d5f4f71af9ec3ce5ac54a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":385},
            "size":{
              "width":200,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6efcc731d524e53a929bc4e06ab0349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":385},
                "size":{
                  "width":200,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"589aaef39d384646980b95973f264bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1242,
              "y":268},
            "size":{
              "width":98,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abdbd2a6e6b14ac78e11ea23b030703f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1242,
                  "y":268},
                "size":{
                  "width":98,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ab10b77ea4341028a2e2bf975e6248e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":496},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/申請案件-檢視案件合約/u62_line.png"}},
{
          "id":"c9368753a8f8488f8fb62f38707bc498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1242,
              "y":518},
            "size":{
              "width":98,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afff92ec57e148f084b024920df9d759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1242,
                  "y":518},
                "size":{
                  "width":98,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fb32f25116141938a4f04f03a12078a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1151,
              "y":414},
            "size":{
              "width":52,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f96c847dec3545c0a3f459b6e44d6a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1151,
                  "y":414},
                "size":{
                  "width":52,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u65.png"}},
{
          "id":"936c5821cf9941d2908a82957d672a5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1151,
              "y":327},
            "size":{
              "width":52,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cb89df6aa44df18e02bc8eba63f37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1151,
                  "y":327},
                "size":{
                  "width":52,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u67.png"}},
{
          "id":"fb6c1c06ae58495cb6a3f92b8e1ff8de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":1213,
              "y":338},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59ac995af80f4b07b35e42782fefc23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":1213,
                  "y":338},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2d9f1b19b21413e9a1e14125f8f15c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":1213,
              "y":424},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9f507aa348a4373afb13bb1a3321e35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":1213,
                  "y":424},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d236379989234bf8a51e7b8b7855cb7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":561},
            "size":{
              "width":279,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b47628b0012a4de19fdf093537bda343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":561},
                "size":{
                  "width":279,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f08c8d5173ed46109dc6ed684194d101",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":258},
            "size":{
              "width":644,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/申請案件-檢視案件合約/u75_line.png"}},
{
          "id":"3d98d435c6d14f7cb7bd194d6df3f15e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":476,
              "y":196},
            "size":{
              "width":217,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"421e87b2380a46f9b36fca417626a73c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":476,
                  "y":196},
                "size":{
                  "width":217,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df1d2fd12bfc4780ac019daf6878a22c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1151,
              "y":566},
            "size":{
              "width":127,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2761ac4ae71447258d886e325d561b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1151,
                  "y":566},
                "size":{
                  "width":127,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視案件申請的詳細資料 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視案件申請的詳細資料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b55a77524c9488a9d5015486857a79d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":983,
              "y":219},
            "size":{
              "width":137,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7daee33d1594969bddd811d2b47dc5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":983,
                  "y":219},
                "size":{
                  "width":137,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/已經結束的案件合約/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1d34a79918e0492a861a801245fb4928":{
      "scriptId":"u0"},
    "1f456cea2baa4de090a96a74e93fbcea":{
      "scriptId":"u1"},
    "9612b89753c34923b8c29e9332de50a9":{
      "scriptId":"u2"},
    "766dedb3dfc5411192b6b39ce627095d":{
      "scriptId":"u3"},
    "80a4a189f14342afb6441b891258fb0f":{
      "scriptId":"u4"},
    "47d9351539f84f928257672a792b5e03":{
      "scriptId":"u5"},
    "21786accb54e4b3a8ba2aca332471452":{
      "scriptId":"u6"},
    "df1edc26370a4e29ace9246d0bc77c58":{
      "scriptId":"u7"},
    "e0d022425a034ad192f3c4bfc6bcb6f2":{
      "scriptId":"u8"},
    "8d3885a8cfb840e4abd41b6e26617a6c":{
      "scriptId":"u9"},
    "70778cd0ac40419999a31fd338919b84":{
      "scriptId":"u10"},
    "c74c77b5c6594072ac40b084ca114289":{
      "scriptId":"u11"},
    "d9496f810cd5425d946b2fa2ea95cbfe":{
      "scriptId":"u12"},
    "b91266bdf35644489d55cfd228e01d7c":{
      "scriptId":"u13"},
    "5102266271fd4a3db08eb3c33aa6eaf9":{
      "scriptId":"u14"},
    "7718b91e83d24342af2a65cf4bcc5302":{
      "scriptId":"u15"},
    "556124282c084c78a703d86c4bff67e8":{
      "scriptId":"u16"},
    "beb11e111c184e67b435f220b5b62597":{
      "scriptId":"u17"},
    "b8e95ec330c34008a153bbf78b852e44":{
      "scriptId":"u18"},
    "8c14183484054ceea7f50b5bedb837b7":{
      "scriptId":"u19"},
    "de996487aaa44ac48c37bccd07ccee3f":{
      "scriptId":"u20"},
    "c5c2c9d5b1984cf79aeedb40e54d45e3":{
      "scriptId":"u21"},
    "a4cf89205e314548884114df9b0d963d":{
      "scriptId":"u22"},
    "6642c83c127a47aeacfdb8b6e04c0568":{
      "scriptId":"u23"},
    "3b6758dbb2304bd895768cbb3f4be803":{
      "scriptId":"u24"},
    "3e1dbd090bea4e13af0c912b4dd08fb1":{
      "scriptId":"u25"},
    "8053b27294ba40cf934f63683df99282":{
      "scriptId":"u26"},
    "83e7709cb9a4452cba42663668169b10":{
      "scriptId":"u27"},
    "1cfbe5259c8544f2bd479d9a9fbbd73b":{
      "scriptId":"u28"},
    "eaf11f140d6643f69d466d938aac0610":{
      "scriptId":"u29"},
    "27472eade1814a9e8d99efca3b8ae93d":{
      "scriptId":"u30"},
    "e61605f0298b41bf8184a8921a3f5cf9":{
      "scriptId":"u31"},
    "4ee6be41e5c344818f09b06c156d4f52":{
      "scriptId":"u32"},
    "fe204b34c5d24d87b8fe853393d10d68":{
      "scriptId":"u33"},
    "e166a28d5e9c44a891483f99de3e540c":{
      "scriptId":"u34"},
    "5e1b6d179d344f03ac2d768e86f9c1eb":{
      "scriptId":"u35"},
    "bffbe8e690184dc9ab7b875a57677cc6":{
      "scriptId":"u36"},
    "c21b8bc0c0664c35a5c71ec659f0b049":{
      "scriptId":"u37"},
    "509da9f17d39434ea65b5ad30f5aedee":{
      "scriptId":"u38"},
    "74adaa2a392e4337b0ca8977c6f8ba1d":{
      "scriptId":"u39"},
    "c05fe5b0d07d49b7965025e0cbad5598":{
      "scriptId":"u40"},
    "210e532a11fb4b7db6537e7b67b25037":{
      "scriptId":"u41"},
    "1fdce205bbfa4020979f0c56133df09b":{
      "scriptId":"u42"},
    "5e9ef3657e104cb891f9024363046a34":{
      "scriptId":"u43"},
    "8967cc7b6d984a348cb74dc04dc65d5e":{
      "scriptId":"u44"},
    "cd26b93bc5994662935ca1b2e5b61713":{
      "scriptId":"u45"},
    "29e441524d5f4f71af9ec3ce5ac54a39":{
      "scriptId":"u46"},
    "c6efcc731d524e53a929bc4e06ab0349":{
      "scriptId":"u47"},
    "589aaef39d384646980b95973f264bf6":{
      "scriptId":"u48"},
    "abdbd2a6e6b14ac78e11ea23b030703f":{
      "scriptId":"u49"},
    "5ab10b77ea4341028a2e2bf975e6248e":{
      "scriptId":"u50"},
    "c9368753a8f8488f8fb62f38707bc498":{
      "scriptId":"u51"},
    "afff92ec57e148f084b024920df9d759":{
      "scriptId":"u52"},
    "6fb32f25116141938a4f04f03a12078a":{
      "scriptId":"u53"},
    "f96c847dec3545c0a3f459b6e44d6a87":{
      "scriptId":"u54"},
    "936c5821cf9941d2908a82957d672a5a":{
      "scriptId":"u55"},
    "d1cb89df6aa44df18e02bc8eba63f37f":{
      "scriptId":"u56"},
    "fb6c1c06ae58495cb6a3f92b8e1ff8de":{
      "scriptId":"u57"},
    "59ac995af80f4b07b35e42782fefc23d":{
      "scriptId":"u58"},
    "c2d9f1b19b21413e9a1e14125f8f15c5":{
      "scriptId":"u59"},
    "d9f507aa348a4373afb13bb1a3321e35":{
      "scriptId":"u60"},
    "d236379989234bf8a51e7b8b7855cb7e":{
      "scriptId":"u61"},
    "b47628b0012a4de19fdf093537bda343":{
      "scriptId":"u62"},
    "f08c8d5173ed46109dc6ed684194d101":{
      "scriptId":"u63"},
    "3d98d435c6d14f7cb7bd194d6df3f15e":{
      "scriptId":"u64"},
    "421e87b2380a46f9b36fca417626a73c":{
      "scriptId":"u65"},
    "df1d2fd12bfc4780ac019daf6878a22c":{
      "scriptId":"u66"},
    "2761ac4ae71447258d886e325d561b2b":{
      "scriptId":"u67"},
    "9b55a77524c9488a9d5015486857a79d":{
      "scriptId":"u68"},
    "d7daee33d1594969bddd811d2b47dc5b":{
      "scriptId":"u69"}}});