$axure.loadCurrentPage({
  "url":"已經結束無法申請的案件詳細資料.html",
  "generationDate":new Date(1404292438786.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"c67c594e9b6348ce8da90191a84a4348",
    "type":"Axure:Page",
    "name":"已經結束無法申請的案件詳細資料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1093e6dd739948e8a16b74f6ab02f0bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b342a428002943f3b37c1bbf15178432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u0.png"}},
{
          "id":"0e939bfa17324e49980fced0d707ea91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":470,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e66366b6b12542068945ed4ae9f6c4d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":470,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視申請的案件詳細資料 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視申請的案件詳細資料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b726d00dbc475494d7cd83ed6e0e48",
          "label":"save",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":231},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["a9b726d00dbc475494d7cd83ed6e0e48"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"6c3f00011ebe4a1eb36034dc818388cd",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ee17cc8b3d6a4a1dbd9a958faf28f978",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"a9b726d00dbc475494d7cd83ed6e0e48",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d5a0b9d2f964403a1d566ec106e6f33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a9b726d00dbc475494d7cd83ed6e0e48",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e15cc22d9d274312b4af60b6e7bb7786",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f5b611d2bca64256a16deb347e6df08c",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"a9b726d00dbc475494d7cd83ed6e0e48",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83d6896f633d4ba1b133d46203478ba8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a9b726d00dbc475494d7cd83ed6e0e48",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"158abeaf54174398ab80235c354f9183",
          "label":"apply",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":229},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["158abeaf54174398ab80235c354f9183"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c3a0d05ac46a4ddaaffe90c5140be6aa",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ecc4b13d16d49e2b46c92b1d8f77c51",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"158abeaf54174398ab80235c354f9183",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef6188a5cdb64ee4ad28f27afe336874",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"158abeaf54174398ab80235c354f9183",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"1ebb10e56c5640a6991ee8105da822c5",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"318f194cabbf4f6a9bb9635697ba155b",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"158abeaf54174398ab80235c354f9183",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b648b6f9c8964529ba2d10a6bc0b1504",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"158abeaf54174398ab80235c354f9183",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"58e492f57a0249c398af7fc1a20a38c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1135,
              "y":160},
            "size":{
              "width":285,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3286cae62b654c84bf3b1e9ac11ce8af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1135,
                  "y":160},
                "size":{
                  "width":285,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u18.png"}},
{
          "id":"57a91ab9dc8b4049928a406b8f7bb9a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1380,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5008f654684ab79d4ea60e633da548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1380,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u20.png"}},
{
          "id":"f4047c0807784ecdaad0273ae15507ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1380,
              "y":0},
            "size":{
              "width":51,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9454f4db5a994ce3b74bb3f0db71641d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1380,
                  "y":0},
                "size":{
                  "width":51,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u22.png"}},
{
          "id":"1d6a0a3d652546409fa897bbf7e8aa61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1431,
              "y":0},
            "size":{
              "width":489,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c6ab66de9e4b89b12574e76b513fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1431,
                  "y":0},
                "size":{
                  "width":489,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u24.png"}},
{
          "id":"ba76da2d90dc43dc8981c36a2c4a21ad",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":26}},
          "adaptiveStyles":{
},
          "masterId":"96e31ac88e3944cf843d8f845f224998"},
{
          "id":"cc17d444e30b492abbd0b250480953bb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1680,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d1a1dfa27ac24ff2a583a261fc97d904"},
{
          "id":"4c2b0a1d234443398e058e35ea4719de",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1524,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d94c7ba1eaa34714a5d6253dffbe242f"},
{
          "id":"04b4538c2a67413eb66ea37a238f6cfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":660},
            "size":{
              "width":290,
              "height":290},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e6fb6471704975bfdd00cdb5ef37fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":660},
                "size":{
                  "width":290,
                  "height":290},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視申請的案件詳細資料/u55.png"}},
{
          "id":"9a5a9e8379534388a4cdd3c1c0016a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":476,
              "y":123},
            "size":{
              "width":634,
              "height":50},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd991c7bc17a4a7e9f8d836257ec71b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":123},
                "size":{
                  "width":634,
                  "height":50},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/已經結束無法申請的案件詳細資料/u69.png"}},
{
          "id":"0627144a3aac418faa8fd2f0bb12a1f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC66,
              "opacity":1},
            "location":{
              "x":470,
              "y":216},
            "size":{
              "width":640,
              "height":47},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66CC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"563c2bbd3b0a4a638c186e9f96dfe618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC66,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":216},
                "size":{
                  "width":640,
                  "height":47},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請的詳細資料/u75.png"}},
{
          "id":"a90bb24f64ae4ace9df7f0343bb9f689",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":80},
            "size":{
              "width":200,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee36f71b3f645b3853fddf8614e55cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":80},
                "size":{
                  "width":200,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 申請案件-檢視案件合約 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"申請案件-檢視案件合約.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"643f144e29e64e15a2328c6fff5b92c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":402},
            "size":{
              "width":434,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb01d06f840a43dda909f039dd879148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":402},
                "size":{
                  "width":434,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/已經結束無法申請的案件詳細資料/u75.png"}},
{
          "id":"f2a3b4ca912b4179863e742d63ddebca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":630},
            "size":{
              "width":634,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0044d73f724c7b9ed33adcd3601381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":476,
                  "y":630},
                "size":{
                  "width":634,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/已經結束無法申請的案件詳細資料/u77.png"}}]}},
  "masters":{
    "96e31ac88e3944cf843d8f845f224998":{
      "packageId":"96e31ac88e3944cf843d8f845f224998",
      "type":"Axure:Master",
      "name":"dropdown",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"506f205c4d3f45b4a8d8879d40c585c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":117,
                "y":0},
              "size":{
                "width":170,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9b048d4c0424257a86f9053565fae84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":117,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44d2cae74264fe28efc5a9f011db65c",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":63},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"0ac610d031604d3e8252ebd82275eec3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b2490259cfb24a27937c8cc947bca228",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":102},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"17d97940863d453493d1773f25937fa8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":102},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 個人設定 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"個人設定.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"73dd3af138be44458bd25a2634764d55",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afb506fe892a47528ea57c3d3074e449",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"1a6249c0920944ceb89ae7e1be69ce09",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":141},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e45023e673d24bcda3e25c34b974ecef",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":141},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open TeleWork首頁 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"telework__.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7e4f70b8597e4e87b9a74652345d9ede",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":24},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7c6bb4ed82e4d73b9ed1dc1cf37732b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":24},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 遠距工作者登入後(找案件) in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"遠距工作者登入後_找案件_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db4e0239fc24aa5838f7a781f489e0f",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"18px",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099CC,
                        "opacity":1},
                      "location":{
                        "x":70,
                        "y":75},
                      "size":{
                        "width":170,
                        "height":36},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"26d3c97b49b9491e915ab197141698fb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"18px",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099CC,
                            "opacity":1},
                          "location":{
                            "x":70,
                            "y":75},
                          "size":{
                            "width":170,
                            "height":36},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u135.png"}},
{
                    "id":"5a69b865ebd6452ebabd85af7eedb35b",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":74},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c28622cbcfd4bc198d16cf0651c1dac",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":74},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 雇主登入後 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"雇主登入後.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"61887cf395474173a1dd468a457de938",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":-40,
                "y":50},
              "size":{
                "width":900,
                "height":460},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0571e4ff7de34900acd1a730a6b1eb2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":-40,
                    "y":50},
                  "size":{
                    "width":900,
                    "height":460},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73af37ef2bc548cfb218313275d91d54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":90},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9dc390a6c3e4fe89c75bd55943e8173",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":90},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 遠距工作者登入後(找案件) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"遠距工作者登入後_找案件_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c34866e4049b438ea46fb17ab8c63e6b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":140},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d929f16ffcd4e71bd2f5ca13b0d445f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":140},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 雇主登入後 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"雇主登入後.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d1a1dfa27ac24ff2a583a261fc97d904":{
      "packageId":"d1a1dfa27ac24ff2a583a261fc97d904",
      "type":"Axure:Master",
      "name":"change currency",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9769e695b0664441b3ccd5fbff65efea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":44,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0513e769e9d247dcad8d4b622b25b6ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":0},
                  "size":{
                    "width":44,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["7fc383c5928e49879a99dc4d9df850ae"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/遠距工作者詳細資料/u146.png"}},
{
            "id":"7fc383c5928e49879a99dc4d9df850ae",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":66},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"e234e68ced72465cb1fa9db278729a4e",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"dde9df61cfeb4ad0b61066271a6d78ad",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc21472bed343a3aef07d5ca3ec1639",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"b71ae81389e54486818e6630092762e8",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":30},
                      "size":{
                        "width":287,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c95221fca89e45be83003b35dbef975d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":287,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u151.png"}},
{
                    "id":"e8b8f022d802460e81c3242754b4631b",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":24},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"57944770132240ff89cbea05872a77de",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":24},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cb28593ac22e4ff982b158f27a2b81af",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":58},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"68c1f570ff814e418efd898b1f5a29aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":58},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9eae22708664bd780e699248735f154",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":92},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7d5f6bf4eb94b728c3cd1c2ca7b230d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":92},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c0e451649a8443e6b1d18c009d17b970",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":126},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"604e76edfd1f4bc19d41c745717c608b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":126},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3f060a28aabf42f0bc66baa1730d2dd1",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":160},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"95856e8d4e144148beb2044bf7442380",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":160},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "d94c7ba1eaa34714a5d6253dffbe242f":{
      "packageId":"d94c7ba1eaa34714a5d6253dffbe242f",
      "type":"Axure:Master",
      "name":"newinfo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"288ab1dc513d4d93aa14fe7c5f12cb0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":276,
                "y":0},
              "size":{
                "width":60,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11c910fab7bd4dd2afd5b9891a0bd868",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":276,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle info",
                        "objectsToFades":[{
                            "objectPath":["086570bf076446d99e2f75e95782f03d"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"086570bf076446d99e2f75e95782f03d",
            "label":"info",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":73},
              "size":{
                "width":345,
                "height":142},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3f0f17c212483eac523909f62362b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":false,
                "style":{
                  "location":{
                    "x":0,
                    "y":73},
                  "size":{
                    "width":345,
                    "height":142},
                  "visible":false},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/遠距工作者詳細資料/info_u166.png"}}]}}},
  "objectPaths":{
    "1093e6dd739948e8a16b74f6ab02f0bd":{
      "scriptId":"u0"},
    "b342a428002943f3b37c1bbf15178432":{
      "scriptId":"u1"},
    "0e939bfa17324e49980fced0d707ea91":{
      "scriptId":"u2"},
    "e66366b6b12542068945ed4ae9f6c4d3":{
      "scriptId":"u3"},
    "a9b726d00dbc475494d7cd83ed6e0e48":{
      "scriptId":"u4"},
    "ee17cc8b3d6a4a1dbd9a958faf28f978":{
      "scriptId":"u5"},
    "7d5a0b9d2f964403a1d566ec106e6f33":{
      "scriptId":"u6"},
    "f5b611d2bca64256a16deb347e6df08c":{
      "scriptId":"u7"},
    "83d6896f633d4ba1b133d46203478ba8":{
      "scriptId":"u8"},
    "158abeaf54174398ab80235c354f9183":{
      "scriptId":"u9"},
    "0ecc4b13d16d49e2b46c92b1d8f77c51":{
      "scriptId":"u10"},
    "ef6188a5cdb64ee4ad28f27afe336874":{
      "scriptId":"u11"},
    "318f194cabbf4f6a9bb9635697ba155b":{
      "scriptId":"u12"},
    "b648b6f9c8964529ba2d10a6bc0b1504":{
      "scriptId":"u13"},
    "58e492f57a0249c398af7fc1a20a38c0":{
      "scriptId":"u14"},
    "3286cae62b654c84bf3b1e9ac11ce8af":{
      "scriptId":"u15"},
    "57a91ab9dc8b4049928a406b8f7bb9a5":{
      "scriptId":"u16"},
    "6f5008f654684ab79d4ea60e633da548":{
      "scriptId":"u17"},
    "f4047c0807784ecdaad0273ae15507ba":{
      "scriptId":"u18"},
    "9454f4db5a994ce3b74bb3f0db71641d":{
      "scriptId":"u19"},
    "1d6a0a3d652546409fa897bbf7e8aa61":{
      "scriptId":"u20"},
    "d8c6ab66de9e4b89b12574e76b513fe1":{
      "scriptId":"u21"},
    "ba76da2d90dc43dc8981c36a2c4a21ad":{
      "scriptId":"u22",
      "506f205c4d3f45b4a8d8879d40c585c1":{
        "scriptId":"u23"},
      "e9b048d4c0424257a86f9053565fae84":{
        "scriptId":"u24"},
      "f44d2cae74264fe28efc5a9f011db65c":{
        "scriptId":"u25"},
      "b2490259cfb24a27937c8cc947bca228":{
        "scriptId":"u26"},
      "17d97940863d453493d1773f25937fa8":{
        "scriptId":"u27"},
      "73dd3af138be44458bd25a2634764d55":{
        "scriptId":"u28"},
      "afb506fe892a47528ea57c3d3074e449":{
        "scriptId":"u29"},
      "1a6249c0920944ceb89ae7e1be69ce09":{
        "scriptId":"u30"},
      "e45023e673d24bcda3e25c34b974ecef":{
        "scriptId":"u31"},
      "7e4f70b8597e4e87b9a74652345d9ede":{
        "scriptId":"u32"},
      "e7c6bb4ed82e4d73b9ed1dc1cf37732b":{
        "scriptId":"u33"},
      "1db4e0239fc24aa5838f7a781f489e0f":{
        "scriptId":"u34"},
      "26d3c97b49b9491e915ab197141698fb":{
        "scriptId":"u35"},
      "5a69b865ebd6452ebabd85af7eedb35b":{
        "scriptId":"u36"},
      "1c28622cbcfd4bc198d16cf0651c1dac":{
        "scriptId":"u37"},
      "61887cf395474173a1dd468a457de938":{
        "scriptId":"u38"},
      "0571e4ff7de34900acd1a730a6b1eb2e":{
        "scriptId":"u39"},
      "73af37ef2bc548cfb218313275d91d54":{
        "scriptId":"u40"},
      "f9dc390a6c3e4fe89c75bd55943e8173":{
        "scriptId":"u41"},
      "c34866e4049b438ea46fb17ab8c63e6b":{
        "scriptId":"u42"},
      "3d929f16ffcd4e71bd2f5ca13b0d445f":{
        "scriptId":"u43"}},
    "cc17d444e30b492abbd0b250480953bb":{
      "scriptId":"u44",
      "9769e695b0664441b3ccd5fbff65efea":{
        "scriptId":"u45"},
      "0513e769e9d247dcad8d4b622b25b6ae":{
        "scriptId":"u46"},
      "7fc383c5928e49879a99dc4d9df850ae":{
        "scriptId":"u47"},
      "dde9df61cfeb4ad0b61066271a6d78ad":{
        "scriptId":"u48"},
      "8dc21472bed343a3aef07d5ca3ec1639":{
        "scriptId":"u49"},
      "b71ae81389e54486818e6630092762e8":{
        "scriptId":"u50"},
      "c95221fca89e45be83003b35dbef975d":{
        "scriptId":"u51"},
      "e8b8f022d802460e81c3242754b4631b":{
        "scriptId":"u52"},
      "57944770132240ff89cbea05872a77de":{
        "scriptId":"u53"},
      "cb28593ac22e4ff982b158f27a2b81af":{
        "scriptId":"u54"},
      "68c1f570ff814e418efd898b1f5a29aa":{
        "scriptId":"u55"},
      "f9eae22708664bd780e699248735f154":{
        "scriptId":"u56"},
      "d7d5f6bf4eb94b728c3cd1c2ca7b230d":{
        "scriptId":"u57"},
      "c0e451649a8443e6b1d18c009d17b970":{
        "scriptId":"u58"},
      "604e76edfd1f4bc19d41c745717c608b":{
        "scriptId":"u59"},
      "3f060a28aabf42f0bc66baa1730d2dd1":{
        "scriptId":"u60"},
      "95856e8d4e144148beb2044bf7442380":{
        "scriptId":"u61"}},
    "4c2b0a1d234443398e058e35ea4719de":{
      "scriptId":"u62",
      "288ab1dc513d4d93aa14fe7c5f12cb0e":{
        "scriptId":"u63"},
      "11c910fab7bd4dd2afd5b9891a0bd868":{
        "scriptId":"u64"},
      "086570bf076446d99e2f75e95782f03d":{
        "scriptId":"u65"},
      "7f3f0f17c212483eac523909f62362b1":{
        "scriptId":"u66"}},
    "04b4538c2a67413eb66ea37a238f6cfb":{
      "scriptId":"u67"},
    "70e6fb6471704975bfdd00cdb5ef37fe":{
      "scriptId":"u68"},
    "9a5a9e8379534388a4cdd3c1c0016a57":{
      "scriptId":"u69"},
    "cd991c7bc17a4a7e9f8d836257ec71b0":{
      "scriptId":"u70"},
    "0627144a3aac418faa8fd2f0bb12a1f6":{
      "scriptId":"u71"},
    "563c2bbd3b0a4a638c186e9f96dfe618":{
      "scriptId":"u72"},
    "a90bb24f64ae4ace9df7f0343bb9f689":{
      "scriptId":"u73"},
    "8ee36f71b3f645b3853fddf8614e55cc":{
      "scriptId":"u74"},
    "643f144e29e64e15a2328c6fff5b92c7":{
      "scriptId":"u75"},
    "eb01d06f840a43dda909f039dd879148":{
      "scriptId":"u76"},
    "f2a3b4ca912b4179863e742d63ddebca":{
      "scriptId":"u77"},
    "ce0044d73f724c7b9ed33adcd3601381":{
      "scriptId":"u78"}}});