$axure.loadCurrentPage({
  "url":"檢視案件申請的詳細資料.html",
  "generationDate":new Date(1404292438554.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"dfe1a924aeb546abb9730dbcb55c882b",
    "type":"Axure:Page",
    "name":"檢視案件申請的詳細資料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"893807cfbe25418ea3956dd49a061366",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d815b682d54da2936749bedc5be5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u0.png"}},
{
          "id":"15401ce1f59346348dfdafccfbc29b2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":470,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62291c47af084ba190999eb786ebccc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":470,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視申請的案件詳細資料 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視申請的案件詳細資料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a53af35470214ace906b5d7b53003675",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":680,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eceb128a14e48ecb97ea00bffb20a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":680,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 投標者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"投標者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ebbe97e3b7a4baaac28640c37732e00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":900,
              "y":410},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"314b7fc2688e4c2681c7673475650b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":900,
                  "y":410},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主評價 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主評價.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b4f829b7e574218b93463f8e57776b2",
          "label":"save",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":231},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["9b4f829b7e574218b93463f8e57776b2"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"60772daa96dd447298147c2cd4a498dd",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2e1c3cbf210f4b8cbe3b4dd0af81690a",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"9b4f829b7e574218b93463f8e57776b2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae5196f09b724f37a707e2e5cb4d23f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b4f829b7e574218b93463f8e57776b2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"faf1c44fbf134035bb92410aa3e99bb2",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2a120a52e65a4342b38fab867681894b",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"9b4f829b7e574218b93463f8e57776b2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD2322D},
                    "size":{
                      "width":62,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5cad7730cfd416d8b71c48ececefe71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b4f829b7e574218b93463f8e57776b2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD2322D},
                        "size":{
                          "width":62,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/搜尋案件/dropdown_button_u5.png",
                    "selected~":"images/搜尋案件/dropdown_button_u5_selected.png",
                    "mouseOver~":"images/搜尋案件/dropdown_button_u5_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"df51b1ea1df04f29be40b0349a126651",
          "label":"apply",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":229},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set This to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["df51b1ea1df04f29be40b0349a126651"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3bb45a1e94154b59942f9f499761aea6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b074eb5172044199bea2d5663bc14ebd",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"df51b1ea1df04f29be40b0349a126651",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7641440193f54c2682fb1c5eaf7d6ef5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df51b1ea1df04f29be40b0349a126651",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ee89592c271d4ba28a59f9ce72780ce4",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6c8a420414f74f19adc1f20fa67d8aa3",
                  "label":"Dropdown button",
                  "parentDynamicPanel":"df51b1ea1df04f29be40b0349a126651",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "selected":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0AD4E},
                    "size":{
                      "width":63,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0421fa1a8c404929b2d1a034fe3f3aed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df51b1ea1df04f29be40b0349a126651",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "selected":{
}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0AD4E},
                        "size":{
                          "width":63,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD9D9D9},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/案件詳細資料/dropdown_button_u14.png",
                    "selected~":"images/案件詳細資料/dropdown_button_u14_selected.png",
                    "mouseOver~":"images/案件詳細資料/dropdown_button_u14_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"bc34ef8fe91d4a4aaae3ff511db390bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1135,
              "y":160},
            "size":{
              "width":285,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79b999f5dad94b598b904250f57965ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1135,
                  "y":160},
                "size":{
                  "width":285,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u18.png"}},
{
          "id":"41e220a57adc44cdbc34fd17f4b249eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1380,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f6d440b79449b49f5ce41df91790f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1380,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u20.png"}},
{
          "id":"a527f29fb6204f4ab1bf94d31b63d64c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1380,
              "y":0},
            "size":{
              "width":51,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ebf34ab81af425286ea3b5798a50629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1380,
                  "y":0},
                "size":{
                  "width":51,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u22.png"}},
{
          "id":"5359b28085b8428b9c20a06a94b69343",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1431,
              "y":0},
            "size":{
              "width":489,
              "height":88},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b962dcda274493fa5efd800dcc554a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1431,
                  "y":0},
                "size":{
                  "width":489,
                  "height":88},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/案件詳細資料/u24.png"}},
{
          "id":"0b3e9aee179e4281992a3f39e80bcc7f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":26}},
          "adaptiveStyles":{
},
          "masterId":"96e31ac88e3944cf843d8f845f224998"},
{
          "id":"169f55803d354df68cc97924b53451f8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1680,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d1a1dfa27ac24ff2a583a261fc97d904"},
{
          "id":"d898c367cf8749f6829987dbfe331db8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1524,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"d94c7ba1eaa34714a5d6253dffbe242f"},
{
          "id":"8b3dd1f7d8e148f3aa2196056a2a3457",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":660},
            "size":{
              "width":290,
              "height":290},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7250e61abe34eb4bc85e07ab15bc200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":660},
                "size":{
                  "width":290,
                  "height":290},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視申請的案件詳細資料/u55.png"}},
{
          "id":"04da2858913b497e8624d0c884394010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC66,
              "opacity":1},
            "location":{
              "x":476,
              "y":123},
            "size":{
              "width":634,
              "height":50},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66CC33},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21d6ad48428479184517212b46296bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC66,
                  "opacity":1},
                "location":{
                  "x":476,
                  "y":123},
                "size":{
                  "width":634,
                  "height":50},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請的詳細資料/u73.png"}},
{
          "id":"bb3f94bca72f4b99b5bba9f76379c471",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC66,
              "opacity":1},
            "location":{
              "x":470,
              "y":216},
            "size":{
              "width":640,
              "height":47},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66CC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e11f26234c104dae8d5a5e81fe158cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC66,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":216},
                "size":{
                  "width":640,
                  "height":47},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請的詳細資料/u75.png"}},
{
          "id":"27509e4c5b404d5486665ca250775069",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":80},
            "size":{
              "width":200,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1450441c4c154f5db21e2d0fd95deed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":80},
                "size":{
                  "width":200,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "96e31ac88e3944cf843d8f845f224998":{
      "packageId":"96e31ac88e3944cf843d8f845f224998",
      "type":"Axure:Master",
      "name":"dropdown",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"506f205c4d3f45b4a8d8879d40c585c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":117,
                "y":0},
              "size":{
                "width":170,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9b048d4c0424257a86f9053565fae84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":117,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44d2cae74264fe28efc5a9f011db65c",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":63},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"0ac610d031604d3e8252ebd82275eec3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b2490259cfb24a27937c8cc947bca228",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":102},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"17d97940863d453493d1773f25937fa8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":102},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 個人設定 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"個人設定.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"73dd3af138be44458bd25a2634764d55",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afb506fe892a47528ea57c3d3074e449",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"1a6249c0920944ceb89ae7e1be69ce09",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":141},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e45023e673d24bcda3e25c34b974ecef",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":141},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open TeleWork首頁 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"telework__.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7e4f70b8597e4e87b9a74652345d9ede",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":24},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7c6bb4ed82e4d73b9ed1dc1cf37732b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":24},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 遠距工作者登入後(找案件) in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"遠距工作者登入後_找案件_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db4e0239fc24aa5838f7a781f489e0f",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"18px",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099CC,
                        "opacity":1},
                      "location":{
                        "x":70,
                        "y":75},
                      "size":{
                        "width":170,
                        "height":36},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"26d3c97b49b9491e915ab197141698fb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"18px",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099CC,
                            "opacity":1},
                          "location":{
                            "x":70,
                            "y":75},
                          "size":{
                            "width":170,
                            "height":36},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u135.png"}},
{
                    "id":"5a69b865ebd6452ebabd85af7eedb35b",
                    "label":"",
                    "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "baseStyle":"627587b6038d43cca051c114ac41ad32",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":10,
                        "y":74},
                      "size":{
                        "width":220,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c28622cbcfd4bc198d16cf0651c1dac",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"f44d2cae74264fe28efc5a9f011db65c",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":10,
                            "y":74},
                          "size":{
                            "width":220,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 2",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 雇主登入後 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"雇主登入後.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"61887cf395474173a1dd468a457de938",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":-40,
                "y":50},
              "size":{
                "width":900,
                "height":460},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0571e4ff7de34900acd1a730a6b1eb2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":-40,
                    "y":50},
                  "size":{
                    "width":900,
                    "height":460},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["f44d2cae74264fe28efc5a9f011db65c"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73af37ef2bc548cfb218313275d91d54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":90},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9dc390a6c3e4fe89c75bd55943e8173",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":90},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 遠距工作者登入後(找案件) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"遠距工作者登入後_找案件_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c34866e4049b438ea46fb17ab8c63e6b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":10,
                "y":140},
              "size":{
                "width":220,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d929f16ffcd4e71bd2f5ca13b0d445f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":10,
                    "y":140},
                  "size":{
                    "width":220,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 雇主登入後 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"雇主登入後.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d1a1dfa27ac24ff2a583a261fc97d904":{
      "packageId":"d1a1dfa27ac24ff2a583a261fc97d904",
      "type":"Axure:Master",
      "name":"change currency",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9769e695b0664441b3ccd5fbff65efea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":44,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0513e769e9d247dcad8d4b622b25b6ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":0},
                  "size":{
                    "width":44,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle (Dynamic Panel)",
                        "objectsToFades":[{
                            "objectPath":["7fc383c5928e49879a99dc4d9df850ae"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/遠距工作者詳細資料/u146.png"}},
{
            "id":"7fc383c5928e49879a99dc4d9df850ae",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":66},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"e234e68ced72465cb1fa9db278729a4e",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"dde9df61cfeb4ad0b61066271a6d78ad",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":297,
                        "height":189}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc21472bed343a3aef07d5ca3ec1639",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":297,
                            "height":189}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u129.png"}},
{
                    "id":"b71ae81389e54486818e6630092762e8",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":30},
                      "size":{
                        "width":287,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c95221fca89e45be83003b35dbef975d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":287,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/遠距工作者詳細資料/u151.png"}},
{
                    "id":"e8b8f022d802460e81c3242754b4631b",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":24},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"57944770132240ff89cbea05872a77de",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":24},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cb28593ac22e4ff982b158f27a2b81af",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":58},
                      "size":{
                        "width":109,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"68c1f570ff814e418efd898b1f5a29aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":58},
                          "size":{
                            "width":109,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9eae22708664bd780e699248735f154",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":92},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7d5f6bf4eb94b728c3cd1c2ca7b230d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":92},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c0e451649a8443e6b1d18c009d17b970",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":126},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"604e76edfd1f4bc19d41c745717c608b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":126},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"3f060a28aabf42f0bc66baa1730d2dd1",
                    "label":"",
                    "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                      "fontSize":"18px",
                      "fontWeight":"500",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0099FF,
                        "opacity":1},
                      "location":{
                        "x":32,
                        "y":160},
                      "size":{
                        "width":91,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"95856e8d4e144148beb2044bf7442380",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7fc383c5928e49879a99dc4d9df850ae",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                          "fontSize":"18px",
                          "fontWeight":"500",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0099FF,
                            "opacity":1},
                          "location":{
                            "x":32,
                            "y":160},
                          "size":{
                            "width":91,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "d94c7ba1eaa34714a5d6253dffbe242f":{
      "packageId":"d94c7ba1eaa34714a5d6253dffbe242f",
      "type":"Axure:Master",
      "name":"newinfo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"288ab1dc513d4d93aa14fe7c5f12cb0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":276,
                "y":0},
              "size":{
                "width":60,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11c910fab7bd4dd2afd5b9891a0bd868",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":276,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle info",
                        "objectsToFades":[{
                            "objectPath":["086570bf076446d99e2f75e95782f03d"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"086570bf076446d99e2f75e95782f03d",
            "label":"info",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":73},
              "size":{
                "width":345,
                "height":142},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3f0f17c212483eac523909f62362b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":false,
                "style":{
                  "location":{
                    "x":0,
                    "y":73},
                  "size":{
                    "width":345,
                    "height":142},
                  "visible":false},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/遠距工作者詳細資料/info_u166.png"}}]}}},
  "objectPaths":{
    "893807cfbe25418ea3956dd49a061366":{
      "scriptId":"u0"},
    "b8d815b682d54da2936749bedc5be5ab":{
      "scriptId":"u1"},
    "15401ce1f59346348dfdafccfbc29b2e":{
      "scriptId":"u2"},
    "62291c47af084ba190999eb786ebccc2":{
      "scriptId":"u3"},
    "a53af35470214ace906b5d7b53003675":{
      "scriptId":"u4"},
    "2eceb128a14e48ecb97ea00bffb20a20":{
      "scriptId":"u5"},
    "3ebbe97e3b7a4baaac28640c37732e00":{
      "scriptId":"u6"},
    "314b7fc2688e4c2681c7673475650b96":{
      "scriptId":"u7"},
    "9b4f829b7e574218b93463f8e57776b2":{
      "scriptId":"u8"},
    "2e1c3cbf210f4b8cbe3b4dd0af81690a":{
      "scriptId":"u9"},
    "ae5196f09b724f37a707e2e5cb4d23f0":{
      "scriptId":"u10"},
    "2a120a52e65a4342b38fab867681894b":{
      "scriptId":"u11"},
    "d5cad7730cfd416d8b71c48ececefe71":{
      "scriptId":"u12"},
    "df51b1ea1df04f29be40b0349a126651":{
      "scriptId":"u13"},
    "b074eb5172044199bea2d5663bc14ebd":{
      "scriptId":"u14"},
    "7641440193f54c2682fb1c5eaf7d6ef5":{
      "scriptId":"u15"},
    "6c8a420414f74f19adc1f20fa67d8aa3":{
      "scriptId":"u16"},
    "0421fa1a8c404929b2d1a034fe3f3aed":{
      "scriptId":"u17"},
    "bc34ef8fe91d4a4aaae3ff511db390bf":{
      "scriptId":"u18"},
    "79b999f5dad94b598b904250f57965ad":{
      "scriptId":"u19"},
    "41e220a57adc44cdbc34fd17f4b249eb":{
      "scriptId":"u20"},
    "b1f6d440b79449b49f5ce41df91790f0":{
      "scriptId":"u21"},
    "a527f29fb6204f4ab1bf94d31b63d64c":{
      "scriptId":"u22"},
    "6ebf34ab81af425286ea3b5798a50629":{
      "scriptId":"u23"},
    "5359b28085b8428b9c20a06a94b69343":{
      "scriptId":"u24"},
    "1b962dcda274493fa5efd800dcc554a9":{
      "scriptId":"u25"},
    "0b3e9aee179e4281992a3f39e80bcc7f":{
      "scriptId":"u26",
      "506f205c4d3f45b4a8d8879d40c585c1":{
        "scriptId":"u27"},
      "e9b048d4c0424257a86f9053565fae84":{
        "scriptId":"u28"},
      "f44d2cae74264fe28efc5a9f011db65c":{
        "scriptId":"u29"},
      "b2490259cfb24a27937c8cc947bca228":{
        "scriptId":"u30"},
      "17d97940863d453493d1773f25937fa8":{
        "scriptId":"u31"},
      "73dd3af138be44458bd25a2634764d55":{
        "scriptId":"u32"},
      "afb506fe892a47528ea57c3d3074e449":{
        "scriptId":"u33"},
      "1a6249c0920944ceb89ae7e1be69ce09":{
        "scriptId":"u34"},
      "e45023e673d24bcda3e25c34b974ecef":{
        "scriptId":"u35"},
      "7e4f70b8597e4e87b9a74652345d9ede":{
        "scriptId":"u36"},
      "e7c6bb4ed82e4d73b9ed1dc1cf37732b":{
        "scriptId":"u37"},
      "1db4e0239fc24aa5838f7a781f489e0f":{
        "scriptId":"u38"},
      "26d3c97b49b9491e915ab197141698fb":{
        "scriptId":"u39"},
      "5a69b865ebd6452ebabd85af7eedb35b":{
        "scriptId":"u40"},
      "1c28622cbcfd4bc198d16cf0651c1dac":{
        "scriptId":"u41"},
      "61887cf395474173a1dd468a457de938":{
        "scriptId":"u42"},
      "0571e4ff7de34900acd1a730a6b1eb2e":{
        "scriptId":"u43"},
      "73af37ef2bc548cfb218313275d91d54":{
        "scriptId":"u44"},
      "f9dc390a6c3e4fe89c75bd55943e8173":{
        "scriptId":"u45"},
      "c34866e4049b438ea46fb17ab8c63e6b":{
        "scriptId":"u46"},
      "3d929f16ffcd4e71bd2f5ca13b0d445f":{
        "scriptId":"u47"}},
    "169f55803d354df68cc97924b53451f8":{
      "scriptId":"u48",
      "9769e695b0664441b3ccd5fbff65efea":{
        "scriptId":"u49"},
      "0513e769e9d247dcad8d4b622b25b6ae":{
        "scriptId":"u50"},
      "7fc383c5928e49879a99dc4d9df850ae":{
        "scriptId":"u51"},
      "dde9df61cfeb4ad0b61066271a6d78ad":{
        "scriptId":"u52"},
      "8dc21472bed343a3aef07d5ca3ec1639":{
        "scriptId":"u53"},
      "b71ae81389e54486818e6630092762e8":{
        "scriptId":"u54"},
      "c95221fca89e45be83003b35dbef975d":{
        "scriptId":"u55"},
      "e8b8f022d802460e81c3242754b4631b":{
        "scriptId":"u56"},
      "57944770132240ff89cbea05872a77de":{
        "scriptId":"u57"},
      "cb28593ac22e4ff982b158f27a2b81af":{
        "scriptId":"u58"},
      "68c1f570ff814e418efd898b1f5a29aa":{
        "scriptId":"u59"},
      "f9eae22708664bd780e699248735f154":{
        "scriptId":"u60"},
      "d7d5f6bf4eb94b728c3cd1c2ca7b230d":{
        "scriptId":"u61"},
      "c0e451649a8443e6b1d18c009d17b970":{
        "scriptId":"u62"},
      "604e76edfd1f4bc19d41c745717c608b":{
        "scriptId":"u63"},
      "3f060a28aabf42f0bc66baa1730d2dd1":{
        "scriptId":"u64"},
      "95856e8d4e144148beb2044bf7442380":{
        "scriptId":"u65"}},
    "d898c367cf8749f6829987dbfe331db8":{
      "scriptId":"u66",
      "288ab1dc513d4d93aa14fe7c5f12cb0e":{
        "scriptId":"u67"},
      "11c910fab7bd4dd2afd5b9891a0bd868":{
        "scriptId":"u68"},
      "086570bf076446d99e2f75e95782f03d":{
        "scriptId":"u69"},
      "7f3f0f17c212483eac523909f62362b1":{
        "scriptId":"u70"}},
    "8b3dd1f7d8e148f3aa2196056a2a3457":{
      "scriptId":"u71"},
    "e7250e61abe34eb4bc85e07ab15bc200":{
      "scriptId":"u72"},
    "04da2858913b497e8624d0c884394010":{
      "scriptId":"u73"},
    "d21d6ad48428479184517212b46296bd":{
      "scriptId":"u74"},
    "bb3f94bca72f4b99b5bba9f76379c471":{
      "scriptId":"u75"},
    "e11f26234c104dae8d5a5e81fe158cab":{
      "scriptId":"u76"},
    "27509e4c5b404d5486665ca250775069":{
      "scriptId":"u77"},
    "1450441c4c154f5db21e2d0fd95deed6":{
      "scriptId":"u78"}}});