$axure.loadCurrentPage({
  "url":"儲存過的.html",
  "generationDate":new Date(1404292444741.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"831bf66a93df47b3bb7d09f26c62609f",
    "type":"Axure:Page",
    "name":"儲存過的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12e7b6a2621a4cb498412df19aa6a29f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2476ed23ff74f30954dd8d59c4344e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"546b662cb0f04f8f84c91e2a104fc833",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1902,
              "height":640},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c0fa502ad2343848053ef8c139a6ac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1902,
                  "height":640},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u0.png"}},
{
          "id":"e2f6033b5b6e47ea851108d0e7c501ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1902,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f3cdc9a693146518dcdb8a78e2be8af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1902,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u2.png"}},
{
          "id":"a938babafa0b45b3810e17a9f85b06e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":160},
            "size":{
              "width":1024,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c420adc110a94d519a4032df0cf11ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":160},
                "size":{
                  "width":1024,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u4.png"}},
{
          "id":"f993b92e19f54bfc95929833266de957",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71cd779a55444dbc9bf6cb26c3224e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"561fc38714f14370922521fbd346882b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a1b3286d0245cd9d73a056312908bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u8.png"}},
{
          "id":"899acdb8dd634f28a48207d1aca85478",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941df686d9cc4da482ebf215dfc824cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"119a64dd9fd34d65bc4441758f80d249",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f29e20e09d943d7a91225f8fdf2a56c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":190},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u16.png"}},
{
          "id":"1fbacb81ec31475b97ea7dac1abf7fef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":615,
              "y":190},
            "size":{
              "width":41,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb713e16569491d8c84fc2158212ff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":615,
                  "y":190},
                "size":{
                  "width":41,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u18.png"}},
{
          "id":"00cc82b3efdc42f4bfd82db077d9315b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":203},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0422d0c27e14359bcd68d982df18364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":203},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u20.png"}},
{
          "id":"d013991d21014c29a737de478c41fe68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":260},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81c8b94683d447448c21df8c09aced03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":260},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1acd1a173384ea7a6ae227c002477f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f802fbe0464579bd9d2c3709026745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b963c713c8c04bcf857eb695563a88d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":480,
              "y":380},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c531ad8bea2c42f388bfa986a8c31982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":380},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u22.png"}},
{
          "id":"c8b4971205d643b3afba592b089d2cd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":260},
            "size":{
              "width":730,
              "height":400},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e125546b1e54e80bd508e7cc711e960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":260},
                "size":{
                  "width":730,
                  "height":400},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u26.png"}},
{
          "id":"8a2eb5a983be4c82bbd0122221475b4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":328},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0fa02e276eb44b19c3bed9741efa5f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":328},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u30.png"}},
{
          "id":"f777c053a5ca495b891afab650942fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":316},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af7757cb2d6423da8bab42fd6ef6419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":316},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"1d9b63fe90d44dcebec2f20a97bbb951",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":328},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371d2d04641342489e5b08e7e7a87311",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":328},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"b29e05c1d6dd4150ac0f294ed6d73ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":340},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300d54cf02fb4f72ace2ea6679034d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":340},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"3c53f13483c64d7b81bd630fcb5cec35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":402},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69fcadfbf6394feca5c6381cfc10ae48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":402},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u38.jpg"}},
{
          "id":"94c29fa9411141798d743f8d7c528d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":390},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d731973fc61349c6b999d94a97072fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":390},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"dc0063c75f614cf9b1d5b588d0a29f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":402},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18427a7bbc2b49048455ed0919e7fdf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":402},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"419acde1aad24ed4b005bb21c5ab7d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":414},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93ab41f9bec24748b13b5948f276a9d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":414},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"b1650fdeb3ff4fcc9fe8ffb167cd6e74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":482},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f4d4068d7ae4887858bfb064bf98b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":482},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u46.jpg"}},
{
          "id":"eea229b6c7be4d4dac0f13391ed6387d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":470},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b776890b4fe43c9ad66019ffcd94285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":470},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"0e851d8a459b42d49793a06c8800f710",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":482},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a37385f056bc44638b486fb013a87d60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":482},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"ba6dc1b3e32a4b4db9fa1e32c940e0b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":494},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fb93bbb4d04bdfa57c98257915cf6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":494},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"736896c3406b490ca7a546be4e959155",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":578},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a27653f59c4eb092b04816fff2e9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":578},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u54.jpg"}},
{
          "id":"ec5ee96ee34644518690c854820112ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":566},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c1f53a1f504e64a0bfda30df0921e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":566},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"b4f100b475a64c42973554486883ebe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":578},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf4e74b20d0467880cb178459710729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":578},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"ddfd05d4319c465b9d7e12d5c2da2a8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":590},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451a00c5ee814ee2b680874e4bc7e3e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":590},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"4accb46d2af246e68a522799315b0bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":974,
              "y":262},
            "size":{
              "width":200,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71de4ff2ee5040a7a10ae7a4b0a619ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":974,
                  "y":262},
                "size":{
                  "width":200,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申請案件-檢視案件合約/u22.png"}},
{
          "id":"4f80ce20c7804d1f98eeb3fc27ac9e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":316},
            "size":{
              "width":190,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dabe9b3591c3454482a6ff496333f71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":316},
                "size":{
                  "width":190,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u62.png"}},
{
          "id":"bfb0358a1ed24dfe88ffd2cfb7d75985",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":396},
            "size":{
              "width":190,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1da87aa76e94fbf9189c7c289333b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":396},
                "size":{
                  "width":190,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u62.png"}},
{
          "id":"b1552e57a1b74d8e8bbb09cc88125ccf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":476},
            "size":{
              "width":190,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9637331229ed4d58a6269d38a5302cbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":476},
                "size":{
                  "width":190,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u62.png"}},
{
          "id":"508b6919559e44779d943a41b1774588",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":566},
            "size":{
              "width":190,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c3dbb148c948b0806dfdf02eae1569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":566},
                "size":{
                  "width":190,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/儲存過的/u62.png"}},
{
          "id":"a185e01c623b41cb82d694b39fe36aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":613},
            "size":{
              "width":119,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598c9eed8857461f9e672f6e190d243b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":613},
                "size":{
                  "width":119,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u58.png"}},
{
          "id":"1f54b4f78f2d442ab7d5b1f91ee59ef5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1466,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88addcaace2e4992b5f00f4c3432e166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1466,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u0.png"}},
{
          "id":"fa615e643ded47729cfce51cbcd8c7e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17fe9774f614491dad54112ab99a0021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"918e315db32c4361a325fe5626a4d466",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":10},
            "size":{
              "width":138,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74a57f25b7b7450fb33e3ea5f33eb154",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":10},
                "size":{
                  "width":138,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80b1d214b5e1498cbc167770d5127543",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":616,
              "y":10},
            "size":{
              "width":83,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6352c178ef074675beb06b9fa9e80067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":616,
                  "y":10},
                "size":{
                  "width":83,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3664367dadb04c2faa5c457343231a42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":737,
              "y":10},
            "size":{
              "width":55,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ffb997123bb437d8becc3e57fa2d9ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":737,
                  "y":10},
                "size":{
                  "width":55,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c66d499b9204801914acd7d81be3c7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":830,
              "y":10},
            "size":{
              "width":58,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2fa52dd1e2432d8d0a2efbc01a35c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":830,
                  "y":10},
                "size":{
                  "width":58,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75ea2b6776314002b7aa62a0aeb48357",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1903,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec6a1d31e0fb4b53a0fd45db834b75c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1903,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u51.png"}},
{
          "id":"be4c14f5decb4e3dae46cc6531140a34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"432bed4fa41c4de4ab5afbd62370d179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f07fee3e29034c92a9a3017eb70f87b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":370,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d712115ec34520b8ee045b20401f0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":370,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"441f7f4d45544785b427501b02dff1c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d17cd692b1ea4d7f9a4e93fc302ad85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26730d35272d4e568642a3f53cd47eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c2579f7e5674ce59b0e275874a7350c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14613456343e4203a68a47f355005b96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":353},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b678a9cd364c7ea9c53998fb6e7152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":353},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"4a23d45c5fcf4543a4f0e6030c483790",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":446},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6197eb6fc95b422f90841d6d77245d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":446},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"a150a28a67d44902a72edf4c9ffd0c62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":529},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817e367972784bf3974d6502f46ebb7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":529},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"a2893917dc394d9782bd65976b7a502b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":613},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bfe1175d6e44456aba15d0deea01b80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":613},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"890bb2bf25654877a2d3c64d19803b71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1270,
              "y":613},
            "size":{
              "width":119,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77fc21b941a54f2d8986618f603f0948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1270,
                  "y":613},
                "size":{
                  "width":119,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 連絡遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"連絡遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d6f833f533b4008bd457562ae37ebef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c53e8d3bf4b4fa19aa2dbac4e9b6fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de9628cfe11f4814a89286fd274a0988",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f15c79b0a9040f2a8dcfeceff4adb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c93373ba79b145f0aabf3dc0b4c92d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ebf035760ef4095835d0614e0ae4c4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bd8916bba0c490788c3b36b34ee597a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6c5e67926f42eb927e1473eadcb3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88af634f4b5c4c9cb2c13178e2de8ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60d16c542f094434a85621bd4f82e2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "12e7b6a2621a4cb498412df19aa6a29f":{
      "scriptId":"u0"},
    "f2476ed23ff74f30954dd8d59c4344e0":{
      "scriptId":"u1"},
    "546b662cb0f04f8f84c91e2a104fc833":{
      "scriptId":"u2"},
    "1c0fa502ad2343848053ef8c139a6ac7":{
      "scriptId":"u3"},
    "e2f6033b5b6e47ea851108d0e7c501ff":{
      "scriptId":"u4"},
    "1f3cdc9a693146518dcdb8a78e2be8af":{
      "scriptId":"u5"},
    "a938babafa0b45b3810e17a9f85b06e8":{
      "scriptId":"u6"},
    "c420adc110a94d519a4032df0cf11ffd":{
      "scriptId":"u7"},
    "f993b92e19f54bfc95929833266de957":{
      "scriptId":"u8"},
    "71cd779a55444dbc9bf6cb26c3224e87":{
      "scriptId":"u9"},
    "561fc38714f14370922521fbd346882b":{
      "scriptId":"u10"},
    "90a1b3286d0245cd9d73a056312908bc":{
      "scriptId":"u11"},
    "899acdb8dd634f28a48207d1aca85478":{
      "scriptId":"u12"},
    "941df686d9cc4da482ebf215dfc824cb":{
      "scriptId":"u13"},
    "119a64dd9fd34d65bc4441758f80d249":{
      "scriptId":"u14"},
    "9f29e20e09d943d7a91225f8fdf2a56c":{
      "scriptId":"u15"},
    "1fbacb81ec31475b97ea7dac1abf7fef":{
      "scriptId":"u16"},
    "9eb713e16569491d8c84fc2158212ff1":{
      "scriptId":"u17"},
    "00cc82b3efdc42f4bfd82db077d9315b":{
      "scriptId":"u18"},
    "f0422d0c27e14359bcd68d982df18364":{
      "scriptId":"u19"},
    "d013991d21014c29a737de478c41fe68":{
      "scriptId":"u20"},
    "81c8b94683d447448c21df8c09aced03":{
      "scriptId":"u21"},
    "a1acd1a173384ea7a6ae227c002477f6":{
      "scriptId":"u22"},
    "69f802fbe0464579bd9d2c3709026745":{
      "scriptId":"u23"},
    "b963c713c8c04bcf857eb695563a88d1":{
      "scriptId":"u24"},
    "c531ad8bea2c42f388bfa986a8c31982":{
      "scriptId":"u25"},
    "c8b4971205d643b3afba592b089d2cd7":{
      "scriptId":"u26"},
    "7e125546b1e54e80bd508e7cc711e960":{
      "scriptId":"u27"},
    "8a2eb5a983be4c82bbd0122221475b4a":{
      "scriptId":"u28"},
    "b0fa02e276eb44b19c3bed9741efa5f8":{
      "scriptId":"u29"},
    "f777c053a5ca495b891afab650942fea":{
      "scriptId":"u30"},
    "9af7757cb2d6423da8bab42fd6ef6419":{
      "scriptId":"u31"},
    "1d9b63fe90d44dcebec2f20a97bbb951":{
      "scriptId":"u32"},
    "371d2d04641342489e5b08e7e7a87311":{
      "scriptId":"u33"},
    "b29e05c1d6dd4150ac0f294ed6d73ec1":{
      "scriptId":"u34"},
    "300d54cf02fb4f72ace2ea6679034d09":{
      "scriptId":"u35"},
    "3c53f13483c64d7b81bd630fcb5cec35":{
      "scriptId":"u36"},
    "69fcadfbf6394feca5c6381cfc10ae48":{
      "scriptId":"u37"},
    "94c29fa9411141798d743f8d7c528d38":{
      "scriptId":"u38"},
    "d731973fc61349c6b999d94a97072fba":{
      "scriptId":"u39"},
    "dc0063c75f614cf9b1d5b588d0a29f4e":{
      "scriptId":"u40"},
    "18427a7bbc2b49048455ed0919e7fdf2":{
      "scriptId":"u41"},
    "419acde1aad24ed4b005bb21c5ab7d19":{
      "scriptId":"u42"},
    "93ab41f9bec24748b13b5948f276a9d6":{
      "scriptId":"u43"},
    "b1650fdeb3ff4fcc9fe8ffb167cd6e74":{
      "scriptId":"u44"},
    "5f4d4068d7ae4887858bfb064bf98b3c":{
      "scriptId":"u45"},
    "eea229b6c7be4d4dac0f13391ed6387d":{
      "scriptId":"u46"},
    "3b776890b4fe43c9ad66019ffcd94285":{
      "scriptId":"u47"},
    "0e851d8a459b42d49793a06c8800f710":{
      "scriptId":"u48"},
    "a37385f056bc44638b486fb013a87d60":{
      "scriptId":"u49"},
    "ba6dc1b3e32a4b4db9fa1e32c940e0b9":{
      "scriptId":"u50"},
    "a4fb93bbb4d04bdfa57c98257915cf6a":{
      "scriptId":"u51"},
    "736896c3406b490ca7a546be4e959155":{
      "scriptId":"u52"},
    "66a27653f59c4eb092b04816fff2e9bc":{
      "scriptId":"u53"},
    "ec5ee96ee34644518690c854820112ef":{
      "scriptId":"u54"},
    "04c1f53a1f504e64a0bfda30df0921e2":{
      "scriptId":"u55"},
    "b4f100b475a64c42973554486883ebe0":{
      "scriptId":"u56"},
    "6cf4e74b20d0467880cb178459710729":{
      "scriptId":"u57"},
    "ddfd05d4319c465b9d7e12d5c2da2a8f":{
      "scriptId":"u58"},
    "451a00c5ee814ee2b680874e4bc7e3e9":{
      "scriptId":"u59"},
    "4accb46d2af246e68a522799315b0bc8":{
      "scriptId":"u60"},
    "71de4ff2ee5040a7a10ae7a4b0a619ec":{
      "scriptId":"u61"},
    "4f80ce20c7804d1f98eeb3fc27ac9e97":{
      "scriptId":"u62"},
    "dabe9b3591c3454482a6ff496333f71c":{
      "scriptId":"u63"},
    "bfb0358a1ed24dfe88ffd2cfb7d75985":{
      "scriptId":"u64"},
    "d1da87aa76e94fbf9189c7c289333b78":{
      "scriptId":"u65"},
    "b1552e57a1b74d8e8bbb09cc88125ccf":{
      "scriptId":"u66"},
    "9637331229ed4d58a6269d38a5302cbc":{
      "scriptId":"u67"},
    "508b6919559e44779d943a41b1774588":{
      "scriptId":"u68"},
    "40c3dbb148c948b0806dfdf02eae1569":{
      "scriptId":"u69"},
    "a185e01c623b41cb82d694b39fe36aa8":{
      "scriptId":"u70"},
    "598c9eed8857461f9e672f6e190d243b":{
      "scriptId":"u71"},
    "1f54b4f78f2d442ab7d5b1f91ee59ef5":{
      "scriptId":"u72"},
    "88addcaace2e4992b5f00f4c3432e166":{
      "scriptId":"u73"},
    "fa615e643ded47729cfce51cbcd8c7e8":{
      "scriptId":"u74"},
    "17fe9774f614491dad54112ab99a0021":{
      "scriptId":"u75"},
    "918e315db32c4361a325fe5626a4d466":{
      "scriptId":"u76"},
    "74a57f25b7b7450fb33e3ea5f33eb154":{
      "scriptId":"u77"},
    "80b1d214b5e1498cbc167770d5127543":{
      "scriptId":"u78"},
    "6352c178ef074675beb06b9fa9e80067":{
      "scriptId":"u79"},
    "3664367dadb04c2faa5c457343231a42":{
      "scriptId":"u80"},
    "2ffb997123bb437d8becc3e57fa2d9ee":{
      "scriptId":"u81"},
    "9c66d499b9204801914acd7d81be3c7c":{
      "scriptId":"u82"},
    "2e2fa52dd1e2432d8d0a2efbc01a35c8":{
      "scriptId":"u83"},
    "75ea2b6776314002b7aa62a0aeb48357":{
      "scriptId":"u84"},
    "ec6a1d31e0fb4b53a0fd45db834b75c0":{
      "scriptId":"u85"},
    "be4c14f5decb4e3dae46cc6531140a34":{
      "scriptId":"u86"},
    "432bed4fa41c4de4ab5afbd62370d179":{
      "scriptId":"u87"},
    "f07fee3e29034c92a9a3017eb70f87b4":{
      "scriptId":"u88"},
    "46d712115ec34520b8ee045b20401f0f":{
      "scriptId":"u89"},
    "441f7f4d45544785b427501b02dff1c9":{
      "scriptId":"u90"},
    "d17cd692b1ea4d7f9a4e93fc302ad85b":{
      "scriptId":"u91"},
    "26730d35272d4e568642a3f53cd47eb1":{
      "scriptId":"u92"},
    "3c2579f7e5674ce59b0e275874a7350c":{
      "scriptId":"u93"},
    "14613456343e4203a68a47f355005b96":{
      "scriptId":"u94"},
    "88b678a9cd364c7ea9c53998fb6e7152":{
      "scriptId":"u95"},
    "4a23d45c5fcf4543a4f0e6030c483790":{
      "scriptId":"u96"},
    "6197eb6fc95b422f90841d6d77245d74":{
      "scriptId":"u97"},
    "a150a28a67d44902a72edf4c9ffd0c62":{
      "scriptId":"u98"},
    "817e367972784bf3974d6502f46ebb7f":{
      "scriptId":"u99"},
    "a2893917dc394d9782bd65976b7a502b":{
      "scriptId":"u100"},
    "0bfe1175d6e44456aba15d0deea01b80":{
      "scriptId":"u101"},
    "890bb2bf25654877a2d3c64d19803b71":{
      "scriptId":"u102"},
    "77fc21b941a54f2d8986618f603f0948":{
      "scriptId":"u103"},
    "4d6f833f533b4008bd457562ae37ebef":{
      "scriptId":"u104"},
    "4c53e8d3bf4b4fa19aa2dbac4e9b6fed":{
      "scriptId":"u105"},
    "de9628cfe11f4814a89286fd274a0988":{
      "scriptId":"u106"},
    "9f15c79b0a9040f2a8dcfeceff4adb09":{
      "scriptId":"u107"},
    "c93373ba79b145f0aabf3dc0b4c92d91":{
      "scriptId":"u108"},
    "2ebf035760ef4095835d0614e0ae4c4d":{
      "scriptId":"u109"},
    "1bd8916bba0c490788c3b36b34ee597a":{
      "scriptId":"u110"},
    "cf6c5e67926f42eb927e1473eadcb3b9":{
      "scriptId":"u111"},
    "88af634f4b5c4c9cb2c13178e2de8ed9":{
      "scriptId":"u112"},
    "60d16c542f094434a85621bd4f82e2cc":{
      "scriptId":"u113"}}});