$axure.loadCurrentPage({
  "url":"傳送過訊息的.html",
  "generationDate":new Date(1404292444563.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"d1abd4f8c39e46a5949f558060e7f480",
    "type":"Axure:Page",
    "name":"傳送過訊息的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"865c9ff389b94c9a82531696dcdbcaa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1902,
              "height":640},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4adc2d6f684dec9d2e7cbfae8e71d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1902,
                  "height":640},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u0.png"}},
{
          "id":"c07aab6c855d4dda9977f53e9c227605",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1902,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371248879750446a9a77781f63a1f827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1902,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u2.png"}},
{
          "id":"1276a0ff370e4c54a9415933f602a4af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":160},
            "size":{
              "width":1024,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"657c03edce35496b8126cc6add79ecc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":160},
                "size":{
                  "width":1024,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u4.png"}},
{
          "id":"5b46e468de6845a9b9eb7d11cb6f7d04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":0},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca6bf007c174c30bf524f301f877fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":0},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"e5b266a4e42048938c66d777c4cd6209",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed48dbdc36346ca9400d8943c3b5ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u8.png"}},
{
          "id":"f826dd25c6ac4cf3941069f7087e91cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d76acb10b9844baaa5ce5315905160ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7babf7297922475596f66974b47404f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b188606a274df08fdb23430e40f270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":190},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u16.png"}},
{
          "id":"72d4de24cbaf417eb6c49287363008bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":615,
              "y":190},
            "size":{
              "width":41,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"081683b5e46947a689cc1fddd270eb49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":615,
                  "y":190},
                "size":{
                  "width":41,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u18.png"}},
{
          "id":"68ec31104c554a53aa3fe515b704ce1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":203},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a20c5d4e31451dbd3ba6b382df0a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":203},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u20.png"}},
{
          "id":"79de53e6f2f04618ae9915b46b7c3b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":260},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db4a57d18678460fb80db30a1437be73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":260},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78386229d2ef41019f925a19eda71e65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":480,
              "y":320},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8791deb3184579b083b1e887995c83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":320},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u22.png"}},
{
          "id":"fe2aad2c5e814401889587d80abaf8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":380},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6bbffd1e6e44becb3067e5c8156eb71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":380},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u26.png"}},
{
          "id":"7ab7fa4418a442ebba6e0a111eb58bf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":260},
            "size":{
              "width":730,
              "height":380},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"566ab2af63d3445795b42c02f8ef12f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":260},
                "size":{
                  "width":730,
                  "height":380},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u28.png"}},
{
          "id":"14b118db9a8a4ba096437e268c0832d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":298},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c6ee7a7f9394fd5b2c1798673c1614d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":298},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u30.png"}},
{
          "id":"f736312a96de41929aad8de1639b9460",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":286},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b221789f5c4343a34bc00455fc9711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":286},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"9bfb8e5aabb045e0ba6849124667f358",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":298},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2719393dc5b043bbb4533f0c5fa5e9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":298},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"4e1b31b620bf48efaa03e5471fdda51b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":310},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45039e303664423ab3ae106b185d46f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":310},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"9ce4dbd2ae2345d5bd16da358d01fda7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":381},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"608d86d5aee643b8b7a94c8532837323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":381},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u38.jpg"}},
{
          "id":"07ba36fc3da54bdba4aff9329a6b6de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":369},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dafbfb5b9eb4aa3803e747f1f816ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":369},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"41f179f2684745c5aff41377f398ce77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":381},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0081cbb453483fa7d49c2bb4cb8f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":381},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"ed9db4b34d124bc9ba9043c6839b9c41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1356,
              "y":393},
            "size":{
              "width":13,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15a767ec48c44c70b392cee63c5918f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1356,
                  "y":393},
                "size":{
                  "width":13,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u44.png"}},
{
          "id":"7db4238004644460ab463d9eb990baec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":465},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86e3676848f04041bd47379d51ae17e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":465},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u46.jpg"}},
{
          "id":"1f07371864984b22bec0ce1b72bb5875",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":453},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2790242bfd6a495a8aeae8218c33c12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":453},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"2c037a93a6134ff99b0a7e5b03225a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":465},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75bf61ce1ed44a49a4ba47ff8be4329a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":465},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"ba6483758c3e4a40a03c082cf59b8afd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":477},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a098a2c48d945de9379ffc58a068f7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":477},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"097fd0d9049743ed84b2d9f8cdc87707",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":548},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d706a05adc7e45c99d549381bb862106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":548},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u54.jpg"}},
{
          "id":"502bf1a46761472790519952052942ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":751,
              "y":536},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e328c749b6d49cc9e3e7f7f0f821ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":751,
                  "y":536},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"e6c1d1cf9fb945a39bcb1d55b164246f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":548},
            "size":{
              "width":119,
              "height":34},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b8079b3730484f94f94f82908abf3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":548},
                "size":{
                  "width":119,
                  "height":34},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u30.png"}},
{
          "id":"54fadf3b441740cd85e90be99215033d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1364,
              "y":560},
            "size":{
              "width":10,
              "height":7},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76133781976f4bd58be92f092fa8fc4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1364,
                  "y":560},
                "size":{
                  "width":10,
                  "height":7},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u36.png"}},
{
          "id":"299a51d6a72d46948d0dd97d766e748f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1270,
              "y":583},
            "size":{
              "width":119,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6931317241ab41d1bc542eb6200cff18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1270,
                  "y":583},
                "size":{
                  "width":119,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u58.png"}},
{
          "id":"16c206d1dac04ea68f0e4e62aa66253b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1474,
              "y":10},
            "size":{
              "width":438,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea2286e6c7244748eea1b45c0668879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1474,
                  "y":10},
                "size":{
                  "width":438,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日誌/u6.png"}},
{
          "id":"d73d397cfec24bc7a8f003531f32714f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":20},
            "size":{
              "width":138,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"222f236d462347a0905ad55030cdf76a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":20},
                "size":{
                  "width":138,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70285aebbc1d4c4980cf4d1119ff9341",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1903,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"518fa4fdb3804741ba542a423c970e81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1903,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/檢視案件申請人清單/u51.png"}},
{
          "id":"db59459d08dc4896ae50d510ef6d0f4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":240,
              "y":20},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92bbba1437b345c397a16a983811a052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":240,
                  "y":20},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 雇主登入後 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"雇主登入後.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"588bf71d258d463e85b4b0c580400f5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":380,
              "y":20},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd755d2e2c9d4374b0d3f7c75adadda5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":380,
                  "y":20},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36776b18874045048e0168bb02145c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1caceac8f74ba8b6fa27d92dddc259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1db17240159842c1abf1fae1b53df6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":560,
              "y":20},
            "size":{
              "width":70,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce611538578f4871bd2146168df14515",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":560,
                  "y":20},
                "size":{
                  "width":70,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 訊息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b770f546c9e34f7d92d044c59c34bf8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":990,
              "y":286},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34afd9725cfb4761986ecd4c66ff88d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":990,
                  "y":286},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"748f1ea73a25493cb106b686321fcdf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":990,
              "y":370},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e534e3e100184278a8b8253c2540e307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":990,
                  "y":370},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"c3594fb70c8a4891a42f4aff97ed57ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":990,
              "y":454},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d31a5d725644c708a7fb6b6b5a7ef56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":990,
                  "y":454},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"f6b0520be0624d59b42d6d6829630046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":990,
              "y":538},
            "size":{
              "width":213,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2403a683f9f64700b0be19ddd0f753aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":990,
                  "y":538},
                "size":{
                  "width":213,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/傳送過訊息的/u28.png"}},
{
          "id":"cfc3ade9523147bb8dfd09a37bf3d153",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":323},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24068956869a41869ba9539fd53e23f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":323},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"1b01f08e2a94441aac0ca624262dd879",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":416},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22cbe773fa1641f8b2dc492ed7f2ae28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":416},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"5f0edb61de814260ae9cf88a056a3065",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":499},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56253b44082548309c80ada680e89258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":499},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"7a8a39b6d03e44758cf96d00b0f8ded4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":583},
            "size":{
              "width":90,
              "height":37},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af77884e808b4964a690d4cf662ba90a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":583},
                "size":{
                  "width":90,
                  "height":37},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理我的團隊/u92.png"}},
{
          "id":"6c119449b18f4d25ab39edf8cb0f6cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1270,
              "y":606},
            "size":{
              "width":119,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e32c99f860347e2834d45237bd9a59a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1270,
                  "y":606},
                "size":{
                  "width":119,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 連絡遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"連絡遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c62486593a48a18ee1ec4f4d5f3c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":754,
              "y":276},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85fc464217d9416fbddbb45108bb36ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":754,
                  "y":276},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4884ab9628d4f8a886cbed552ed2bb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":751,
              "y":374},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0467cf9229842f2aaa761f24c7e5f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":751,
                  "y":374},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0adb4c5551ee44a5baba22068c2c1c58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":751,
              "y":455},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9319341f5eb8480ba9bff50c72962641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":751,
                  "y":455},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc19406493244f499969532bc59430b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":754,
              "y":538},
            "size":{
              "width":246,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9ab14c6c2847788171dcc0ddc86bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":754,
                  "y":538},
                "size":{
                  "width":246,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40cb3731303a47309a26eaf74fc53aa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9432cf95948e4abcae44286f1007cd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b61f90c259554e498129756dc9eca9a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa94f3bab5744f3a6baf0832fe13937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d16df71e696d48359572b612155490bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":650,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e515b949a8884eec8098e2bdec460f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":650,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視工作日誌 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視工作日誌.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66703f3120174054bbf1cd27b9737412",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":120},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a452acc1eb44df9d4056f04633c6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":120},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 檢視合約列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"檢視合約列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8b6e2a9e26f483882b68f427a5e4c56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":480,
              "y":121},
            "size":{
              "width":150,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b82ec21b5e2442caa53fe0d7e02cad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":480,
                  "y":121},
                "size":{
                  "width":150,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 管理我的團隊 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"管理我的團隊.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "865c9ff389b94c9a82531696dcdbcaa8":{
      "scriptId":"u0"},
    "cd4adc2d6f684dec9d2e7cbfae8e71d0":{
      "scriptId":"u1"},
    "c07aab6c855d4dda9977f53e9c227605":{
      "scriptId":"u2"},
    "371248879750446a9a77781f63a1f827":{
      "scriptId":"u3"},
    "1276a0ff370e4c54a9415933f602a4af":{
      "scriptId":"u4"},
    "657c03edce35496b8126cc6add79ecc6":{
      "scriptId":"u5"},
    "5b46e468de6845a9b9eb7d11cb6f7d04":{
      "scriptId":"u6"},
    "7ca6bf007c174c30bf524f301f877fa4":{
      "scriptId":"u7"},
    "e5b266a4e42048938c66d777c4cd6209":{
      "scriptId":"u8"},
    "6ed48dbdc36346ca9400d8943c3b5ab1":{
      "scriptId":"u9"},
    "f826dd25c6ac4cf3941069f7087e91cf":{
      "scriptId":"u10"},
    "d76acb10b9844baaa5ce5315905160ee":{
      "scriptId":"u11"},
    "7babf7297922475596f66974b47404f5":{
      "scriptId":"u12"},
    "46b188606a274df08fdb23430e40f270":{
      "scriptId":"u13"},
    "72d4de24cbaf417eb6c49287363008bf":{
      "scriptId":"u14"},
    "081683b5e46947a689cc1fddd270eb49":{
      "scriptId":"u15"},
    "68ec31104c554a53aa3fe515b704ce1c":{
      "scriptId":"u16"},
    "a3a20c5d4e31451dbd3ba6b382df0a6f":{
      "scriptId":"u17"},
    "79de53e6f2f04618ae9915b46b7c3b1a":{
      "scriptId":"u18"},
    "db4a57d18678460fb80db30a1437be73":{
      "scriptId":"u19"},
    "78386229d2ef41019f925a19eda71e65":{
      "scriptId":"u20"},
    "ba8791deb3184579b083b1e887995c83":{
      "scriptId":"u21"},
    "fe2aad2c5e814401889587d80abaf8d9":{
      "scriptId":"u22"},
    "a6bbffd1e6e44becb3067e5c8156eb71":{
      "scriptId":"u23"},
    "7ab7fa4418a442ebba6e0a111eb58bf2":{
      "scriptId":"u24"},
    "566ab2af63d3445795b42c02f8ef12f1":{
      "scriptId":"u25"},
    "14b118db9a8a4ba096437e268c0832d2":{
      "scriptId":"u26"},
    "9c6ee7a7f9394fd5b2c1798673c1614d":{
      "scriptId":"u27"},
    "f736312a96de41929aad8de1639b9460":{
      "scriptId":"u28"},
    "c4b221789f5c4343a34bc00455fc9711":{
      "scriptId":"u29"},
    "9bfb8e5aabb045e0ba6849124667f358":{
      "scriptId":"u30"},
    "2719393dc5b043bbb4533f0c5fa5e9be":{
      "scriptId":"u31"},
    "4e1b31b620bf48efaa03e5471fdda51b":{
      "scriptId":"u32"},
    "45039e303664423ab3ae106b185d46f2":{
      "scriptId":"u33"},
    "9ce4dbd2ae2345d5bd16da358d01fda7":{
      "scriptId":"u34"},
    "608d86d5aee643b8b7a94c8532837323":{
      "scriptId":"u35"},
    "07ba36fc3da54bdba4aff9329a6b6de5":{
      "scriptId":"u36"},
    "9dafbfb5b9eb4aa3803e747f1f816ae5":{
      "scriptId":"u37"},
    "41f179f2684745c5aff41377f398ce77":{
      "scriptId":"u38"},
    "cd0081cbb453483fa7d49c2bb4cb8f56":{
      "scriptId":"u39"},
    "ed9db4b34d124bc9ba9043c6839b9c41":{
      "scriptId":"u40"},
    "15a767ec48c44c70b392cee63c5918f5":{
      "scriptId":"u41"},
    "7db4238004644460ab463d9eb990baec":{
      "scriptId":"u42"},
    "86e3676848f04041bd47379d51ae17e2":{
      "scriptId":"u43"},
    "1f07371864984b22bec0ce1b72bb5875":{
      "scriptId":"u44"},
    "2790242bfd6a495a8aeae8218c33c12c":{
      "scriptId":"u45"},
    "2c037a93a6134ff99b0a7e5b03225a4e":{
      "scriptId":"u46"},
    "75bf61ce1ed44a49a4ba47ff8be4329a":{
      "scriptId":"u47"},
    "ba6483758c3e4a40a03c082cf59b8afd":{
      "scriptId":"u48"},
    "4a098a2c48d945de9379ffc58a068f7b":{
      "scriptId":"u49"},
    "097fd0d9049743ed84b2d9f8cdc87707":{
      "scriptId":"u50"},
    "d706a05adc7e45c99d549381bb862106":{
      "scriptId":"u51"},
    "502bf1a46761472790519952052942ab":{
      "scriptId":"u52"},
    "1e328c749b6d49cc9e3e7f7f0f821ab6":{
      "scriptId":"u53"},
    "e6c1d1cf9fb945a39bcb1d55b164246f":{
      "scriptId":"u54"},
    "73b8079b3730484f94f94f82908abf3b":{
      "scriptId":"u55"},
    "54fadf3b441740cd85e90be99215033d":{
      "scriptId":"u56"},
    "76133781976f4bd58be92f092fa8fc4e":{
      "scriptId":"u57"},
    "299a51d6a72d46948d0dd97d766e748f":{
      "scriptId":"u58"},
    "6931317241ab41d1bc542eb6200cff18":{
      "scriptId":"u59"},
    "16c206d1dac04ea68f0e4e62aa66253b":{
      "scriptId":"u60"},
    "1ea2286e6c7244748eea1b45c0668879":{
      "scriptId":"u61"},
    "d73d397cfec24bc7a8f003531f32714f":{
      "scriptId":"u62"},
    "222f236d462347a0905ad55030cdf76a":{
      "scriptId":"u63"},
    "70285aebbc1d4c4980cf4d1119ff9341":{
      "scriptId":"u64"},
    "518fa4fdb3804741ba542a423c970e81":{
      "scriptId":"u65"},
    "db59459d08dc4896ae50d510ef6d0f4b":{
      "scriptId":"u66"},
    "92bbba1437b345c397a16a983811a052":{
      "scriptId":"u67"},
    "588bf71d258d463e85b4b0c580400f5b":{
      "scriptId":"u68"},
    "cd755d2e2c9d4374b0d3f7c75adadda5":{
      "scriptId":"u69"},
    "36776b18874045048e0168bb02145c94":{
      "scriptId":"u70"},
    "be1caceac8f74ba8b6fa27d92dddc259":{
      "scriptId":"u71"},
    "1db17240159842c1abf1fae1b53df6ff":{
      "scriptId":"u72"},
    "ce611538578f4871bd2146168df14515":{
      "scriptId":"u73"},
    "b770f546c9e34f7d92d044c59c34bf8a":{
      "scriptId":"u74"},
    "34afd9725cfb4761986ecd4c66ff88d7":{
      "scriptId":"u75"},
    "748f1ea73a25493cb106b686321fcdf7":{
      "scriptId":"u76"},
    "e534e3e100184278a8b8253c2540e307":{
      "scriptId":"u77"},
    "c3594fb70c8a4891a42f4aff97ed57ef":{
      "scriptId":"u78"},
    "4d31a5d725644c708a7fb6b6b5a7ef56":{
      "scriptId":"u79"},
    "f6b0520be0624d59b42d6d6829630046":{
      "scriptId":"u80"},
    "2403a683f9f64700b0be19ddd0f753aa":{
      "scriptId":"u81"},
    "cfc3ade9523147bb8dfd09a37bf3d153":{
      "scriptId":"u82"},
    "24068956869a41869ba9539fd53e23f2":{
      "scriptId":"u83"},
    "1b01f08e2a94441aac0ca624262dd879":{
      "scriptId":"u84"},
    "22cbe773fa1641f8b2dc492ed7f2ae28":{
      "scriptId":"u85"},
    "5f0edb61de814260ae9cf88a056a3065":{
      "scriptId":"u86"},
    "56253b44082548309c80ada680e89258":{
      "scriptId":"u87"},
    "7a8a39b6d03e44758cf96d00b0f8ded4":{
      "scriptId":"u88"},
    "af77884e808b4964a690d4cf662ba90a":{
      "scriptId":"u89"},
    "6c119449b18f4d25ab39edf8cb0f6cf8":{
      "scriptId":"u90"},
    "6e32c99f860347e2834d45237bd9a59a":{
      "scriptId":"u91"},
    "11c62486593a48a18ee1ec4f4d5f3c4b":{
      "scriptId":"u92"},
    "85fc464217d9416fbddbb45108bb36ef":{
      "scriptId":"u93"},
    "a4884ab9628d4f8a886cbed552ed2bb6":{
      "scriptId":"u94"},
    "f0467cf9229842f2aaa761f24c7e5f91":{
      "scriptId":"u95"},
    "0adb4c5551ee44a5baba22068c2c1c58":{
      "scriptId":"u96"},
    "9319341f5eb8480ba9bff50c72962641":{
      "scriptId":"u97"},
    "dc19406493244f499969532bc59430b4":{
      "scriptId":"u98"},
    "9d9ab14c6c2847788171dcc0ddc86bb8":{
      "scriptId":"u99"},
    "40cb3731303a47309a26eaf74fc53aa0":{
      "scriptId":"u100"},
    "9432cf95948e4abcae44286f1007cd4f":{
      "scriptId":"u101"},
    "b61f90c259554e498129756dc9eca9a4":{
      "scriptId":"u102"},
    "daa94f3bab5744f3a6baf0832fe13937":{
      "scriptId":"u103"},
    "d16df71e696d48359572b612155490bc":{
      "scriptId":"u104"},
    "e515b949a8884eec8098e2bdec460f2a":{
      "scriptId":"u105"},
    "66703f3120174054bbf1cd27b9737412":{
      "scriptId":"u106"},
    "c6a452acc1eb44df9d4056f04633c6ef":{
      "scriptId":"u107"},
    "a8b6e2a9e26f483882b68f427a5e4c56":{
      "scriptId":"u108"},
    "6b82ec21b5e2442caa53fe0d7e02cad4":{
      "scriptId":"u109"}}});