$axure.loadCurrentPage({
  "url":"telework__.html",
  "generationDate":new Date(1404292430057.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"18da3dbee0be4644bc90a336d2459cf7",
    "type":"Axure:Page",
    "name":"TeleWork首頁",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"71eb8337a15248fcb0702657a7361166",
          "label":"首頁-Lightbox",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":1920,
              "height":2697},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f22ee148ca4928b751969e3c5688d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":1920,
                  "height":2697},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 首頁-Lightbox",
                      "objectsToFades":[{
                          "objectPath":["71eb8337a15248fcb0702657a7361166"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/telework__/__-lightbox_u0.png"}},
{
          "id":"421a692327954381801ca9043a15ed82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":2697},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cda173f133a4935808de14767659185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":2697},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/telework__/u2.png"}},
{
          "id":"372317371bba4bb2bb3c9e2332f80d04",
          "label":"快速註冊警示1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1588,
              "y":224},
            "size":{
              "width":110,
              "height":30},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37165b589c9f49d1b6302706d09df1ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1588,
                  "y":224},
                "size":{
                  "width":110,
                  "height":30},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 快速註冊警示1",
                      "objectsToFades":[{
                          "objectPath":["372317371bba4bb2bb3c9e2332f80d04"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/telework__/快速註冊警示1_u4.png"}},
{
          "id":"15427b53c25a47cb8ed95e4f163063cf",
          "label":"快速註冊警示2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1588,
              "y":269},
            "size":{
              "width":110,
              "height":30},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300883a54d464981954316399b599d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1588,
                  "y":269},
                "size":{
                  "width":110,
                  "height":30},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide 快速註冊警示2",
                      "objectsToFades":[{
                          "objectPath":["15427b53c25a47cb8ed95e4f163063cf"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/telework__/快速註冊警示1_u4.png"}},
{
          "id":"466bb7fe723343778070abe178899d4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1623,
              "y":306},
            "size":{
              "width":86,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a26dbfacccf94765adf95221f08d49b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1623,
                  "y":306},
                "size":{
                  "width":86,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 快速註冊警示1,<br>快速註冊警示2",
                      "objectsToFades":[{
                          "objectPath":["372317371bba4bb2bb3c9e2332f80d04"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["15427b53c25a47cb8ed95e4f163063cf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81ee05ab3c242dc99bcfc158afb2257",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":570},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa849eb19ab43d0b3eedd15486679d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":570},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"661c8ae8a3654c27858444c4ec49215c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":710,
              "y":570},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b5d6ed136d4c938e47356bc709d309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":710,
                  "y":570},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dd2e483a4ec467ab7972b7af242c8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":570},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2385a91c01494497a2d00d772eae8154",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":570},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77566fb2f6964016a7652827fe391028",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1220,
              "y":570},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a7cd21fd7c43e68e3cb450f28d42e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1220,
                  "y":570},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8106af9ed9848a09aaa7d28432a861d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":870},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68627d3779574f7ea858ba8108f135a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":870},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea30bee95e30491581c6c14fde289529",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":710,
              "y":870},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f9f0210779d4cdca09c8b90cd5fa23e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":710,
                  "y":870},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf569dee9d024b509e5c555a36d19c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":960,
              "y":870},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60cb447e78b434fbaf5e1743720f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":960,
                  "y":870},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eca2f30b2ce48ac81a589dd3d2c1c60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1220,
              "y":870},
            "size":{
              "width":250,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9803061c4984d18ab535df4ce59c6cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1220,
                  "y":870},
                "size":{
                  "width":250,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜尋遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜尋遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff918c0ba32443ec8c927bfb8be0fad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti TC Light', 'Heiti TC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":17},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bfb597bbff4dc6b8ae948f1e1be7c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti TC Light', 'Heiti TC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":17},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 依照分類瀏覽遠距工作者 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"依照分類瀏覽遠距工作者.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c38fb19a16942f5b40d65c3edce2662",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti TC Light', 'Heiti TC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":606,
              "y":17},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82b993d70b0449df958af6597965006e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti TC Light', 'Heiti TC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":606,
                  "y":17},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 依照分類瀏覽案件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"依照分類瀏覽案件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a7f2ae8d23b40c093f809d0527dd8d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti TC Light', 'Heiti TC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":720,
              "y":17},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad912f67a4534768a41ad566a3512c8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti TC Light', 'Heiti TC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":720,
                  "y":17},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"Scroll to anchor (y only)",
                      "objectPath":["4d56c2d1f1ee479fba2b2ce332723b8c"],
                      "options":{
                        "direction":"vertical"}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d56c2d1f1ee479fba2b2ce332723b8c",
          "label":"anchor",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":1160},
            "size":{
              "width":200,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d352539ca224a3886142ac05db934f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":1160},
                "size":{
                  "width":200,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a5bee10f06d4924823aafc93c9d4719",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1720,
              "y":17},
            "size":{
              "width":100,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe4a2c252deb465ab6c525fcc4982a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1720,
                  "y":17},
                "size":{
                  "width":100,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登入頁 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登入頁_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bfba589d4204598b2c657d01e9e93f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1820,
              "y":17},
            "size":{
              "width":100,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba55415fd13648228fb4890528a48c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1820,
                  "y":17},
                "size":{
                  "width":100,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 註冊頁 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"註冊頁.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "71eb8337a15248fcb0702657a7361166":{
      "scriptId":"u0"},
    "b8f22ee148ca4928b751969e3c5688d3":{
      "scriptId":"u1"},
    "421a692327954381801ca9043a15ed82":{
      "scriptId":"u2"},
    "0cda173f133a4935808de14767659185":{
      "scriptId":"u3"},
    "372317371bba4bb2bb3c9e2332f80d04":{
      "scriptId":"u4"},
    "37165b589c9f49d1b6302706d09df1ab":{
      "scriptId":"u5"},
    "15427b53c25a47cb8ed95e4f163063cf":{
      "scriptId":"u6"},
    "300883a54d464981954316399b599d12":{
      "scriptId":"u7"},
    "466bb7fe723343778070abe178899d4f":{
      "scriptId":"u8"},
    "a26dbfacccf94765adf95221f08d49b9":{
      "scriptId":"u9"},
    "f81ee05ab3c242dc99bcfc158afb2257":{
      "scriptId":"u10"},
    "ffa849eb19ab43d0b3eedd15486679d2":{
      "scriptId":"u11"},
    "661c8ae8a3654c27858444c4ec49215c":{
      "scriptId":"u12"},
    "76b5d6ed136d4c938e47356bc709d309":{
      "scriptId":"u13"},
    "1dd2e483a4ec467ab7972b7af242c8f5":{
      "scriptId":"u14"},
    "2385a91c01494497a2d00d772eae8154":{
      "scriptId":"u15"},
    "77566fb2f6964016a7652827fe391028":{
      "scriptId":"u16"},
    "c2a7cd21fd7c43e68e3cb450f28d42e7":{
      "scriptId":"u17"},
    "d8106af9ed9848a09aaa7d28432a861d":{
      "scriptId":"u18"},
    "68627d3779574f7ea858ba8108f135a7":{
      "scriptId":"u19"},
    "ea30bee95e30491581c6c14fde289529":{
      "scriptId":"u20"},
    "8f9f0210779d4cdca09c8b90cd5fa23e":{
      "scriptId":"u21"},
    "cf569dee9d024b509e5c555a36d19c7e":{
      "scriptId":"u22"},
    "c60cb447e78b434fbaf5e1743720f9ef":{
      "scriptId":"u23"},
    "1eca2f30b2ce48ac81a589dd3d2c1c60":{
      "scriptId":"u24"},
    "c9803061c4984d18ab535df4ce59c6cc":{
      "scriptId":"u25"},
    "ff918c0ba32443ec8c927bfb8be0fad2":{
      "scriptId":"u26"},
    "a9bfb597bbff4dc6b8ae948f1e1be7c9":{
      "scriptId":"u27"},
    "4c38fb19a16942f5b40d65c3edce2662":{
      "scriptId":"u28"},
    "82b993d70b0449df958af6597965006e":{
      "scriptId":"u29"},
    "7a7f2ae8d23b40c093f809d0527dd8d7":{
      "scriptId":"u30"},
    "ad912f67a4534768a41ad566a3512c8f":{
      "scriptId":"u31"},
    "4d56c2d1f1ee479fba2b2ce332723b8c":{
      "scriptId":"u32"},
    "1d352539ca224a3886142ac05db934f9":{
      "scriptId":"u33"},
    "7a5bee10f06d4924823aafc93c9d4719":{
      "scriptId":"u34"},
    "fe4a2c252deb465ab6c525fcc4982a2b":{
      "scriptId":"u35"},
    "1bfba589d4204598b2c657d01e9e93f0":{
      "scriptId":"u36"},
    "ba55415fd13648228fb4890528a48c97":{
      "scriptId":"u37"}}});